/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Character Type Enum</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getCharacterTypeEnum()
 * @model
 * @generated
 */
public enum CharacterTypeEnum implements Enumerator
{
  /**
   * The '<em><b>ZOMBIE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZOMBIE_VALUE
   * @generated
   * @ordered
   */
  ZOMBIE(0, "ZOMBIE", "zombie"),

  /**
   * The '<em><b>GHOST</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GHOST_VALUE
   * @generated
   * @ordered
   */
  GHOST(1, "GHOST", "ghost"),

  /**
   * The '<em><b>PUMPKINBOMBER</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PUMPKINBOMBER_VALUE
   * @generated
   * @ordered
   */
  PUMPKINBOMBER(2, "PUMPKINBOMBER", "pumpkinbomber");

  /**
   * The '<em><b>ZOMBIE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ZOMBIE
   * @model literal="zombie"
   * @generated
   * @ordered
   */
  public static final int ZOMBIE_VALUE = 0;

  /**
   * The '<em><b>GHOST</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GHOST
   * @model literal="ghost"
   * @generated
   * @ordered
   */
  public static final int GHOST_VALUE = 1;

  /**
   * The '<em><b>PUMPKINBOMBER</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PUMPKINBOMBER
   * @model literal="pumpkinbomber"
   * @generated
   * @ordered
   */
  public static final int PUMPKINBOMBER_VALUE = 2;

  /**
   * An array of all the '<em><b>Character Type Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final CharacterTypeEnum[] VALUES_ARRAY =
    new CharacterTypeEnum[]
    {
      ZOMBIE,
      GHOST,
      PUMPKINBOMBER,
    };

  /**
   * A public read-only list of all the '<em><b>Character Type Enum</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<CharacterTypeEnum> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Character Type Enum</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CharacterTypeEnum get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      CharacterTypeEnum result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Character Type Enum</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CharacterTypeEnum getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      CharacterTypeEnum result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Character Type Enum</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static CharacterTypeEnum get(int value)
  {
    switch (value)
    {
      case ZOMBIE_VALUE: return ZOMBIE;
      case GHOST_VALUE: return GHOST;
      case PUMPKINBOMBER_VALUE: return PUMPKINBOMBER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private CharacterTypeEnum(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //CharacterTypeEnum


