/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Difficulty Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getLevel <em>Level</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#isInstantDeath <em>Instant Death</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getSpeedMultiplier <em>Speed Multiplier</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getDamageMultiplier <em>Damage Multiplier</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getMaxThreat <em>Max Threat</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getEnemyLimits <em>Enemy Limits</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig()
 * @model
 * @generated
 */
public interface DifficultyConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute.
   * The literals are from the enumeration {@link main.game.maze.dsl.mazeDsl.DifficultyLevel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.DifficultyLevel
   * @see #setLevel(DifficultyLevel)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_Level()
   * @model
   * @generated
   */
  DifficultyLevel getLevel();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getLevel <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Level</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.DifficultyLevel
   * @see #getLevel()
   * @generated
   */
  void setLevel(DifficultyLevel value);

  /**
   * Returns the value of the '<em><b>Instant Death</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instant Death</em>' attribute.
   * @see #setInstantDeath(boolean)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_InstantDeath()
   * @model
   * @generated
   */
  boolean isInstantDeath();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#isInstantDeath <em>Instant Death</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instant Death</em>' attribute.
   * @see #isInstantDeath()
   * @generated
   */
  void setInstantDeath(boolean value);

  /**
   * Returns the value of the '<em><b>Speed Multiplier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed Multiplier</em>' attribute.
   * @see #setSpeedMultiplier(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_SpeedMultiplier()
   * @model
   * @generated
   */
  double getSpeedMultiplier();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getSpeedMultiplier <em>Speed Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed Multiplier</em>' attribute.
   * @see #getSpeedMultiplier()
   * @generated
   */
  void setSpeedMultiplier(double value);

  /**
   * Returns the value of the '<em><b>Damage Multiplier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Damage Multiplier</em>' attribute.
   * @see #setDamageMultiplier(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_DamageMultiplier()
   * @model
   * @generated
   */
  double getDamageMultiplier();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getDamageMultiplier <em>Damage Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Damage Multiplier</em>' attribute.
   * @see #getDamageMultiplier()
   * @generated
   */
  void setDamageMultiplier(double value);

  /**
   * Returns the value of the '<em><b>Max Threat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Threat</em>' attribute.
   * @see #setMaxThreat(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_MaxThreat()
   * @model
   * @generated
   */
  int getMaxThreat();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getMaxThreat <em>Max Threat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Threat</em>' attribute.
   * @see #getMaxThreat()
   * @generated
   */
  void setMaxThreat(int value);

  /**
   * Returns the value of the '<em><b>Enemy Limits</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.EnemyLimit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enemy Limits</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getDifficultyConfig_EnemyLimits()
   * @model containment="true"
   * @generated
   */
  EList<EnemyLimit> getEnemyLimits();

} // DifficultyConfig
