/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enemy Limit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getType <em>Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getMaxCount <em>Max Count</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getEnemyLimit()
 * @model
 * @generated
 */
public interface EnemyLimit extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link main.game.maze.dsl.mazeDsl.EnemyType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.EnemyType
   * @see #setType(EnemyType)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getEnemyLimit_Type()
   * @model
   * @generated
   */
  EnemyType getType();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.EnemyType
   * @see #getType()
   * @generated
   */
  void setType(EnemyType value);

  /**
   * Returns the value of the '<em><b>Max Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Count</em>' attribute.
   * @see #setMaxCount(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getEnemyLimit_MaxCount()
   * @model
   * @generated
   */
  int getMaxCount();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getMaxCount <em>Max Count</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Count</em>' attribute.
   * @see #getMaxCount()
   * @generated
   */
  void setMaxCount(int value);

} // EnemyLimit


