/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Configuration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getImports <em>Imports</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getDifficulty <em>Difficulty</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getOpponents <em>Opponents</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getPatrols <em>Patrols</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getLootTables <em>Loot Tables</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration()
 * @model
 * @generated
 */
public interface GameConfiguration extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Imports</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.Import}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Imports</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_Imports()
   * @model containment="true"
   * @generated
   */
  EList<Import> getImports();

  /**
   * Returns the value of the '<em><b>Difficulty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Difficulty</em>' containment reference.
   * @see #setDifficulty(DifficultyConfig)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_Difficulty()
   * @model containment="true"
   * @generated
   */
  DifficultyConfig getDifficulty();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getDifficulty <em>Difficulty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Difficulty</em>' containment reference.
   * @see #getDifficulty()
   * @generated
   */
  void setDifficulty(DifficultyConfig value);

  /**
   * Returns the value of the '<em><b>Opponents</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.OpponentConfig}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Opponents</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_Opponents()
   * @model containment="true"
   * @generated
   */
  EList<OpponentConfig> getOpponents();

  /**
   * Returns the value of the '<em><b>Patrols</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.PatrolConfig}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Patrols</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_Patrols()
   * @model containment="true"
   * @generated
   */
  EList<PatrolConfig> getPatrols();

  /**
   * Returns the value of the '<em><b>Loot Tables</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.LootTableConfig}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loot Tables</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getGameConfiguration_LootTables()
   * @model containment="true"
   * @generated
   */
  EList<LootTableConfig> getLootTables();

} // GameConfiguration
