/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Loot Item Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getType <em>Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getValue <em>Value</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getLootItemConfig()
 * @model
 * @generated
 */
public interface LootItemConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getLootItemConfig_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link main.game.maze.dsl.mazeDsl.LootItemTypeEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.LootItemTypeEnum
   * @see #setType(LootItemTypeEnum)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getLootItemConfig_Type()
   * @model
   * @generated
   */
  LootItemTypeEnum getType();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.LootItemTypeEnum
   * @see #getType()
   * @generated
   */
  void setType(LootItemTypeEnum value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getLootItemConfig_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see #setWeight(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getLootItemConfig_Weight()
   * @model
   * @generated
   */
  int getWeight();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see #getWeight()
   * @generated
   */
  void setWeight(int value);

} // LootItemConfig
