/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see main.game.maze.dsl.mazeDsl.MazeDslFactory
 * @model kind="package"
 * @generated
 */
public interface MazeDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mazeDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.main.game.maze/dsl/MazeDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mazeDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazeDslPackage eINSTANCE = main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl.init();

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl <em>Game Configuration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getGameConfiguration()
   * @generated
   */
  int GAME_CONFIGURATION = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__IMPORTS = 1;

  /**
   * The feature id for the '<em><b>Difficulty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__DIFFICULTY = 2;

  /**
   * The feature id for the '<em><b>Opponents</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__OPPONENTS = 3;

  /**
   * The feature id for the '<em><b>Patrols</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__PATROLS = 4;

  /**
   * The feature id for the '<em><b>Loot Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION__LOOT_TABLES = 5;

  /**
   * The number of structural features of the '<em>Game Configuration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_CONFIGURATION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.ImportImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl <em>Difficulty Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getDifficultyConfig()
   * @generated
   */
  int DIFFICULTY_CONFIG = 2;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__LEVEL = 0;

  /**
   * The feature id for the '<em><b>Instant Death</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__INSTANT_DEATH = 1;

  /**
   * The feature id for the '<em><b>Speed Multiplier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__SPEED_MULTIPLIER = 2;

  /**
   * The feature id for the '<em><b>Damage Multiplier</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER = 3;

  /**
   * The feature id for the '<em><b>Max Threat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__MAX_THREAT = 4;

  /**
   * The feature id for the '<em><b>Enemy Limits</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG__ENEMY_LIMITS = 5;

  /**
   * The number of structural features of the '<em>Difficulty Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIFFICULTY_CONFIG_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.EnemyLimitImpl <em>Enemy Limit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.EnemyLimitImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getEnemyLimit()
   * @generated
   */
  int ENEMY_LIMIT = 3;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENEMY_LIMIT__TYPE = 0;

  /**
   * The feature id for the '<em><b>Max Count</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENEMY_LIMIT__MAX_COUNT = 1;

  /**
   * The number of structural features of the '<em>Enemy Limit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENEMY_LIMIT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl <em>Opponent Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getOpponentConfig()
   * @generated
   */
  int OPPONENT_CONFIG = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__TYPE = 1;

  /**
   * The feature id for the '<em><b>Display Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__DISPLAY_NAME = 2;

  /**
   * The feature id for the '<em><b>Health</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__HEALTH = 3;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__SPEED = 4;

  /**
   * The feature id for the '<em><b>Threat Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__THREAT_LEVEL = 5;

  /**
   * The feature id for the '<em><b>Enabled</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__ENABLED = 6;

  /**
   * The feature id for the '<em><b>Behavior</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__BEHAVIOR = 7;

  /**
   * The feature id for the '<em><b>Character Specifics</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__CHARACTER_SPECIFICS = 8;

  /**
   * The feature id for the '<em><b>Patrol Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__PATROL_REF = 9;

  /**
   * The feature id for the '<em><b>Loot Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG__LOOT_REF = 10;

  /**
   * The number of structural features of the '<em>Opponent Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPPONENT_CONFIG_FEATURE_COUNT = 11;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.CharacterSpecificsImpl <em>Character Specifics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.CharacterSpecificsImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getCharacterSpecifics()
   * @generated
   */
  int CHARACTER_SPECIFICS = 5;

  /**
   * The feature id for the '<em><b>Attack Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_SPECIFICS__ATTACK_DAMAGE = 0;

  /**
   * The number of structural features of the '<em>Character Specifics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHARACTER_SPECIFICS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.ZombieSpecificsImpl <em>Zombie Specifics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.ZombieSpecificsImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getZombieSpecifics()
   * @generated
   */
  int ZOMBIE_SPECIFICS = 6;

  /**
   * The feature id for the '<em><b>Attack Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOMBIE_SPECIFICS__ATTACK_DAMAGE = CHARACTER_SPECIFICS__ATTACK_DAMAGE;

  /**
   * The feature id for the '<em><b>Infection Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOMBIE_SPECIFICS__INFECTION_LEVEL = CHARACTER_SPECIFICS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Resurrection Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOMBIE_SPECIFICS__RESURRECTION_TIME = CHARACTER_SPECIFICS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Zombie Specifics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZOMBIE_SPECIFICS_FEATURE_COUNT = CHARACTER_SPECIFICS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.GhostSpecificsImpl <em>Ghost Specifics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.GhostSpecificsImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getGhostSpecifics()
   * @generated
   */
  int GHOST_SPECIFICS = 7;

  /**
   * The feature id for the '<em><b>Attack Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHOST_SPECIFICS__ATTACK_DAMAGE = CHARACTER_SPECIFICS__ATTACK_DAMAGE;

  /**
   * The feature id for the '<em><b>Visibility Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHOST_SPECIFICS__VISIBILITY_LEVEL = CHARACTER_SPECIFICS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Non Tangibility Energy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHOST_SPECIFICS__NON_TANGIBILITY_ENERGY = CHARACTER_SPECIFICS_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ghost Specifics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GHOST_SPECIFICS_FEATURE_COUNT = CHARACTER_SPECIFICS_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl <em>Ranged Specifics</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getRangedSpecifics()
   * @generated
   */
  int RANGED_SPECIFICS = 8;

  /**
   * The feature id for the '<em><b>Attack Damage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__ATTACK_DAMAGE = CHARACTER_SPECIFICS__ATTACK_DAMAGE;

  /**
   * The feature id for the '<em><b>Attack Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__ATTACK_RANGE = CHARACTER_SPECIFICS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attack Cooldown</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__ATTACK_COOLDOWN = CHARACTER_SPECIFICS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Projectile Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__PROJECTILE_SPEED = CHARACTER_SPECIFICS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Projectile Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__PROJECTILE_TYPE = CHARACTER_SPECIFICS_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Splash Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS__SPLASH_RADIUS = CHARACTER_SPECIFICS_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Ranged Specifics</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGED_SPECIFICS_FEATURE_COUNT = CHARACTER_SPECIFICS_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.PatrolConfigImpl <em>Patrol Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.PatrolConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getPatrolConfig()
   * @generated
   */
  int PATROL_CONFIG = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_CONFIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Vision Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_CONFIG__VISION_RANGE = 1;

  /**
   * The feature id for the '<em><b>Zone</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_CONFIG__ZONE = 2;

  /**
   * The feature id for the '<em><b>Waypoints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_CONFIG__WAYPOINTS = 3;

  /**
   * The number of structural features of the '<em>Patrol Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_CONFIG_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.PatrolZoneConfigImpl <em>Patrol Zone Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.PatrolZoneConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getPatrolZoneConfig()
   * @generated
   */
  int PATROL_ZONE_CONFIG = 10;

  /**
   * The feature id for the '<em><b>Top Left X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_ZONE_CONFIG__TOP_LEFT_X = 0;

  /**
   * The feature id for the '<em><b>Top Left Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_ZONE_CONFIG__TOP_LEFT_Y = 1;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_ZONE_CONFIG__WIDTH = 2;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_ZONE_CONFIG__HEIGHT = 3;

  /**
   * The number of structural features of the '<em>Patrol Zone Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATROL_ZONE_CONFIG_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.WaypointImpl <em>Waypoint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.WaypointImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getWaypoint()
   * @generated
   */
  int WAYPOINT = 11;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAYPOINT__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAYPOINT__Y = 1;

  /**
   * The feature id for the '<em><b>Wait Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAYPOINT__WAIT_TIME = 2;

  /**
   * The number of structural features of the '<em>Waypoint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WAYPOINT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.LootTableConfigImpl <em>Loot Table Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.LootTableConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootTableConfig()
   * @generated
   */
  int LOOT_TABLE_CONFIG = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_TABLE_CONFIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_TABLE_CONFIG__CAPACITY = 1;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_TABLE_CONFIG__ITEMS = 2;

  /**
   * The number of structural features of the '<em>Loot Table Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_TABLE_CONFIG_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl <em>Loot Item Config</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootItemConfig()
   * @generated
   */
  int LOOT_ITEM_CONFIG = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_ITEM_CONFIG__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_ITEM_CONFIG__TYPE = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_ITEM_CONFIG__VALUE = 2;

  /**
   * The feature id for the '<em><b>Weight</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_ITEM_CONFIG__WEIGHT = 3;

  /**
   * The number of structural features of the '<em>Loot Item Config</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOT_ITEM_CONFIG_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.DifficultyLevel <em>Difficulty Level</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.DifficultyLevel
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getDifficultyLevel()
   * @generated
   */
  int DIFFICULTY_LEVEL = 14;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.EnemyType <em>Enemy Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.EnemyType
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getEnemyType()
   * @generated
   */
  int ENEMY_TYPE = 15;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.CharacterTypeEnum <em>Character Type Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.CharacterTypeEnum
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getCharacterTypeEnum()
   * @generated
   */
  int CHARACTER_TYPE_ENUM = 16;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.BehaviorTypeEnum <em>Behavior Type Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.BehaviorTypeEnum
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getBehaviorTypeEnum()
   * @generated
   */
  int BEHAVIOR_TYPE_ENUM = 17;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.ProjectileTypeEnum <em>Projectile Type Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.ProjectileTypeEnum
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getProjectileTypeEnum()
   * @generated
   */
  int PROJECTILE_TYPE_ENUM = 18;

  /**
   * The meta object id for the '{@link main.game.maze.dsl.mazeDsl.LootItemTypeEnum <em>Loot Item Type Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.dsl.mazeDsl.LootItemTypeEnum
   * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootItemTypeEnum()
   * @generated
   */
  int LOOT_ITEM_TYPE_ENUM = 19;


  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.GameConfiguration <em>Game Configuration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Configuration</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration
   * @generated
   */
  EClass getGameConfiguration();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getName()
   * @see #getGameConfiguration()
   * @generated
   */
  EAttribute getGameConfiguration_Name();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getImports()
   * @see #getGameConfiguration()
   * @generated
   */
  EReference getGameConfiguration_Imports();

  /**
   * Returns the meta object for the containment reference '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getDifficulty <em>Difficulty</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Difficulty</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getDifficulty()
   * @see #getGameConfiguration()
   * @generated
   */
  EReference getGameConfiguration_Difficulty();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getOpponents <em>Opponents</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Opponents</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getOpponents()
   * @see #getGameConfiguration()
   * @generated
   */
  EReference getGameConfiguration_Opponents();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getPatrols <em>Patrols</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Patrols</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getPatrols()
   * @see #getGameConfiguration()
   * @generated
   */
  EReference getGameConfiguration_Patrols();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.GameConfiguration#getLootTables <em>Loot Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loot Tables</em>'.
   * @see main.game.maze.dsl.mazeDsl.GameConfiguration#getLootTables()
   * @see #getGameConfiguration()
   * @generated
   */
  EReference getGameConfiguration_LootTables();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see main.game.maze.dsl.mazeDsl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see main.game.maze.dsl.mazeDsl.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig <em>Difficulty Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Difficulty Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig
   * @generated
   */
  EClass getDifficultyConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#getLevel()
   * @see #getDifficultyConfig()
   * @generated
   */
  EAttribute getDifficultyConfig_Level();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#isInstantDeath <em>Instant Death</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Instant Death</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#isInstantDeath()
   * @see #getDifficultyConfig()
   * @generated
   */
  EAttribute getDifficultyConfig_InstantDeath();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getSpeedMultiplier <em>Speed Multiplier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed Multiplier</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#getSpeedMultiplier()
   * @see #getDifficultyConfig()
   * @generated
   */
  EAttribute getDifficultyConfig_SpeedMultiplier();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getDamageMultiplier <em>Damage Multiplier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Damage Multiplier</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#getDamageMultiplier()
   * @see #getDifficultyConfig()
   * @generated
   */
  EAttribute getDifficultyConfig_DamageMultiplier();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getMaxThreat <em>Max Threat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Threat</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#getMaxThreat()
   * @see #getDifficultyConfig()
   * @generated
   */
  EAttribute getDifficultyConfig_MaxThreat();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.DifficultyConfig#getEnemyLimits <em>Enemy Limits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Enemy Limits</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyConfig#getEnemyLimits()
   * @see #getDifficultyConfig()
   * @generated
   */
  EReference getDifficultyConfig_EnemyLimits();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.EnemyLimit <em>Enemy Limit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Enemy Limit</em>'.
   * @see main.game.maze.dsl.mazeDsl.EnemyLimit
   * @generated
   */
  EClass getEnemyLimit();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see main.game.maze.dsl.mazeDsl.EnemyLimit#getType()
   * @see #getEnemyLimit()
   * @generated
   */
  EAttribute getEnemyLimit_Type();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.EnemyLimit#getMaxCount <em>Max Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Count</em>'.
   * @see main.game.maze.dsl.mazeDsl.EnemyLimit#getMaxCount()
   * @see #getEnemyLimit()
   * @generated
   */
  EAttribute getEnemyLimit_MaxCount();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.OpponentConfig <em>Opponent Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Opponent Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig
   * @generated
   */
  EClass getOpponentConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getName()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Name();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getType()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Type();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getDisplayName <em>Display Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Display Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getDisplayName()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_DisplayName();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getHealth <em>Health</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Health</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getHealth()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Health();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getSpeed()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Speed();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getThreatLevel <em>Threat Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Threat Level</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getThreatLevel()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_ThreatLevel();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getEnabled <em>Enabled</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Enabled</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getEnabled()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Enabled();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getBehavior <em>Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Behavior</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getBehavior()
   * @see #getOpponentConfig()
   * @generated
   */
  EAttribute getOpponentConfig_Behavior();

  /**
   * Returns the meta object for the containment reference '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getCharacterSpecifics <em>Character Specifics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Character Specifics</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getCharacterSpecifics()
   * @see #getOpponentConfig()
   * @generated
   */
  EReference getOpponentConfig_CharacterSpecifics();

  /**
   * Returns the meta object for the reference '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getPatrolRef <em>Patrol Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Patrol Ref</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getPatrolRef()
   * @see #getOpponentConfig()
   * @generated
   */
  EReference getOpponentConfig_PatrolRef();

  /**
   * Returns the meta object for the reference '{@link main.game.maze.dsl.mazeDsl.OpponentConfig#getLootRef <em>Loot Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Loot Ref</em>'.
   * @see main.game.maze.dsl.mazeDsl.OpponentConfig#getLootRef()
   * @see #getOpponentConfig()
   * @generated
   */
  EReference getOpponentConfig_LootRef();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.CharacterSpecifics <em>Character Specifics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Character Specifics</em>'.
   * @see main.game.maze.dsl.mazeDsl.CharacterSpecifics
   * @generated
   */
  EClass getCharacterSpecifics();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.CharacterSpecifics#getAttackDamage <em>Attack Damage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attack Damage</em>'.
   * @see main.game.maze.dsl.mazeDsl.CharacterSpecifics#getAttackDamage()
   * @see #getCharacterSpecifics()
   * @generated
   */
  EAttribute getCharacterSpecifics_AttackDamage();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.ZombieSpecifics <em>Zombie Specifics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zombie Specifics</em>'.
   * @see main.game.maze.dsl.mazeDsl.ZombieSpecifics
   * @generated
   */
  EClass getZombieSpecifics();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.ZombieSpecifics#getInfectionLevel <em>Infection Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Infection Level</em>'.
   * @see main.game.maze.dsl.mazeDsl.ZombieSpecifics#getInfectionLevel()
   * @see #getZombieSpecifics()
   * @generated
   */
  EAttribute getZombieSpecifics_InfectionLevel();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.ZombieSpecifics#getResurrectionTime <em>Resurrection Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Resurrection Time</em>'.
   * @see main.game.maze.dsl.mazeDsl.ZombieSpecifics#getResurrectionTime()
   * @see #getZombieSpecifics()
   * @generated
   */
  EAttribute getZombieSpecifics_ResurrectionTime();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.GhostSpecifics <em>Ghost Specifics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ghost Specifics</em>'.
   * @see main.game.maze.dsl.mazeDsl.GhostSpecifics
   * @generated
   */
  EClass getGhostSpecifics();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.GhostSpecifics#getVisibilityLevel <em>Visibility Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility Level</em>'.
   * @see main.game.maze.dsl.mazeDsl.GhostSpecifics#getVisibilityLevel()
   * @see #getGhostSpecifics()
   * @generated
   */
  EAttribute getGhostSpecifics_VisibilityLevel();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.GhostSpecifics#getNonTangibilityEnergy <em>Non Tangibility Energy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Non Tangibility Energy</em>'.
   * @see main.game.maze.dsl.mazeDsl.GhostSpecifics#getNonTangibilityEnergy()
   * @see #getGhostSpecifics()
   * @generated
   */
  EAttribute getGhostSpecifics_NonTangibilityEnergy();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics <em>Ranged Specifics</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ranged Specifics</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics
   * @generated
   */
  EClass getRangedSpecifics();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackRange <em>Attack Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attack Range</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackRange()
   * @see #getRangedSpecifics()
   * @generated
   */
  EAttribute getRangedSpecifics_AttackRange();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackCooldown <em>Attack Cooldown</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attack Cooldown</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackCooldown()
   * @see #getRangedSpecifics()
   * @generated
   */
  EAttribute getRangedSpecifics_AttackCooldown();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileSpeed <em>Projectile Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Projectile Speed</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileSpeed()
   * @see #getRangedSpecifics()
   * @generated
   */
  EAttribute getRangedSpecifics_ProjectileSpeed();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileType <em>Projectile Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Projectile Type</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileType()
   * @see #getRangedSpecifics()
   * @generated
   */
  EAttribute getRangedSpecifics_ProjectileType();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getSplashRadius <em>Splash Radius</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Splash Radius</em>'.
   * @see main.game.maze.dsl.mazeDsl.RangedSpecifics#getSplashRadius()
   * @see #getRangedSpecifics()
   * @generated
   */
  EAttribute getRangedSpecifics_SplashRadius();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.PatrolConfig <em>Patrol Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Patrol Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolConfig
   * @generated
   */
  EClass getPatrolConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolConfig#getName()
   * @see #getPatrolConfig()
   * @generated
   */
  EAttribute getPatrolConfig_Name();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getVisionRange <em>Vision Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vision Range</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolConfig#getVisionRange()
   * @see #getPatrolConfig()
   * @generated
   */
  EAttribute getPatrolConfig_VisionRange();

  /**
   * Returns the meta object for the containment reference '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getZone <em>Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Zone</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolConfig#getZone()
   * @see #getPatrolConfig()
   * @generated
   */
  EReference getPatrolConfig_Zone();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getWaypoints <em>Waypoints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Waypoints</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolConfig#getWaypoints()
   * @see #getPatrolConfig()
   * @generated
   */
  EReference getPatrolConfig_Waypoints();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.PatrolZoneConfig <em>Patrol Zone Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Patrol Zone Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolZoneConfig
   * @generated
   */
  EClass getPatrolZoneConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getTopLeftX <em>Top Left X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top Left X</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getTopLeftX()
   * @see #getPatrolZoneConfig()
   * @generated
   */
  EAttribute getPatrolZoneConfig_TopLeftX();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getTopLeftY <em>Top Left Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top Left Y</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getTopLeftY()
   * @see #getPatrolZoneConfig()
   * @generated
   */
  EAttribute getPatrolZoneConfig_TopLeftY();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getWidth()
   * @see #getPatrolZoneConfig()
   * @generated
   */
  EAttribute getPatrolZoneConfig_Width();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see main.game.maze.dsl.mazeDsl.PatrolZoneConfig#getHeight()
   * @see #getPatrolZoneConfig()
   * @generated
   */
  EAttribute getPatrolZoneConfig_Height();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.Waypoint <em>Waypoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Waypoint</em>'.
   * @see main.game.maze.dsl.mazeDsl.Waypoint
   * @generated
   */
  EClass getWaypoint();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.Waypoint#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see main.game.maze.dsl.mazeDsl.Waypoint#getX()
   * @see #getWaypoint()
   * @generated
   */
  EAttribute getWaypoint_X();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.Waypoint#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see main.game.maze.dsl.mazeDsl.Waypoint#getY()
   * @see #getWaypoint()
   * @generated
   */
  EAttribute getWaypoint_Y();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.Waypoint#getWaitTime <em>Wait Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Wait Time</em>'.
   * @see main.game.maze.dsl.mazeDsl.Waypoint#getWaitTime()
   * @see #getWaypoint()
   * @generated
   */
  EAttribute getWaypoint_WaitTime();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.LootTableConfig <em>Loot Table Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loot Table Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootTableConfig
   * @generated
   */
  EClass getLootTableConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootTableConfig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootTableConfig#getName()
   * @see #getLootTableConfig()
   * @generated
   */
  EAttribute getLootTableConfig_Name();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootTableConfig#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootTableConfig#getCapacity()
   * @see #getLootTableConfig()
   * @generated
   */
  EAttribute getLootTableConfig_Capacity();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.dsl.mazeDsl.LootTableConfig#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootTableConfig#getItems()
   * @see #getLootTableConfig()
   * @generated
   */
  EReference getLootTableConfig_Items();

  /**
   * Returns the meta object for class '{@link main.game.maze.dsl.mazeDsl.LootItemConfig <em>Loot Item Config</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loot Item Config</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemConfig
   * @generated
   */
  EClass getLootItemConfig();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemConfig#getName()
   * @see #getLootItemConfig()
   * @generated
   */
  EAttribute getLootItemConfig_Name();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemConfig#getType()
   * @see #getLootItemConfig()
   * @generated
   */
  EAttribute getLootItemConfig_Type();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemConfig#getValue()
   * @see #getLootItemConfig()
   * @generated
   */
  EAttribute getLootItemConfig_Value();

  /**
   * Returns the meta object for the attribute '{@link main.game.maze.dsl.mazeDsl.LootItemConfig#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Weight</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemConfig#getWeight()
   * @see #getLootItemConfig()
   * @generated
   */
  EAttribute getLootItemConfig_Weight();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.DifficultyLevel <em>Difficulty Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Difficulty Level</em>'.
   * @see main.game.maze.dsl.mazeDsl.DifficultyLevel
   * @generated
   */
  EEnum getDifficultyLevel();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.EnemyType <em>Enemy Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Enemy Type</em>'.
   * @see main.game.maze.dsl.mazeDsl.EnemyType
   * @generated
   */
  EEnum getEnemyType();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.CharacterTypeEnum <em>Character Type Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Character Type Enum</em>'.
   * @see main.game.maze.dsl.mazeDsl.CharacterTypeEnum
   * @generated
   */
  EEnum getCharacterTypeEnum();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.BehaviorTypeEnum <em>Behavior Type Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Behavior Type Enum</em>'.
   * @see main.game.maze.dsl.mazeDsl.BehaviorTypeEnum
   * @generated
   */
  EEnum getBehaviorTypeEnum();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.ProjectileTypeEnum <em>Projectile Type Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Projectile Type Enum</em>'.
   * @see main.game.maze.dsl.mazeDsl.ProjectileTypeEnum
   * @generated
   */
  EEnum getProjectileTypeEnum();

  /**
   * Returns the meta object for enum '{@link main.game.maze.dsl.mazeDsl.LootItemTypeEnum <em>Loot Item Type Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Loot Item Type Enum</em>'.
   * @see main.game.maze.dsl.mazeDsl.LootItemTypeEnum
   * @generated
   */
  EEnum getLootItemTypeEnum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MazeDslFactory getMazeDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl <em>Game Configuration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getGameConfiguration()
     * @generated
     */
    EClass GAME_CONFIGURATION = eINSTANCE.getGameConfiguration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_CONFIGURATION__NAME = eINSTANCE.getGameConfiguration_Name();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_CONFIGURATION__IMPORTS = eINSTANCE.getGameConfiguration_Imports();

    /**
     * The meta object literal for the '<em><b>Difficulty</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_CONFIGURATION__DIFFICULTY = eINSTANCE.getGameConfiguration_Difficulty();

    /**
     * The meta object literal for the '<em><b>Opponents</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_CONFIGURATION__OPPONENTS = eINSTANCE.getGameConfiguration_Opponents();

    /**
     * The meta object literal for the '<em><b>Patrols</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_CONFIGURATION__PATROLS = eINSTANCE.getGameConfiguration_Patrols();

    /**
     * The meta object literal for the '<em><b>Loot Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_CONFIGURATION__LOOT_TABLES = eINSTANCE.getGameConfiguration_LootTables();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.ImportImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl <em>Difficulty Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getDifficultyConfig()
     * @generated
     */
    EClass DIFFICULTY_CONFIG = eINSTANCE.getDifficultyConfig();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONFIG__LEVEL = eINSTANCE.getDifficultyConfig_Level();

    /**
     * The meta object literal for the '<em><b>Instant Death</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONFIG__INSTANT_DEATH = eINSTANCE.getDifficultyConfig_InstantDeath();

    /**
     * The meta object literal for the '<em><b>Speed Multiplier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONFIG__SPEED_MULTIPLIER = eINSTANCE.getDifficultyConfig_SpeedMultiplier();

    /**
     * The meta object literal for the '<em><b>Damage Multiplier</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER = eINSTANCE.getDifficultyConfig_DamageMultiplier();

    /**
     * The meta object literal for the '<em><b>Max Threat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIFFICULTY_CONFIG__MAX_THREAT = eINSTANCE.getDifficultyConfig_MaxThreat();

    /**
     * The meta object literal for the '<em><b>Enemy Limits</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIFFICULTY_CONFIG__ENEMY_LIMITS = eINSTANCE.getDifficultyConfig_EnemyLimits();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.EnemyLimitImpl <em>Enemy Limit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.EnemyLimitImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getEnemyLimit()
     * @generated
     */
    EClass ENEMY_LIMIT = eINSTANCE.getEnemyLimit();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENEMY_LIMIT__TYPE = eINSTANCE.getEnemyLimit_Type();

    /**
     * The meta object literal for the '<em><b>Max Count</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENEMY_LIMIT__MAX_COUNT = eINSTANCE.getEnemyLimit_MaxCount();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl <em>Opponent Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getOpponentConfig()
     * @generated
     */
    EClass OPPONENT_CONFIG = eINSTANCE.getOpponentConfig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__NAME = eINSTANCE.getOpponentConfig_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__TYPE = eINSTANCE.getOpponentConfig_Type();

    /**
     * The meta object literal for the '<em><b>Display Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__DISPLAY_NAME = eINSTANCE.getOpponentConfig_DisplayName();

    /**
     * The meta object literal for the '<em><b>Health</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__HEALTH = eINSTANCE.getOpponentConfig_Health();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__SPEED = eINSTANCE.getOpponentConfig_Speed();

    /**
     * The meta object literal for the '<em><b>Threat Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__THREAT_LEVEL = eINSTANCE.getOpponentConfig_ThreatLevel();

    /**
     * The meta object literal for the '<em><b>Enabled</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__ENABLED = eINSTANCE.getOpponentConfig_Enabled();

    /**
     * The meta object literal for the '<em><b>Behavior</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPPONENT_CONFIG__BEHAVIOR = eINSTANCE.getOpponentConfig_Behavior();

    /**
     * The meta object literal for the '<em><b>Character Specifics</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPPONENT_CONFIG__CHARACTER_SPECIFICS = eINSTANCE.getOpponentConfig_CharacterSpecifics();

    /**
     * The meta object literal for the '<em><b>Patrol Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPPONENT_CONFIG__PATROL_REF = eINSTANCE.getOpponentConfig_PatrolRef();

    /**
     * The meta object literal for the '<em><b>Loot Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPPONENT_CONFIG__LOOT_REF = eINSTANCE.getOpponentConfig_LootRef();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.CharacterSpecificsImpl <em>Character Specifics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.CharacterSpecificsImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getCharacterSpecifics()
     * @generated
     */
    EClass CHARACTER_SPECIFICS = eINSTANCE.getCharacterSpecifics();

    /**
     * The meta object literal for the '<em><b>Attack Damage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHARACTER_SPECIFICS__ATTACK_DAMAGE = eINSTANCE.getCharacterSpecifics_AttackDamage();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.ZombieSpecificsImpl <em>Zombie Specifics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.ZombieSpecificsImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getZombieSpecifics()
     * @generated
     */
    EClass ZOMBIE_SPECIFICS = eINSTANCE.getZombieSpecifics();

    /**
     * The meta object literal for the '<em><b>Infection Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZOMBIE_SPECIFICS__INFECTION_LEVEL = eINSTANCE.getZombieSpecifics_InfectionLevel();

    /**
     * The meta object literal for the '<em><b>Resurrection Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZOMBIE_SPECIFICS__RESURRECTION_TIME = eINSTANCE.getZombieSpecifics_ResurrectionTime();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.GhostSpecificsImpl <em>Ghost Specifics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.GhostSpecificsImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getGhostSpecifics()
     * @generated
     */
    EClass GHOST_SPECIFICS = eINSTANCE.getGhostSpecifics();

    /**
     * The meta object literal for the '<em><b>Visibility Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GHOST_SPECIFICS__VISIBILITY_LEVEL = eINSTANCE.getGhostSpecifics_VisibilityLevel();

    /**
     * The meta object literal for the '<em><b>Non Tangibility Energy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GHOST_SPECIFICS__NON_TANGIBILITY_ENERGY = eINSTANCE.getGhostSpecifics_NonTangibilityEnergy();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl <em>Ranged Specifics</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getRangedSpecifics()
     * @generated
     */
    EClass RANGED_SPECIFICS = eINSTANCE.getRangedSpecifics();

    /**
     * The meta object literal for the '<em><b>Attack Range</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGED_SPECIFICS__ATTACK_RANGE = eINSTANCE.getRangedSpecifics_AttackRange();

    /**
     * The meta object literal for the '<em><b>Attack Cooldown</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGED_SPECIFICS__ATTACK_COOLDOWN = eINSTANCE.getRangedSpecifics_AttackCooldown();

    /**
     * The meta object literal for the '<em><b>Projectile Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGED_SPECIFICS__PROJECTILE_SPEED = eINSTANCE.getRangedSpecifics_ProjectileSpeed();

    /**
     * The meta object literal for the '<em><b>Projectile Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGED_SPECIFICS__PROJECTILE_TYPE = eINSTANCE.getRangedSpecifics_ProjectileType();

    /**
     * The meta object literal for the '<em><b>Splash Radius</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RANGED_SPECIFICS__SPLASH_RADIUS = eINSTANCE.getRangedSpecifics_SplashRadius();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.PatrolConfigImpl <em>Patrol Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.PatrolConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getPatrolConfig()
     * @generated
     */
    EClass PATROL_CONFIG = eINSTANCE.getPatrolConfig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_CONFIG__NAME = eINSTANCE.getPatrolConfig_Name();

    /**
     * The meta object literal for the '<em><b>Vision Range</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_CONFIG__VISION_RANGE = eINSTANCE.getPatrolConfig_VisionRange();

    /**
     * The meta object literal for the '<em><b>Zone</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATROL_CONFIG__ZONE = eINSTANCE.getPatrolConfig_Zone();

    /**
     * The meta object literal for the '<em><b>Waypoints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATROL_CONFIG__WAYPOINTS = eINSTANCE.getPatrolConfig_Waypoints();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.PatrolZoneConfigImpl <em>Patrol Zone Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.PatrolZoneConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getPatrolZoneConfig()
     * @generated
     */
    EClass PATROL_ZONE_CONFIG = eINSTANCE.getPatrolZoneConfig();

    /**
     * The meta object literal for the '<em><b>Top Left X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_ZONE_CONFIG__TOP_LEFT_X = eINSTANCE.getPatrolZoneConfig_TopLeftX();

    /**
     * The meta object literal for the '<em><b>Top Left Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_ZONE_CONFIG__TOP_LEFT_Y = eINSTANCE.getPatrolZoneConfig_TopLeftY();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_ZONE_CONFIG__WIDTH = eINSTANCE.getPatrolZoneConfig_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATROL_ZONE_CONFIG__HEIGHT = eINSTANCE.getPatrolZoneConfig_Height();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.WaypointImpl <em>Waypoint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.WaypointImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getWaypoint()
     * @generated
     */
    EClass WAYPOINT = eINSTANCE.getWaypoint();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAYPOINT__X = eINSTANCE.getWaypoint_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAYPOINT__Y = eINSTANCE.getWaypoint_Y();

    /**
     * The meta object literal for the '<em><b>Wait Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WAYPOINT__WAIT_TIME = eINSTANCE.getWaypoint_WaitTime();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.LootTableConfigImpl <em>Loot Table Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.LootTableConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootTableConfig()
     * @generated
     */
    EClass LOOT_TABLE_CONFIG = eINSTANCE.getLootTableConfig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_TABLE_CONFIG__NAME = eINSTANCE.getLootTableConfig_Name();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_TABLE_CONFIG__CAPACITY = eINSTANCE.getLootTableConfig_Capacity();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOT_TABLE_CONFIG__ITEMS = eINSTANCE.getLootTableConfig_Items();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl <em>Loot Item Config</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootItemConfig()
     * @generated
     */
    EClass LOOT_ITEM_CONFIG = eINSTANCE.getLootItemConfig();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_ITEM_CONFIG__NAME = eINSTANCE.getLootItemConfig_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_ITEM_CONFIG__TYPE = eINSTANCE.getLootItemConfig_Type();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_ITEM_CONFIG__VALUE = eINSTANCE.getLootItemConfig_Value();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOOT_ITEM_CONFIG__WEIGHT = eINSTANCE.getLootItemConfig_Weight();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.DifficultyLevel <em>Difficulty Level</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.DifficultyLevel
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getDifficultyLevel()
     * @generated
     */
    EEnum DIFFICULTY_LEVEL = eINSTANCE.getDifficultyLevel();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.EnemyType <em>Enemy Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.EnemyType
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getEnemyType()
     * @generated
     */
    EEnum ENEMY_TYPE = eINSTANCE.getEnemyType();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.CharacterTypeEnum <em>Character Type Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.CharacterTypeEnum
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getCharacterTypeEnum()
     * @generated
     */
    EEnum CHARACTER_TYPE_ENUM = eINSTANCE.getCharacterTypeEnum();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.BehaviorTypeEnum <em>Behavior Type Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.BehaviorTypeEnum
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getBehaviorTypeEnum()
     * @generated
     */
    EEnum BEHAVIOR_TYPE_ENUM = eINSTANCE.getBehaviorTypeEnum();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.ProjectileTypeEnum <em>Projectile Type Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.ProjectileTypeEnum
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getProjectileTypeEnum()
     * @generated
     */
    EEnum PROJECTILE_TYPE_ENUM = eINSTANCE.getProjectileTypeEnum();

    /**
     * The meta object literal for the '{@link main.game.maze.dsl.mazeDsl.LootItemTypeEnum <em>Loot Item Type Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.dsl.mazeDsl.LootItemTypeEnum
     * @see main.game.maze.dsl.mazeDsl.impl.MazeDslPackageImpl#getLootItemTypeEnum()
     * @generated
     */
    EEnum LOOT_ITEM_TYPE_ENUM = eINSTANCE.getLootItemTypeEnum();

  }

} //MazeDslPackage
