/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage
 * @generated
 */
public interface MazeDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazeDslFactory eINSTANCE = main.game.maze.dsl.mazeDsl.impl.MazeDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Game Configuration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game Configuration</em>'.
   * @generated
   */
  GameConfiguration createGameConfiguration();

  /**
   * Returns a new object of class '<em>Import</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Import</em>'.
   * @generated
   */
  Import createImport();

  /**
   * Returns a new object of class '<em>Difficulty Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Difficulty Config</em>'.
   * @generated
   */
  DifficultyConfig createDifficultyConfig();

  /**
   * Returns a new object of class '<em>Enemy Limit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Enemy Limit</em>'.
   * @generated
   */
  EnemyLimit createEnemyLimit();

  /**
   * Returns a new object of class '<em>Opponent Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Opponent Config</em>'.
   * @generated
   */
  OpponentConfig createOpponentConfig();

  /**
   * Returns a new object of class '<em>Character Specifics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Character Specifics</em>'.
   * @generated
   */
  CharacterSpecifics createCharacterSpecifics();

  /**
   * Returns a new object of class '<em>Zombie Specifics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Zombie Specifics</em>'.
   * @generated
   */
  ZombieSpecifics createZombieSpecifics();

  /**
   * Returns a new object of class '<em>Ghost Specifics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ghost Specifics</em>'.
   * @generated
   */
  GhostSpecifics createGhostSpecifics();

  /**
   * Returns a new object of class '<em>Ranged Specifics</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ranged Specifics</em>'.
   * @generated
   */
  RangedSpecifics createRangedSpecifics();

  /**
   * Returns a new object of class '<em>Patrol Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Patrol Config</em>'.
   * @generated
   */
  PatrolConfig createPatrolConfig();

  /**
   * Returns a new object of class '<em>Patrol Zone Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Patrol Zone Config</em>'.
   * @generated
   */
  PatrolZoneConfig createPatrolZoneConfig();

  /**
   * Returns a new object of class '<em>Waypoint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Waypoint</em>'.
   * @generated
   */
  Waypoint createWaypoint();

  /**
   * Returns a new object of class '<em>Loot Table Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Table Config</em>'.
   * @generated
   */
  LootTableConfig createLootTableConfig();

  /**
   * Returns a new object of class '<em>Loot Item Config</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Loot Item Config</em>'.
   * @generated
   */
  LootItemConfig createLootItemConfig();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MazeDslPackage getMazeDslPackage();

} //MazeDslFactory
