/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Patrol Config</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getVisionRange <em>Vision Range</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getZone <em>Zone</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getWaypoints <em>Waypoints</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getPatrolConfig()
 * @model
 * @generated
 */
public interface PatrolConfig extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getPatrolConfig_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Vision Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vision Range</em>' attribute.
   * @see #setVisionRange(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getPatrolConfig_VisionRange()
   * @model
   * @generated
   */
  double getVisionRange();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getVisionRange <em>Vision Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vision Range</em>' attribute.
   * @see #getVisionRange()
   * @generated
   */
  void setVisionRange(double value);

  /**
   * Returns the value of the '<em><b>Zone</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zone</em>' containment reference.
   * @see #setZone(PatrolZoneConfig)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getPatrolConfig_Zone()
   * @model containment="true"
   * @generated
   */
  PatrolZoneConfig getZone();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.PatrolConfig#getZone <em>Zone</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zone</em>' containment reference.
   * @see #getZone()
   * @generated
   */
  void setZone(PatrolZoneConfig value);

  /**
   * Returns the value of the '<em><b>Waypoints</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.dsl.mazeDsl.Waypoint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Waypoints</em>' containment reference list.
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getPatrolConfig_Waypoints()
   * @model containment="true"
   * @generated
   */
  EList<Waypoint> getWaypoints();

} // PatrolConfig
