/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ranged Specifics</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackRange <em>Attack Range</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackCooldown <em>Attack Cooldown</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileSpeed <em>Projectile Speed</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileType <em>Projectile Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getSplashRadius <em>Splash Radius</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics()
 * @model
 * @generated
 */
public interface RangedSpecifics extends CharacterSpecifics
{
  /**
   * Returns the value of the '<em><b>Attack Range</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attack Range</em>' attribute.
   * @see #setAttackRange(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics_AttackRange()
   * @model
   * @generated
   */
  double getAttackRange();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackRange <em>Attack Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attack Range</em>' attribute.
   * @see #getAttackRange()
   * @generated
   */
  void setAttackRange(double value);

  /**
   * Returns the value of the '<em><b>Attack Cooldown</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attack Cooldown</em>' attribute.
   * @see #setAttackCooldown(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics_AttackCooldown()
   * @model
   * @generated
   */
  int getAttackCooldown();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getAttackCooldown <em>Attack Cooldown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attack Cooldown</em>' attribute.
   * @see #getAttackCooldown()
   * @generated
   */
  void setAttackCooldown(int value);

  /**
   * Returns the value of the '<em><b>Projectile Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projectile Speed</em>' attribute.
   * @see #setProjectileSpeed(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics_ProjectileSpeed()
   * @model
   * @generated
   */
  double getProjectileSpeed();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileSpeed <em>Projectile Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projectile Speed</em>' attribute.
   * @see #getProjectileSpeed()
   * @generated
   */
  void setProjectileSpeed(double value);

  /**
   * Returns the value of the '<em><b>Projectile Type</b></em>' attribute.
   * The literals are from the enumeration {@link main.game.maze.dsl.mazeDsl.ProjectileTypeEnum}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Projectile Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.ProjectileTypeEnum
   * @see #setProjectileType(ProjectileTypeEnum)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics_ProjectileType()
   * @model
   * @generated
   */
  ProjectileTypeEnum getProjectileType();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getProjectileType <em>Projectile Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Projectile Type</em>' attribute.
   * @see main.game.maze.dsl.mazeDsl.ProjectileTypeEnum
   * @see #getProjectileType()
   * @generated
   */
  void setProjectileType(ProjectileTypeEnum value);

  /**
   * Returns the value of the '<em><b>Splash Radius</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Splash Radius</em>' attribute.
   * @see #setSplashRadius(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getRangedSpecifics_SplashRadius()
   * @model
   * @generated
   */
  double getSplashRadius();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.RangedSpecifics#getSplashRadius <em>Splash Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Splash Radius</em>' attribute.
   * @see #getSplashRadius()
   * @generated
   */
  void setSplashRadius(double value);

} // RangedSpecifics
