/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Waypoint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.Waypoint#getX <em>X</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.Waypoint#getY <em>Y</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.Waypoint#getWaitTime <em>Wait Time</em>}</li>
 * </ul>
 *
 * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getWaypoint()
 * @model
 * @generated
 */
public interface Waypoint extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getWaypoint_X()
   * @model
   * @generated
   */
  double getX();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.Waypoint#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(double value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(double)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getWaypoint_Y()
   * @model
   * @generated
   */
  double getY();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.Waypoint#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(double value);

  /**
   * Returns the value of the '<em><b>Wait Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wait Time</em>' attribute.
   * @see #setWaitTime(int)
   * @see main.game.maze.dsl.mazeDsl.MazeDslPackage#getWaypoint_WaitTime()
   * @model
   * @generated
   */
  int getWaitTime();

  /**
   * Sets the value of the '{@link main.game.maze.dsl.mazeDsl.Waypoint#getWaitTime <em>Wait Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wait Time</em>' attribute.
   * @see #getWaitTime()
   * @generated
   */
  void setWaitTime(int value);

} // Waypoint


