<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviour" nsURI="http://main.game.maze/behaviour" nsPrefix="behaviour">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="main.game.maze"/>
    <details key="resource" value="XMI"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="opp" value="../../../../../opponents-module/src/main/resources/opponents.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Direction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPosition" lowerBound="1"
        eType="#//Position"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endPosition" lowerBound="1"
        eType="#//Position"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositivePositions"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositivePositions" value="self.posX >= 0 and self.posY >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posX" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posY" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovementBehavior" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The MovementBehavior contains the positions of the character in the maze and methods to update the position."/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositiveMovementSpeed ValidVisionRange"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositiveMovementSpeed" value="self.movementSpeed > 0"/>
      <details key="ValidVisionRange" value="self.visionRange > 0 and&#xA;&#x9;&#x9;&#x9;if self.charactertype->any(true).oclIsKindOf(opp::RangedEnemy) then&#xA;&#x9;&#x9;&#x9; &#x9;let rangedCharacter : opp::RangedEnemy = self.charactertype->any(true).oclAsType(opp::RangedEnemy)&#xA;&#x9;&#x9;&#x9;    in rangedCharacter.attackRange &lt;= self.visionRange&#xA;&#x9;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;&#x9;true&#xA;&#x9;&#x9;&#x9;endif"/>
    </eAnnotations>
    <eOperations name="move"/>
    <eOperations name="update">
      <eParameters name="healthEvent" lowerBound="1" eType="#//HealthEvent"/>
    </eOperations>
    <eOperations name="update">
      <eParameters name="speedEvent" lowerBound="1" eType="#//SpeedEvent"/>
    </eOperations>
    <eOperations name="update">
      <eParameters name="timeEvent" lowerBound="1" eType="#//TimeEvent"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charactertype" lowerBound="1"
        eType="ecore:EClass ../../../../../opponents-module/src/main/resources/opponents.ecore#//CharacterType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Character on which those movements should apply."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreWalls" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates if the movements should ignore walls."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="&#xA;&#x9;&#x9;&#x9;&#x9;if self.charactertype->any(true).oclIsKindOf(opp::Ghost) then&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;let ghostCharacter : opp::Ghost = self.charactertype->any(true).oclAsType(opp::Ghost)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;in ghostCharacter.nonTangibilityEnergy >= 0&#xA;&#x9;&#x9;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;false&#xA;&#x9;&#x9;&#x9;&#x9;endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instantKillOnCollision"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates if the player should be killed when it collides this character."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.charactertype->any(true).threatLevel > 100"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="movementSpeed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Attributes derived from character speed"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.charactertype->any(true).speed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseVisionRange" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalVisionRange"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visionRangeMultiplier"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visionRange" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the distance the enemy can see the player."/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="self.baseVisionRange * self.visionRangeMultiplier + self.additionalVisionRange"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextPositions" upperBound="-1"
        eType="#//Position">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For dynamic purpose. Stores the list of points to the next step. Should be frequently updated."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For dynamic purpose. Stores the current position of the enemy."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="direction" eType="#//Direction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="For dynamic purpose. Stores the current direction of the enemy."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomBehavior" eSuperTypes="#//MovementBehavior">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositiveRegenPerSecond"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositiveRegenPerSecond" value="self.regenPerSecond >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="regenPerSecond" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Amount of HP when regained per second."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatrolBehavior" eSuperTypes="#//MovementBehavior">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="RequiresOnePatrolPoint ValidStardIndex ValidPatrolZone"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="RequiresOnePatrolPoint" value="self.path->size() > 0"/>
      <details key="ValidStardIndex" value="self.currentIndex >= 0 and self.currentIndex &lt; self.path->size()"/>
      <details key="ValidPatrolZone" value="self.patrolZone->size() = 0 or&#xA;&#x9;&#x9;&#x9;let width : ecore::EDouble = self.patrolZone->collect(z | z.width)->any(true),&#xA;&#x9;&#x9;&#x9;    height : ecore::EDouble = self.patrolZone->collect(z | z.height)->any(true),&#xA;&#x9;&#x9;&#x9;    topLeft : Position = self.patrolZone->collect(z | z.topLeft)->any(true)&#xA;&#x9;&#x9;&#x9;in self.path->forAll(pp | pp.point->any(p | &#xA;&#x9;&#x9;&#x9;&#x9;p.posX >= topLeft.posX and&#xA;&#x9;&#x9;&#x9;&#x9;p.posY >= topLeft.posY and&#xA;&#x9;&#x9;&#x9;&#x9;p.posX &lt;= topLeft.posX + width and&#xA;&#x9;&#x9;&#x9;&#x9;p.posY &lt;= topLeft.posY + height&#xA;&#x9;&#x9;))"/>
    </eAnnotations>
    <eOperations name="nextIndex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" upperBound="-1"
        eType="#//PatrolPoint" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of patrol steps. If only one is present, the character should stay at this step and not move at all."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The index in the path describing the point the character should start at"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathcalculator" lowerBound="1"
        eType="#//PathCalculator" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The calculator used to compute movements to the next point"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" eType="#//PatrolPathBehavior">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="How to handle the path list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patrolZone" eType="#//PatrolZone">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of 1 or 0 patrol zone. It is optional"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChaseBehavior" eSuperTypes="#//MovementBehavior">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NotTooLargeAttackRadius"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="NotTooLargeAttackRadius" value="self.charactertype->select(p | p.oclIsKindOf(opp::RangedEnemy))->isEmpty() or&#xA;&#x9;&#x9;&#x9;let rangedEnemy : opp::RangedEnemy = self.charactertype->any(true).oclAsType(opp::RangedEnemy),&#xA;&#x9;&#x9;&#x9;&#x9;relativeTarget : Position = self.relativePositionTarget->any(true)&#xA;&#x9;&#x9;&#x9;in rangedEnemy.attackRange >= relativeTarget.posX and rangedEnemy.attackRange >= relativeTarget.posY"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relativePositionTarget"
        lowerBound="1" eType="#//Position" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Position relative to the player to chase.&#xA;If set to Position{posX=x,posY=y}, then the character will target the target is Position(Player.x+x, Player.y+y). "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathcalculator" lowerBound="1"
        eType="#//PathCalculator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatrolPoint">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a patrol step&#xA;"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositivePatrolPointCoords ValidHealthEventsProbability ValidSpeedEventsProbability ValidTimeEventsProbability ValidVisionEventsProbability ValidAttackEventsProbability"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositivePatrolPointCoords" value="self.point->forAll(p | p.posX > 0 and p.posY > 0)"/>
      <details key="ValidHealthEventsProbability" value="self.events->select(p | p.oclIsKindOf(HealthEvent))->collect(p | p.probability)->sum() &lt;= 100"/>
      <details key="ValidSpeedEventsProbability" value="self.events->select(p | p.oclIsKindOf(SpeedEvent))->collect(p | p.probability)->sum() &lt;= 100"/>
      <details key="ValidTimeEventsProbability" value="self.events->select(p | p.oclIsKindOf(TimeEvent))->collect(p | p.probability)->sum() &lt;= 100"/>
      <details key="ValidVisionEventsProbability" value="self.events->select(p | p.oclIsKindOf(VisionEvent))->collect(p | p.probability)->sum() &lt;= 100"/>
      <details key="ValidAttackEventsProbability" value="self.events->select(p | p.oclIsKindOf(AttackEvent))->collect(p | p.probability)->sum() &lt;= 100"/>
    </eAnnotations>
    <eOperations name="triggerEvents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="point" lowerBound="1" eType="#//Position"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Coordinates of the patrol step"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" ordered="false"
        upperBound="-1" eType="#//CharacterEvent" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of events that can occur when the enemy reaches this point."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatrolZone">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="topLeft" lowerBound="1"
        eType="#//Position">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Top left corner of the rectangular patrol zone"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PathCalculator" abstract="true">
    <eOperations name="compute" lowerBound="1" upperBound="-1" eType="#//Position">
      <eParameters name="target" eType="#//Position"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distanceMethod" lowerBound="1"
        eType="#//DistanceMethod">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Method used to compute when the path calculator did not hit the target, or as heuristic method for A* algorithm."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DijkstraPathCalculator" eSuperTypes="#//PathCalculator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidDijsktraPath"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidDijsktraPath" value="self.maxPathLength > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPathLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When computing the Dijkstra algorithm, a maximum of maxIterations iterations are performed. If the character has not been found, the character will take the direction of the nearest of the last iterations points."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AstarPathCalculator" eSuperTypes="#//PathCalculator">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidAStartPath"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidAStartPath" value="self.maxPathLength > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPathLength" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When computing the A* algorithm, a maximum of maxIterations iterations are performed. If the character has not been found, the character will take the direction of the nearest of the last iterations points."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalPathCalculator" eSuperTypes="#//PathCalculator"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DistanceMethod">
    <eLiterals name="MANHATTAN"/>
    <eLiterals name="EUCLIDEAN" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PatrolPathBehavior">
    <eLiterals name="LOOP"/>
    <eLiterals name="BACKWARD" value="1"/>
    <eLiterals name="RANDOM" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterEvent" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidProbability"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidProbability" value="self.probability >= 0 and self.probability &lt;= 100"/>
    </eAnnotations>
    <eOperations name="notify"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Probability in percentage of this event to happen."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscriber" lowerBound="1"
        eType="#//MovementBehavior">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set of movement behaviors to notify when this event is triggered."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HealthEvent" eSuperTypes="#//CharacterEvent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositiveHealthAmount ValidHealthPercentage"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositiveHealthAmount" value="self.healthAmount >= 0"/>
      <details key="ValidHealthPercentage" value="self.healthPercentage >= 0 and self.healthPercentage &lt;= 100"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="healthAmount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="healthPercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpeedEvent" eSuperTypes="#//CharacterEvent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ValidSpeedPercentage"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="ValidSpeedPercentage" value="self.speedPercentage >= -100 and self.speedPercentage &lt;= 100"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speedAmount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speedPercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent" eSuperTypes="#//CharacterEvent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PositivePatrolTime"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="PositivePatrolTime" value="self.time >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisionEvent" eSuperTypes="#//CharacterEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusAmount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusPercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttackEvent" eSuperTypes="#//CharacterEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusPercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radiusAmount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damageAmount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="damagePercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
