/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.mazecomp;

import main.game.maze.opponents.Ghost;
import main.game.maze.opponents.LootItem;
import main.game.maze.opponents.LootTable;
import main.game.maze.opponents.PumpkinBomber;
import main.game.maze.opponents.Zombie;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Maze File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.mazecomp.MazeFile#getZombies <em>Zombies</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.MazeFile#getGhosts <em>Ghosts</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.MazeFile#getPumpkinBombers <em>Pumpkin Bombers</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.MazeFile#getLootTables <em>Loot Tables</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.MazeFile#getLootItems <em>Loot Items</em>}</li>
 * </ul>
 *
 * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile()
 * @model
 * @generated
 */
public interface MazeFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Zombies</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.opponents.Zombie}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zombies</em>' containment reference list.
   * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile_Zombies()
   * @model containment="true"
   * @generated
   */
  EList<Zombie> getZombies();

  /**
   * Returns the value of the '<em><b>Ghosts</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.opponents.Ghost}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ghosts</em>' containment reference list.
   * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile_Ghosts()
   * @model containment="true"
   * @generated
   */
  EList<Ghost> getGhosts();

  /**
   * Returns the value of the '<em><b>Pumpkin Bombers</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.opponents.PumpkinBomber}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pumpkin Bombers</em>' containment reference list.
   * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile_PumpkinBombers()
   * @model containment="true"
   * @generated
   */
  EList<PumpkinBomber> getPumpkinBombers();

  /**
   * Returns the value of the '<em><b>Loot Tables</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.opponents.LootTable}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loot Tables</em>' containment reference list.
   * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile_LootTables()
   * @model containment="true"
   * @generated
   */
  EList<LootTable> getLootTables();

  /**
   * Returns the value of the '<em><b>Loot Items</b></em>' containment reference list.
   * The list contents are of type {@link main.game.maze.opponents.LootItem}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loot Items</em>' containment reference list.
   * @see main.game.maze.mazecomp.MazecompPackage#getMazeFile_LootItems()
   * @model containment="true"
   * @generated
   */
  EList<LootItem> getLootItems();

} // MazeFile
