/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.mazecomp;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see main.game.maze.mazecomp.MazecompPackage
 * @generated
 */
public interface MazecompFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazecompFactory eINSTANCE = main.game.maze.mazecomp.impl.MazecompFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Maze File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Maze File</em>'.
   * @generated
   */
  MazeFile createMazeFile();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MazecompPackage getMazecompPackage();

} //MazecompFactory
