/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.mazecomp;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see main.game.maze.mazecomp.MazecompFactory
 * @model kind="package"
 * @generated
 */
public interface MazecompPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mazecomp";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://main.game.maze/mazecomp";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mazecomp";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MazecompPackage eINSTANCE = main.game.maze.mazecomp.impl.MazecompPackageImpl.init();

  /**
   * The meta object id for the '{@link main.game.maze.mazecomp.impl.MazeFileImpl <em>Maze File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see main.game.maze.mazecomp.impl.MazeFileImpl
   * @see main.game.maze.mazecomp.impl.MazecompPackageImpl#getMazeFile()
   * @generated
   */
  int MAZE_FILE = 0;

  /**
   * The feature id for the '<em><b>Zombies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE__ZOMBIES = 0;

  /**
   * The feature id for the '<em><b>Ghosts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE__GHOSTS = 1;

  /**
   * The feature id for the '<em><b>Pumpkin Bombers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE__PUMPKIN_BOMBERS = 2;

  /**
   * The feature id for the '<em><b>Loot Tables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE__LOOT_TABLES = 3;

  /**
   * The feature id for the '<em><b>Loot Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE__LOOT_ITEMS = 4;

  /**
   * The number of structural features of the '<em>Maze File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAZE_FILE_FEATURE_COUNT = 5;


  /**
   * Returns the meta object for class '{@link main.game.maze.mazecomp.MazeFile <em>Maze File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Maze File</em>'.
   * @see main.game.maze.mazecomp.MazeFile
   * @generated
   */
  EClass getMazeFile();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.mazecomp.MazeFile#getZombies <em>Zombies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Zombies</em>'.
   * @see main.game.maze.mazecomp.MazeFile#getZombies()
   * @see #getMazeFile()
   * @generated
   */
  EReference getMazeFile_Zombies();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.mazecomp.MazeFile#getGhosts <em>Ghosts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ghosts</em>'.
   * @see main.game.maze.mazecomp.MazeFile#getGhosts()
   * @see #getMazeFile()
   * @generated
   */
  EReference getMazeFile_Ghosts();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.mazecomp.MazeFile#getPumpkinBombers <em>Pumpkin Bombers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pumpkin Bombers</em>'.
   * @see main.game.maze.mazecomp.MazeFile#getPumpkinBombers()
   * @see #getMazeFile()
   * @generated
   */
  EReference getMazeFile_PumpkinBombers();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.mazecomp.MazeFile#getLootTables <em>Loot Tables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loot Tables</em>'.
   * @see main.game.maze.mazecomp.MazeFile#getLootTables()
   * @see #getMazeFile()
   * @generated
   */
  EReference getMazeFile_LootTables();

  /**
   * Returns the meta object for the containment reference list '{@link main.game.maze.mazecomp.MazeFile#getLootItems <em>Loot Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Loot Items</em>'.
   * @see main.game.maze.mazecomp.MazeFile#getLootItems()
   * @see #getMazeFile()
   * @generated
   */
  EReference getMazeFile_LootItems();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MazecompFactory getMazecompFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link main.game.maze.mazecomp.impl.MazeFileImpl <em>Maze File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see main.game.maze.mazecomp.impl.MazeFileImpl
     * @see main.game.maze.mazecomp.impl.MazecompPackageImpl#getMazeFile()
     * @generated
     */
    EClass MAZE_FILE = eINSTANCE.getMazeFile();

    /**
     * The meta object literal for the '<em><b>Zombies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_FILE__ZOMBIES = eINSTANCE.getMazeFile_Zombies();

    /**
     * The meta object literal for the '<em><b>Ghosts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_FILE__GHOSTS = eINSTANCE.getMazeFile_Ghosts();

    /**
     * The meta object literal for the '<em><b>Pumpkin Bombers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_FILE__PUMPKIN_BOMBERS = eINSTANCE.getMazeFile_PumpkinBombers();

    /**
     * The meta object literal for the '<em><b>Loot Tables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_FILE__LOOT_TABLES = eINSTANCE.getMazeFile_LootTables();

    /**
     * The meta object literal for the '<em><b>Loot Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAZE_FILE__LOOT_ITEMS = eINSTANCE.getMazeFile_LootItems();

  }

} //MazecompPackage
