/*
 * generated by Xtext 2.40.0
 */
package main.game.maze.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;

import main.game.maze.xtextgen.MazeCompRuntimeModule;
import main.game.maze.xtextgen.MazeCompStandaloneSetup;

import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MazeCompIdeSetup extends MazeCompStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MazeCompRuntimeModule(), new MazeCompIdeModule()));
	}
	
}
