/*
 * generated by Xtext 2.40.0
 */
grammar InternalMazeComp;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package main.game.maze.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package main.game.maze.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import main.game.maze.services.MazeCompGrammarAccess;

}

@parser::members {

 	private MazeCompGrammarAccess grammarAccess;

    public InternalMazeCompParser(TokenStream input, MazeCompGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "MazeFile";
   	}

   	@Override
   	protected MazeCompGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleMazeFile
entryRuleMazeFile returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMazeFileRule()); }
	iv_ruleMazeFile=ruleMazeFile
	{ $current=$iv_ruleMazeFile.current; }
	EOF;

// Rule MazeFile
ruleMazeFile returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getMazeFileAccess().getZombiesZombieParserRuleCall_0_0());
				}
				lv_zombies_0_0=ruleZombie
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMazeFileRule());
					}
					add(
						$current,
						"zombies",
						lv_zombies_0_0,
						"main.game.maze.MazeComp.Zombie");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMazeFileAccess().getGhostsGhostParserRuleCall_1_0());
				}
				lv_ghosts_1_0=ruleGhost
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMazeFileRule());
					}
					add(
						$current,
						"ghosts",
						lv_ghosts_1_0,
						"main.game.maze.MazeComp.Ghost");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMazeFileAccess().getPumpkinBombersPumpkinBomberParserRuleCall_2_0());
				}
				lv_pumpkinBombers_2_0=rulePumpkinBomber
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMazeFileRule());
					}
					add(
						$current,
						"pumpkinBombers",
						lv_pumpkinBombers_2_0,
						"main.game.maze.MazeComp.PumpkinBomber");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMazeFileAccess().getLootTablesLootTableParserRuleCall_3_0());
				}
				lv_lootTables_3_0=ruleLootTable
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMazeFileRule());
					}
					add(
						$current,
						"lootTables",
						lv_lootTables_3_0,
						"main.game.maze.MazeComp.LootTable");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		(
			(
				{
					newCompositeNode(grammarAccess.getMazeFileAccess().getLootItemsLootItemParserRuleCall_4_0());
				}
				lv_lootItems_4_0=ruleLootItem
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMazeFileRule());
					}
					add(
						$current,
						"lootItems",
						lv_lootItems_4_0,
						"main.game.maze.MazeComp.LootItem");
					afterParserOrEnumRuleCall();
				}
			)
		)*
	)
;

// Entry rule entryRuleEString
entryRuleEString returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEStringRule()); }
	iv_ruleEString=ruleEString
	{ $current=$iv_ruleEString.current.getText(); }
	EOF;

// Rule EString
ruleEString returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		this_STRING_0=RULE_STRING
		{
			$current.merge(this_STRING_0);
		}
		{
			newLeafNode(this_STRING_0, grammarAccess.getEStringAccess().getSTRINGTerminalRuleCall_0());
		}
		    |
		this_ID_1=RULE_ID
		{
			$current.merge(this_ID_1);
		}
		{
			newLeafNode(this_ID_1, grammarAccess.getEStringAccess().getIDTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEBoolean
entryRuleEBoolean returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEBooleanRule()); }
	iv_ruleEBoolean=ruleEBoolean
	{ $current=$iv_ruleEBoolean.current.getText(); }
	EOF;

// Rule EBoolean
ruleEBoolean returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		kw='true'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getTrueKeyword_0());
		}
		    |
		kw='false'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEBooleanAccess().getFalseKeyword_1());
		}
	)
;

// Entry rule entryRuleEInt
entryRuleEInt returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEIntRule()); }
	iv_ruleEInt=ruleEInt
	{ $current=$iv_ruleEInt.current.getText(); }
	EOF;

// Rule EInt
ruleEInt returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEIntAccess().getHyphenMinusKeyword_0());
			}
		)?
		this_INT_1=RULE_INT
		{
			$current.merge(this_INT_1);
		}
		{
			newLeafNode(this_INT_1, grammarAccess.getEIntAccess().getINTTerminalRuleCall_1());
		}
	)
;

// Entry rule entryRuleEDouble
entryRuleEDouble returns [String current=null]:
	{ newCompositeNode(grammarAccess.getEDoubleRule()); }
	iv_ruleEDouble=ruleEDouble
	{ $current=$iv_ruleEDouble.current.getText(); }
	EOF;

// Rule EDouble
ruleEDouble returns [AntlrDatatypeRuleToken current=new AntlrDatatypeRuleToken()]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			kw='-'
			{
				$current.merge(kw);
				newLeafNode(kw, grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_0());
			}
		)?
		(
			this_INT_1=RULE_INT
			{
				$current.merge(this_INT_1);
			}
			{
				newLeafNode(this_INT_1, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_1());
			}
		)?
		kw='.'
		{
			$current.merge(kw);
			newLeafNode(kw, grammarAccess.getEDoubleAccess().getFullStopKeyword_2());
		}
		this_INT_3=RULE_INT
		{
			$current.merge(this_INT_3);
		}
		{
			newLeafNode(this_INT_3, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_3());
		}
		(
			(
				kw='E'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getEKeyword_4_0_0());
				}
				    |
				kw='e'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getEKeyword_4_0_1());
				}
			)
			(
				kw='-'
				{
					$current.merge(kw);
					newLeafNode(kw, grammarAccess.getEDoubleAccess().getHyphenMinusKeyword_4_1());
				}
			)?
			this_INT_7=RULE_INT
			{
				$current.merge(this_INT_7);
			}
			{
				newLeafNode(this_INT_7, grammarAccess.getEDoubleAccess().getINTTerminalRuleCall_4_2());
			}
		)?
	)
;

// Entry rule entryRuleZombie
entryRuleZombie returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getZombieRule()); }
	iv_ruleZombie=ruleZombie
	{ $current=$iv_ruleZombie.current; }
	EOF;

// Rule Zombie
ruleZombie returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Zombie'
		{
			newLeafNode(otherlv_0, grammarAccess.getZombieAccess().getZombieKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getZombieAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='id'
			{
				newLeafNode(otherlv_2, grammarAccess.getZombieAccess().getIdKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getIdEStringParserRuleCall_2_1_0());
					}
					lv_id_3_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"id",
							lv_id_3_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_4='displayName'
			{
				newLeafNode(otherlv_4, grammarAccess.getZombieAccess().getDisplayNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getDisplayNameEStringParserRuleCall_3_1_0());
					}
					lv_displayName_5_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"displayName",
							lv_displayName_5_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='enabled'
		{
			newLeafNode(otherlv_6, grammarAccess.getZombieAccess().getEnabledKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getEnabledEBooleanParserRuleCall_5_0());
				}
				lv_enabled_7_0=ruleEBoolean
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"enabled",
						lv_enabled_7_0,
						"main.game.maze.MazeComp.EBoolean");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='health'
		{
			newLeafNode(otherlv_8, grammarAccess.getZombieAccess().getHealthKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getHealthEIntParserRuleCall_7_0());
				}
				lv_health_9_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"health",
						lv_health_9_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='speed'
		{
			newLeafNode(otherlv_10, grammarAccess.getZombieAccess().getSpeedKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getSpeedEDoubleParserRuleCall_9_0());
				}
				lv_speed_11_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"speed",
						lv_speed_11_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_12='ImageBase'
			{
				newLeafNode(otherlv_12, grammarAccess.getZombieAccess().getImageBaseKeyword_10_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getImageBaseEStringParserRuleCall_10_1_0());
					}
					lv_ImageBase_13_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"ImageBase",
							lv_ImageBase_13_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_14='ImageTurnLeft'
			{
				newLeafNode(otherlv_14, grammarAccess.getZombieAccess().getImageTurnLeftKeyword_11_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getImageTurnLeftEStringParserRuleCall_11_1_0());
					}
					lv_ImageTurnLeft_15_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"ImageTurnLeft",
							lv_ImageTurnLeft_15_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_16='ImageTurnRight'
			{
				newLeafNode(otherlv_16, grammarAccess.getZombieAccess().getImageTurnRightKeyword_12_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getImageTurnRightEStringParserRuleCall_12_1_0());
					}
					lv_ImageTurnRight_17_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"ImageTurnRight",
							lv_ImageTurnRight_17_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_18='ImageTurnUp'
			{
				newLeafNode(otherlv_18, grammarAccess.getZombieAccess().getImageTurnUpKeyword_13_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getImageTurnUpEStringParserRuleCall_13_1_0());
					}
					lv_ImageTurnUp_19_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"ImageTurnUp",
							lv_ImageTurnUp_19_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_20='ImageTurnDown'
			{
				newLeafNode(otherlv_20, grammarAccess.getZombieAccess().getImageTurnDownKeyword_14_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getImageTurnDownEStringParserRuleCall_14_1_0());
					}
					lv_ImageTurnDown_21_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"ImageTurnDown",
							lv_ImageTurnDown_21_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_22='behavior'
			{
				newLeafNode(otherlv_22, grammarAccess.getZombieAccess().getBehaviorKeyword_15_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getBehaviorBehaviorTypeEnumRuleCall_15_1_0());
					}
					lv_behavior_23_0=ruleBehaviorType
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"behavior",
							lv_behavior_23_0,
							"main.game.maze.MazeComp.BehaviorType");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_24='attackDamage'
		{
			newLeafNode(otherlv_24, grammarAccess.getZombieAccess().getAttackDamageKeyword_16());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getAttackDamageEIntParserRuleCall_17_0());
				}
				lv_attackDamage_25_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"attackDamage",
						lv_attackDamage_25_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_26='infectionLevel'
		{
			newLeafNode(otherlv_26, grammarAccess.getZombieAccess().getInfectionLevelKeyword_18());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getInfectionLevelEIntParserRuleCall_19_0());
				}
				lv_infectionLevel_27_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"infectionLevel",
						lv_infectionLevel_27_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_28='resurrectionTime'
		{
			newLeafNode(otherlv_28, grammarAccess.getZombieAccess().getResurrectionTimeKeyword_20());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getZombieAccess().getResurrectionTimeEIntParserRuleCall_21_0());
				}
				lv_resurrectionTime_29_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getZombieRule());
					}
					set(
						$current,
						"resurrectionTime",
						lv_resurrectionTime_29_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_30='touchSound'
			{
				newLeafNode(otherlv_30, grammarAccess.getZombieAccess().getTouchSoundKeyword_22_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getZombieAccess().getTouchSoundEStringParserRuleCall_22_1_0());
					}
					lv_touchSound_31_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getZombieRule());
						}
						set(
							$current,
							"touchSound",
							lv_touchSound_31_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_32='zombieLootTable'
			{
				newLeafNode(otherlv_32, grammarAccess.getZombieAccess().getZombieLootTableKeyword_23_0());
			}
			(
				(
					{
						if ($current==null) {
							$current = createModelElement(grammarAccess.getZombieRule());
						}
					}
					{
						newCompositeNode(grammarAccess.getZombieAccess().getZombieLootTableLootTableCrossReference_23_1_0());
					}
					ruleEString
					{
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_34='}'
		{
			newLeafNode(otherlv_34, grammarAccess.getZombieAccess().getRightCurlyBracketKeyword_24());
		}
	)
;

// Entry rule entryRuleGhost
entryRuleGhost returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getGhostRule()); }
	iv_ruleGhost=ruleGhost
	{ $current=$iv_ruleGhost.current; }
	EOF;

// Rule Ghost
ruleGhost returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='Ghost'
		{
			newLeafNode(otherlv_0, grammarAccess.getGhostAccess().getGhostKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getGhostAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='id'
			{
				newLeafNode(otherlv_2, grammarAccess.getGhostAccess().getIdKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getIdEStringParserRuleCall_2_1_0());
					}
					lv_id_3_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"id",
							lv_id_3_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_4='displayName'
			{
				newLeafNode(otherlv_4, grammarAccess.getGhostAccess().getDisplayNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getDisplayNameEStringParserRuleCall_3_1_0());
					}
					lv_displayName_5_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"displayName",
							lv_displayName_5_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='enabled'
		{
			newLeafNode(otherlv_6, grammarAccess.getGhostAccess().getEnabledKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getEnabledEBooleanParserRuleCall_5_0());
				}
				lv_enabled_7_0=ruleEBoolean
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"enabled",
						lv_enabled_7_0,
						"main.game.maze.MazeComp.EBoolean");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='health'
		{
			newLeafNode(otherlv_8, grammarAccess.getGhostAccess().getHealthKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getHealthEIntParserRuleCall_7_0());
				}
				lv_health_9_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"health",
						lv_health_9_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='speed'
		{
			newLeafNode(otherlv_10, grammarAccess.getGhostAccess().getSpeedKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getSpeedEDoubleParserRuleCall_9_0());
				}
				lv_speed_11_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"speed",
						lv_speed_11_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_12='ImageBase'
			{
				newLeafNode(otherlv_12, grammarAccess.getGhostAccess().getImageBaseKeyword_10_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getImageBaseEStringParserRuleCall_10_1_0());
					}
					lv_ImageBase_13_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"ImageBase",
							lv_ImageBase_13_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_14='ImageTurnLeft'
			{
				newLeafNode(otherlv_14, grammarAccess.getGhostAccess().getImageTurnLeftKeyword_11_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getImageTurnLeftEStringParserRuleCall_11_1_0());
					}
					lv_ImageTurnLeft_15_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"ImageTurnLeft",
							lv_ImageTurnLeft_15_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_16='ImageTurnRight'
			{
				newLeafNode(otherlv_16, grammarAccess.getGhostAccess().getImageTurnRightKeyword_12_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getImageTurnRightEStringParserRuleCall_12_1_0());
					}
					lv_ImageTurnRight_17_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"ImageTurnRight",
							lv_ImageTurnRight_17_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_18='ImageTurnUp'
			{
				newLeafNode(otherlv_18, grammarAccess.getGhostAccess().getImageTurnUpKeyword_13_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getImageTurnUpEStringParserRuleCall_13_1_0());
					}
					lv_ImageTurnUp_19_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"ImageTurnUp",
							lv_ImageTurnUp_19_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_20='ImageTurnDown'
			{
				newLeafNode(otherlv_20, grammarAccess.getGhostAccess().getImageTurnDownKeyword_14_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getImageTurnDownEStringParserRuleCall_14_1_0());
					}
					lv_ImageTurnDown_21_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"ImageTurnDown",
							lv_ImageTurnDown_21_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_22='behavior'
			{
				newLeafNode(otherlv_22, grammarAccess.getGhostAccess().getBehaviorKeyword_15_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getGhostAccess().getBehaviorBehaviorTypeEnumRuleCall_15_1_0());
					}
					lv_behavior_23_0=ruleBehaviorType
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getGhostRule());
						}
						set(
							$current,
							"behavior",
							lv_behavior_23_0,
							"main.game.maze.MazeComp.BehaviorType");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_24='attackDamage'
		{
			newLeafNode(otherlv_24, grammarAccess.getGhostAccess().getAttackDamageKeyword_16());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getAttackDamageEIntParserRuleCall_17_0());
				}
				lv_attackDamage_25_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"attackDamage",
						lv_attackDamage_25_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_26='visibilityLevel'
		{
			newLeafNode(otherlv_26, grammarAccess.getGhostAccess().getVisibilityLevelKeyword_18());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getVisibilityLevelEIntParserRuleCall_19_0());
				}
				lv_visibilityLevel_27_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"visibilityLevel",
						lv_visibilityLevel_27_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_28='nonTangibilityEnergy'
		{
			newLeafNode(otherlv_28, grammarAccess.getGhostAccess().getNonTangibilityEnergyKeyword_20());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getGhostAccess().getNonTangibilityEnergyEDoubleParserRuleCall_21_0());
				}
				lv_nonTangibilityEnergy_29_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getGhostRule());
					}
					set(
						$current,
						"nonTangibilityEnergy",
						lv_nonTangibilityEnergy_29_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_30='}'
		{
			newLeafNode(otherlv_30, grammarAccess.getGhostAccess().getRightCurlyBracketKeyword_22());
		}
	)
;

// Entry rule entryRulePumpkinBomber
entryRulePumpkinBomber returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPumpkinBomberRule()); }
	iv_rulePumpkinBomber=rulePumpkinBomber
	{ $current=$iv_rulePumpkinBomber.current; }
	EOF;

// Rule PumpkinBomber
rulePumpkinBomber returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='PumpkinBomber'
		{
			newLeafNode(otherlv_0, grammarAccess.getPumpkinBomberAccess().getPumpkinBomberKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getPumpkinBomberAccess().getLeftCurlyBracketKeyword_1());
		}
		(
			otherlv_2='id'
			{
				newLeafNode(otherlv_2, grammarAccess.getPumpkinBomberAccess().getIdKeyword_2_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getIdEStringParserRuleCall_2_1_0());
					}
					lv_id_3_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"id",
							lv_id_3_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_4='displayName'
			{
				newLeafNode(otherlv_4, grammarAccess.getPumpkinBomberAccess().getDisplayNameKeyword_3_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getDisplayNameEStringParserRuleCall_3_1_0());
					}
					lv_displayName_5_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"displayName",
							lv_displayName_5_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_6='enabled'
		{
			newLeafNode(otherlv_6, grammarAccess.getPumpkinBomberAccess().getEnabledKeyword_4());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getEnabledEBooleanParserRuleCall_5_0());
				}
				lv_enabled_7_0=ruleEBoolean
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"enabled",
						lv_enabled_7_0,
						"main.game.maze.MazeComp.EBoolean");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_8='health'
		{
			newLeafNode(otherlv_8, grammarAccess.getPumpkinBomberAccess().getHealthKeyword_6());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getHealthEIntParserRuleCall_7_0());
				}
				lv_health_9_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"health",
						lv_health_9_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_10='speed'
		{
			newLeafNode(otherlv_10, grammarAccess.getPumpkinBomberAccess().getSpeedKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getSpeedEDoubleParserRuleCall_9_0());
				}
				lv_speed_11_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"speed",
						lv_speed_11_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_12='ImageBase'
			{
				newLeafNode(otherlv_12, grammarAccess.getPumpkinBomberAccess().getImageBaseKeyword_10_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getImageBaseEStringParserRuleCall_10_1_0());
					}
					lv_ImageBase_13_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"ImageBase",
							lv_ImageBase_13_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_14='ImageTurnLeft'
			{
				newLeafNode(otherlv_14, grammarAccess.getPumpkinBomberAccess().getImageTurnLeftKeyword_11_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getImageTurnLeftEStringParserRuleCall_11_1_0());
					}
					lv_ImageTurnLeft_15_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"ImageTurnLeft",
							lv_ImageTurnLeft_15_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_16='ImageTurnRight'
			{
				newLeafNode(otherlv_16, grammarAccess.getPumpkinBomberAccess().getImageTurnRightKeyword_12_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getImageTurnRightEStringParserRuleCall_12_1_0());
					}
					lv_ImageTurnRight_17_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"ImageTurnRight",
							lv_ImageTurnRight_17_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_18='ImageTurnUp'
			{
				newLeafNode(otherlv_18, grammarAccess.getPumpkinBomberAccess().getImageTurnUpKeyword_13_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getImageTurnUpEStringParserRuleCall_13_1_0());
					}
					lv_ImageTurnUp_19_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"ImageTurnUp",
							lv_ImageTurnUp_19_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_20='ImageTurnDown'
			{
				newLeafNode(otherlv_20, grammarAccess.getPumpkinBomberAccess().getImageTurnDownKeyword_14_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getImageTurnDownEStringParserRuleCall_14_1_0());
					}
					lv_ImageTurnDown_21_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"ImageTurnDown",
							lv_ImageTurnDown_21_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_22='behavior'
			{
				newLeafNode(otherlv_22, grammarAccess.getPumpkinBomberAccess().getBehaviorKeyword_15_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getBehaviorBehaviorTypeEnumRuleCall_15_1_0());
					}
					lv_behavior_23_0=ruleBehaviorType
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"behavior",
							lv_behavior_23_0,
							"main.game.maze.MazeComp.BehaviorType");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_24='attackRange'
		{
			newLeafNode(otherlv_24, grammarAccess.getPumpkinBomberAccess().getAttackRangeKeyword_16());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getAttackRangeEDoubleParserRuleCall_17_0());
				}
				lv_attackRange_25_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"attackRange",
						lv_attackRange_25_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_26='attackCooldownMs'
		{
			newLeafNode(otherlv_26, grammarAccess.getPumpkinBomberAccess().getAttackCooldownMsKeyword_18());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getAttackCooldownMsEIntParserRuleCall_19_0());
				}
				lv_attackCooldownMs_27_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"attackCooldownMs",
						lv_attackCooldownMs_27_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_28='attackDamage'
		{
			newLeafNode(otherlv_28, grammarAccess.getPumpkinBomberAccess().getAttackDamageKeyword_20());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getAttackDamageEIntParserRuleCall_21_0());
				}
				lv_attackDamage_29_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"attackDamage",
						lv_attackDamage_29_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_30='projectileSpeed'
		{
			newLeafNode(otherlv_30, grammarAccess.getPumpkinBomberAccess().getProjectileSpeedKeyword_22());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getProjectileSpeedEDoubleParserRuleCall_23_0());
				}
				lv_projectileSpeed_31_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"projectileSpeed",
						lv_projectileSpeed_31_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_32='projectileType'
		{
			newLeafNode(otherlv_32, grammarAccess.getPumpkinBomberAccess().getProjectileTypeKeyword_24());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getProjectileTypeProjectileTypeEnumRuleCall_25_0());
				}
				lv_projectileType_33_0=ruleProjectileType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"projectileType",
						lv_projectileType_33_0,
						"main.game.maze.MazeComp.ProjectileType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_34='splashRadius'
		{
			newLeafNode(otherlv_34, grammarAccess.getPumpkinBomberAccess().getSplashRadiusKeyword_26());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getSplashRadiusEDoubleParserRuleCall_27_0());
				}
				lv_splashRadius_35_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"splashRadius",
						lv_splashRadius_35_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_36='arcHeight'
		{
			newLeafNode(otherlv_36, grammarAccess.getPumpkinBomberAccess().getArcHeightKeyword_28());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getPumpkinBomberAccess().getArcHeightEDoubleParserRuleCall_29_0());
				}
				lv_arcHeight_37_0=ruleEDouble
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
					}
					set(
						$current,
						"arcHeight",
						lv_arcHeight_37_0,
						"main.game.maze.MazeComp.EDouble");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_38='projectileImage'
			{
				newLeafNode(otherlv_38, grammarAccess.getPumpkinBomberAccess().getProjectileImageKeyword_30_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getProjectileImageEStringParserRuleCall_30_1_0());
					}
					lv_projectileImage_39_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"projectileImage",
							lv_projectileImage_39_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_40='explosionImage'
			{
				newLeafNode(otherlv_40, grammarAccess.getPumpkinBomberAccess().getExplosionImageKeyword_31_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getExplosionImageEStringParserRuleCall_31_1_0());
					}
					lv_explosionImage_41_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"explosionImage",
							lv_explosionImage_41_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_42='explosionSound'
			{
				newLeafNode(otherlv_42, grammarAccess.getPumpkinBomberAccess().getExplosionSoundKeyword_32_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getExplosionSoundEStringParserRuleCall_32_1_0());
					}
					lv_explosionSound_43_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"explosionSound",
							lv_explosionSound_43_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		(
			otherlv_44='throwSound'
			{
				newLeafNode(otherlv_44, grammarAccess.getPumpkinBomberAccess().getThrowSoundKeyword_33_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getPumpkinBomberAccess().getThrowSoundEStringParserRuleCall_33_1_0());
					}
					lv_throwSound_45_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getPumpkinBomberRule());
						}
						set(
							$current,
							"throwSound",
							lv_throwSound_45_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_46='}'
		{
			newLeafNode(otherlv_46, grammarAccess.getPumpkinBomberAccess().getRightCurlyBracketKeyword_34());
		}
	)
;

// Entry rule entryRuleLootTable
entryRuleLootTable returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLootTableRule()); }
	iv_ruleLootTable=ruleLootTable
	{ $current=$iv_ruleLootTable.current; }
	EOF;

// Rule LootTable
ruleLootTable returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='LootTable'
		{
			newLeafNode(otherlv_0, grammarAccess.getLootTableAccess().getLootTableKeyword_0());
		}
		otherlv_1='{'
		{
			newLeafNode(otherlv_1, grammarAccess.getLootTableAccess().getLeftCurlyBracketKeyword_1());
		}
		otherlv_2='weightCapacity'
		{
			newLeafNode(otherlv_2, grammarAccess.getLootTableAccess().getWeightCapacityKeyword_2());
		}
		otherlv_3='{'
		{
			newLeafNode(otherlv_3, grammarAccess.getLootTableAccess().getLeftCurlyBracketKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLootTableAccess().getWeightCapacityEIntParserRuleCall_4_0());
				}
				lv_weightCapacity_4_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLootTableRule());
					}
					add(
						$current,
						"weightCapacity",
						lv_weightCapacity_4_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_5=','
			{
				newLeafNode(otherlv_5, grammarAccess.getLootTableAccess().getCommaKeyword_5_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getLootTableAccess().getWeightCapacityEIntParserRuleCall_5_1_0());
					}
					lv_weightCapacity_6_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getLootTableRule());
						}
						add(
							$current,
							"weightCapacity",
							lv_weightCapacity_6_0,
							"main.game.maze.MazeComp.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_7='}'
		{
			newLeafNode(otherlv_7, grammarAccess.getLootTableAccess().getRightCurlyBracketKeyword_6());
		}
		(
			otherlv_8='items'
			{
				newLeafNode(otherlv_8, grammarAccess.getLootTableAccess().getItemsKeyword_7_0());
			}
			otherlv_9='{'
			{
				newLeafNode(otherlv_9, grammarAccess.getLootTableAccess().getLeftCurlyBracketKeyword_7_1());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getLootTableAccess().getItemsLootItemParserRuleCall_7_2_0());
					}
					lv_items_10_0=ruleLootItem
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getLootTableRule());
						}
						add(
							$current,
							"items",
							lv_items_10_0,
							"main.game.maze.MazeComp.LootItem");
						afterParserOrEnumRuleCall();
					}
				)
			)
			(
				otherlv_11=','
				{
					newLeafNode(otherlv_11, grammarAccess.getLootTableAccess().getCommaKeyword_7_3_0());
				}
				(
					(
						{
							newCompositeNode(grammarAccess.getLootTableAccess().getItemsLootItemParserRuleCall_7_3_1_0());
						}
						lv_items_12_0=ruleLootItem
						{
							if ($current==null) {
								$current = createModelElementForParent(grammarAccess.getLootTableRule());
							}
							add(
								$current,
								"items",
								lv_items_12_0,
								"main.game.maze.MazeComp.LootItem");
							afterParserOrEnumRuleCall();
						}
					)
				)
			)*
			otherlv_13='}'
			{
				newLeafNode(otherlv_13, grammarAccess.getLootTableAccess().getRightCurlyBracketKeyword_7_4());
			}
		)?
		otherlv_14='}'
		{
			newLeafNode(otherlv_14, grammarAccess.getLootTableAccess().getRightCurlyBracketKeyword_8());
		}
	)
;

// Entry rule entryRuleLootItem
entryRuleLootItem returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getLootItemRule()); }
	iv_ruleLootItem=ruleLootItem
	{ $current=$iv_ruleLootItem.current; }
	EOF;

// Rule LootItem
ruleLootItem returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='LootItem'
		{
			newLeafNode(otherlv_0, grammarAccess.getLootItemAccess().getLootItemKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLootItemAccess().getNameEStringParserRuleCall_1_0());
				}
				lv_name_1_0=ruleEString
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLootItemRule());
					}
					set(
						$current,
						"name",
						lv_name_1_0,
						"main.game.maze.MazeComp.EString");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2='{'
		{
			newLeafNode(otherlv_2, grammarAccess.getLootItemAccess().getLeftCurlyBracketKeyword_2());
		}
		otherlv_3='type'
		{
			newLeafNode(otherlv_3, grammarAccess.getLootItemAccess().getTypeKeyword_3());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLootItemAccess().getTypeLootItemTypeEnumRuleCall_4_0());
				}
				lv_type_4_0=ruleLootItemType
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLootItemRule());
					}
					set(
						$current,
						"type",
						lv_type_4_0,
						"main.game.maze.MazeComp.LootItemType");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_5='value'
		{
			newLeafNode(otherlv_5, grammarAccess.getLootItemAccess().getValueKeyword_5());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLootItemAccess().getValueEIntParserRuleCall_6_0());
				}
				lv_value_6_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLootItemRule());
					}
					set(
						$current,
						"value",
						lv_value_6_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_7='weight'
		{
			newLeafNode(otherlv_7, grammarAccess.getLootItemAccess().getWeightKeyword_7());
		}
		otherlv_8='{'
		{
			newLeafNode(otherlv_8, grammarAccess.getLootItemAccess().getLeftCurlyBracketKeyword_8());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getLootItemAccess().getWeightEIntParserRuleCall_9_0());
				}
				lv_weight_9_0=ruleEInt
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getLootItemRule());
					}
					add(
						$current,
						"weight",
						lv_weight_9_0,
						"main.game.maze.MazeComp.EInt");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			otherlv_10=','
			{
				newLeafNode(otherlv_10, grammarAccess.getLootItemAccess().getCommaKeyword_10_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getLootItemAccess().getWeightEIntParserRuleCall_10_1_0());
					}
					lv_weight_11_0=ruleEInt
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getLootItemRule());
						}
						add(
							$current,
							"weight",
							lv_weight_11_0,
							"main.game.maze.MazeComp.EInt");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
		otherlv_12='}'
		{
			newLeafNode(otherlv_12, grammarAccess.getLootItemAccess().getRightCurlyBracketKeyword_11());
		}
		(
			otherlv_13='graphicBase'
			{
				newLeafNode(otherlv_13, grammarAccess.getLootItemAccess().getGraphicBaseKeyword_12_0());
			}
			(
				(
					{
						newCompositeNode(grammarAccess.getLootItemAccess().getGraphicBaseEStringParserRuleCall_12_1_0());
					}
					lv_graphicBase_14_0=ruleEString
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getLootItemRule());
						}
						set(
							$current,
							"graphicBase",
							lv_graphicBase_14_0,
							"main.game.maze.MazeComp.EString");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)?
		otherlv_15='}'
		{
			newLeafNode(otherlv_15, grammarAccess.getLootItemAccess().getRightCurlyBracketKeyword_13());
		}
	)
;

// Rule BehaviorType
ruleBehaviorType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='PASSIVE'
			{
				$current = grammarAccess.getBehaviorTypeAccess().getPASSIVEEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getBehaviorTypeAccess().getPASSIVEEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='WANDER'
			{
				$current = grammarAccess.getBehaviorTypeAccess().getWANDEREnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getBehaviorTypeAccess().getWANDEREnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='AGGRESSIVE'
			{
				$current = grammarAccess.getBehaviorTypeAccess().getAGGRESSIVEEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getBehaviorTypeAccess().getAGGRESSIVEEnumLiteralDeclaration_2());
			}
		)
	)
;

// Rule LootItemType
ruleLootItemType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='FOOD'
			{
				$current = grammarAccess.getLootItemTypeAccess().getFOODEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getLootItemTypeAccess().getFOODEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='BOMB'
			{
				$current = grammarAccess.getLootItemTypeAccess().getBOMBEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getLootItemTypeAccess().getBOMBEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='TRAP'
			{
				$current = grammarAccess.getLootItemTypeAccess().getTRAPEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getLootItemTypeAccess().getTRAPEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='WEAPON'
			{
				$current = grammarAccess.getLootItemTypeAccess().getWEAPONEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getLootItemTypeAccess().getWEAPONEnumLiteralDeclaration_3());
			}
		)
	)
;

// Rule ProjectileType
ruleProjectileType returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='STRAIGHT'
			{
				$current = grammarAccess.getProjectileTypeAccess().getSTRAIGHTEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getProjectileTypeAccess().getSTRAIGHTEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='LOB'
			{
				$current = grammarAccess.getProjectileTypeAccess().getLOBEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getProjectileTypeAccess().getLOBEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='BEAM'
			{
				$current = grammarAccess.getProjectileTypeAccess().getBEAMEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getProjectileTypeAccess().getBEAMEnumLiteralDeclaration_2());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
