/*
 * generated by Xtext
 */
package main.game.maze.dsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import main.game.maze.dsl.mazeDsl.DifficultyConfig;
import main.game.maze.dsl.mazeDsl.EnemyLimit;
import main.game.maze.dsl.mazeDsl.GameConfiguration;
import main.game.maze.dsl.mazeDsl.GhostSpecifics;
import main.game.maze.dsl.mazeDsl.Import;
import main.game.maze.dsl.mazeDsl.LootItemConfig;
import main.game.maze.dsl.mazeDsl.LootTableConfig;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;
import main.game.maze.dsl.mazeDsl.OpponentConfig;
import main.game.maze.dsl.mazeDsl.PatrolConfig;
import main.game.maze.dsl.mazeDsl.PatrolZoneConfig;
import main.game.maze.dsl.mazeDsl.RangedSpecifics;
import main.game.maze.dsl.mazeDsl.Waypoint;
import main.game.maze.dsl.mazeDsl.ZombieSpecifics;
import main.game.maze.dsl.services.MazeDslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class MazeDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MazeDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MazeDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MazeDslPackage.DIFFICULTY_CONFIG:
				sequence_DifficultyConfig(context, (DifficultyConfig) semanticObject); 
				return; 
			case MazeDslPackage.ENEMY_LIMIT:
				sequence_EnemyLimit(context, (EnemyLimit) semanticObject); 
				return; 
			case MazeDslPackage.GAME_CONFIGURATION:
				sequence_GameConfiguration(context, (GameConfiguration) semanticObject); 
				return; 
			case MazeDslPackage.GHOST_SPECIFICS:
				sequence_GhostSpecifics(context, (GhostSpecifics) semanticObject); 
				return; 
			case MazeDslPackage.IMPORT:
				sequence_Import(context, (Import) semanticObject); 
				return; 
			case MazeDslPackage.LOOT_ITEM_CONFIG:
				sequence_LootItemConfig(context, (LootItemConfig) semanticObject); 
				return; 
			case MazeDslPackage.LOOT_TABLE_CONFIG:
				sequence_LootTableConfig(context, (LootTableConfig) semanticObject); 
				return; 
			case MazeDslPackage.OPPONENT_CONFIG:
				sequence_OpponentConfig(context, (OpponentConfig) semanticObject); 
				return; 
			case MazeDslPackage.PATROL_CONFIG:
				sequence_PatrolConfig(context, (PatrolConfig) semanticObject); 
				return; 
			case MazeDslPackage.PATROL_ZONE_CONFIG:
				sequence_PatrolZoneConfig(context, (PatrolZoneConfig) semanticObject); 
				return; 
			case MazeDslPackage.RANGED_SPECIFICS:
				sequence_RangedSpecifics(context, (RangedSpecifics) semanticObject); 
				return; 
			case MazeDslPackage.WAYPOINT:
				sequence_Waypoint(context, (Waypoint) semanticObject); 
				return; 
			case MazeDslPackage.ZOMBIE_SPECIFICS:
				sequence_ZombieSpecifics(context, (ZombieSpecifics) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     DifficultyConfig returns DifficultyConfig
	 *
	 * Constraint:
	 *     (
	 *         level=DifficultyLevel 
	 *         instantDeath?='true'? 
	 *         speedMultiplier=DOUBLE? 
	 *         damageMultiplier=DOUBLE? 
	 *         maxThreat=SIGNED_INT? 
	 *         enemyLimits+=EnemyLimit*
	 *     )
	 * </pre>
	 */
	protected void sequence_DifficultyConfig(ISerializationContext context, DifficultyConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     EnemyLimit returns EnemyLimit
	 *
	 * Constraint:
	 *     (type=EnemyType maxCount=SIGNED_INT)
	 * </pre>
	 */
	protected void sequence_EnemyLimit(ISerializationContext context, EnemyLimit semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.ENEMY_LIMIT__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.ENEMY_LIMIT__TYPE));
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.ENEMY_LIMIT__MAX_COUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.ENEMY_LIMIT__MAX_COUNT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnemyLimitAccess().getTypeEnemyTypeEnumRuleCall_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getEnemyLimitAccess().getMaxCountSIGNED_INTParserRuleCall_3_0(), semanticObject.getMaxCount());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GameConfiguration returns GameConfiguration
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         imports+=Import* 
	 *         difficulty=DifficultyConfig? 
	 *         opponents+=OpponentConfig* 
	 *         patrols+=PatrolConfig* 
	 *         lootTables+=LootTableConfig*
	 *     )
	 * </pre>
	 */
	protected void sequence_GameConfiguration(ISerializationContext context, GameConfiguration semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CharacterSpecifics returns GhostSpecifics
	 *     GhostSpecifics returns GhostSpecifics
	 *
	 * Constraint:
	 *     (attackDamage=INT? visibilityLevel=INT? nonTangibilityEnergy=DOUBLE?)
	 * </pre>
	 */
	protected void sequence_GhostSpecifics(ISerializationContext context, GhostSpecifics semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Import returns Import
	 *
	 * Constraint:
	 *     importURI=STRING
	 * </pre>
	 */
	protected void sequence_Import(ISerializationContext context, Import semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.IMPORT__IMPORT_URI) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.IMPORT__IMPORT_URI));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getImportAccess().getImportURISTRINGTerminalRuleCall_1_0(), semanticObject.getImportURI());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LootItemConfig returns LootItemConfig
	 *
	 * Constraint:
	 *     (name=ID type=LootItemTypeEnum value=INT weight=INT?)
	 * </pre>
	 */
	protected void sequence_LootItemConfig(ISerializationContext context, LootItemConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     LootTableConfig returns LootTableConfig
	 *
	 * Constraint:
	 *     (name=ID capacity=INT? items+=LootItemConfig+)
	 * </pre>
	 */
	protected void sequence_LootTableConfig(ISerializationContext context, LootTableConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     OpponentConfig returns OpponentConfig
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         type=CharacterTypeEnum 
	 *         displayName=STRING? 
	 *         health=SIGNED_INT? 
	 *         speed=DOUBLE? 
	 *         threatLevel=DOUBLE? 
	 *         enabled=BOOLEAN? 
	 *         behavior=BehaviorTypeEnum? 
	 *         characterSpecifics=CharacterSpecifics? 
	 *         patrolRef=[PatrolConfig|ID]? 
	 *         lootRef=[LootTableConfig|ID]?
	 *     )
	 * </pre>
	 */
	protected void sequence_OpponentConfig(ISerializationContext context, OpponentConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PatrolConfig returns PatrolConfig
	 *
	 * Constraint:
	 *     (name=ID visionRange=DOUBLE? zone=PatrolZoneConfig? waypoints+=Waypoint waypoints+=Waypoint*)
	 * </pre>
	 */
	protected void sequence_PatrolConfig(ISerializationContext context, PatrolConfig semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     PatrolZoneConfig returns PatrolZoneConfig
	 *
	 * Constraint:
	 *     (topLeftX=DOUBLE topLeftY=DOUBLE width=DOUBLE height=DOUBLE)
	 * </pre>
	 */
	protected void sequence_PatrolZoneConfig(ISerializationContext context, PatrolZoneConfig semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__TOP_LEFT_X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__TOP_LEFT_X));
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__TOP_LEFT_Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__TOP_LEFT_Y));
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__WIDTH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__WIDTH));
			if (transientValues.isValueTransient(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__HEIGHT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MazeDslPackage.Literals.PATROL_ZONE_CONFIG__HEIGHT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPatrolZoneConfigAccess().getTopLeftXDOUBLEParserRuleCall_4_0(), semanticObject.getTopLeftX());
		feeder.accept(grammarAccess.getPatrolZoneConfigAccess().getTopLeftYDOUBLEParserRuleCall_6_0(), semanticObject.getTopLeftY());
		feeder.accept(grammarAccess.getPatrolZoneConfigAccess().getWidthDOUBLEParserRuleCall_9_0(), semanticObject.getWidth());
		feeder.accept(grammarAccess.getPatrolZoneConfigAccess().getHeightDOUBLEParserRuleCall_11_0(), semanticObject.getHeight());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CharacterSpecifics returns RangedSpecifics
	 *     RangedSpecifics returns RangedSpecifics
	 *
	 * Constraint:
	 *     (
	 *         attackRange=DOUBLE? 
	 *         attackCooldown=INT? 
	 *         attackDamage=INT? 
	 *         projectileSpeed=DOUBLE? 
	 *         projectileType=ProjectileTypeEnum? 
	 *         splashRadius=DOUBLE?
	 *     )
	 * </pre>
	 */
	protected void sequence_RangedSpecifics(ISerializationContext context, RangedSpecifics semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Waypoint returns Waypoint
	 *
	 * Constraint:
	 *     (x=DOUBLE y=DOUBLE waitTime=INT?)
	 * </pre>
	 */
	protected void sequence_Waypoint(ISerializationContext context, Waypoint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     CharacterSpecifics returns ZombieSpecifics
	 *     ZombieSpecifics returns ZombieSpecifics
	 *
	 * Constraint:
	 *     (attackDamage=INT? infectionLevel=INT? resurrectionTime=INT?)
	 * </pre>
	 */
	protected void sequence_ZombieSpecifics(ISerializationContext context, ZombieSpecifics semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}


