/*
 * generated by Xtext
 */
package main.game.maze.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMazeDslScopeProvider extends DelegatingScopeProvider {
}
