/*
 * generated by Xtext 2.40.0
 */
package main.game.maze;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MazeCompRuntimeModule extends AbstractMazeCompRuntimeModule {
}
