/*
 * generated by Xtext 2.40.0
 */
package main.game.maze.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import main.game.maze.ide.contentassist.antlr.internal.InternalMazeCompParser;
import main.game.maze.services.MazeCompGrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MazeCompParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MazeCompGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MazeCompGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getEDoubleAccess().getAlternatives_4_0(), "rule__EDouble__Alternatives_4_0");
			builder.put(grammarAccess.getBehaviorTypeAccess().getAlternatives(), "rule__BehaviorType__Alternatives");
			builder.put(grammarAccess.getLootItemTypeAccess().getAlternatives(), "rule__LootItemType__Alternatives");
			builder.put(grammarAccess.getProjectileTypeAccess().getAlternatives(), "rule__ProjectileType__Alternatives");
			builder.put(grammarAccess.getMazeFileAccess().getGroup(), "rule__MazeFile__Group__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup(), "rule__EDouble__Group__0");
			builder.put(grammarAccess.getEDoubleAccess().getGroup_4(), "rule__EDouble__Group_4__0");
			builder.put(grammarAccess.getZombieAccess().getGroup(), "rule__Zombie__Group__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_2(), "rule__Zombie__Group_2__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_3(), "rule__Zombie__Group_3__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_10(), "rule__Zombie__Group_10__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_11(), "rule__Zombie__Group_11__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_12(), "rule__Zombie__Group_12__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_13(), "rule__Zombie__Group_13__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_14(), "rule__Zombie__Group_14__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_15(), "rule__Zombie__Group_15__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_22(), "rule__Zombie__Group_22__0");
			builder.put(grammarAccess.getZombieAccess().getGroup_23(), "rule__Zombie__Group_23__0");
			builder.put(grammarAccess.getGhostAccess().getGroup(), "rule__Ghost__Group__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_2(), "rule__Ghost__Group_2__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_3(), "rule__Ghost__Group_3__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_10(), "rule__Ghost__Group_10__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_11(), "rule__Ghost__Group_11__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_12(), "rule__Ghost__Group_12__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_13(), "rule__Ghost__Group_13__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_14(), "rule__Ghost__Group_14__0");
			builder.put(grammarAccess.getGhostAccess().getGroup_15(), "rule__Ghost__Group_15__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup(), "rule__PumpkinBomber__Group__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_2(), "rule__PumpkinBomber__Group_2__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_3(), "rule__PumpkinBomber__Group_3__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_10(), "rule__PumpkinBomber__Group_10__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_11(), "rule__PumpkinBomber__Group_11__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_12(), "rule__PumpkinBomber__Group_12__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_13(), "rule__PumpkinBomber__Group_13__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_14(), "rule__PumpkinBomber__Group_14__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_15(), "rule__PumpkinBomber__Group_15__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_30(), "rule__PumpkinBomber__Group_30__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_31(), "rule__PumpkinBomber__Group_31__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_32(), "rule__PumpkinBomber__Group_32__0");
			builder.put(grammarAccess.getPumpkinBomberAccess().getGroup_33(), "rule__PumpkinBomber__Group_33__0");
			builder.put(grammarAccess.getLootTableAccess().getGroup(), "rule__LootTable__Group__0");
			builder.put(grammarAccess.getLootTableAccess().getGroup_5(), "rule__LootTable__Group_5__0");
			builder.put(grammarAccess.getLootTableAccess().getGroup_7(), "rule__LootTable__Group_7__0");
			builder.put(grammarAccess.getLootTableAccess().getGroup_7_3(), "rule__LootTable__Group_7_3__0");
			builder.put(grammarAccess.getLootItemAccess().getGroup(), "rule__LootItem__Group__0");
			builder.put(grammarAccess.getLootItemAccess().getGroup_10(), "rule__LootItem__Group_10__0");
			builder.put(grammarAccess.getLootItemAccess().getGroup_12(), "rule__LootItem__Group_12__0");
			builder.put(grammarAccess.getMazeFileAccess().getZombiesAssignment_0(), "rule__MazeFile__ZombiesAssignment_0");
			builder.put(grammarAccess.getMazeFileAccess().getGhostsAssignment_1(), "rule__MazeFile__GhostsAssignment_1");
			builder.put(grammarAccess.getMazeFileAccess().getPumpkinBombersAssignment_2(), "rule__MazeFile__PumpkinBombersAssignment_2");
			builder.put(grammarAccess.getMazeFileAccess().getLootTablesAssignment_3(), "rule__MazeFile__LootTablesAssignment_3");
			builder.put(grammarAccess.getMazeFileAccess().getLootItemsAssignment_4(), "rule__MazeFile__LootItemsAssignment_4");
			builder.put(grammarAccess.getZombieAccess().getIdAssignment_2_1(), "rule__Zombie__IdAssignment_2_1");
			builder.put(grammarAccess.getZombieAccess().getDisplayNameAssignment_3_1(), "rule__Zombie__DisplayNameAssignment_3_1");
			builder.put(grammarAccess.getZombieAccess().getEnabledAssignment_5(), "rule__Zombie__EnabledAssignment_5");
			builder.put(grammarAccess.getZombieAccess().getHealthAssignment_7(), "rule__Zombie__HealthAssignment_7");
			builder.put(grammarAccess.getZombieAccess().getSpeedAssignment_9(), "rule__Zombie__SpeedAssignment_9");
			builder.put(grammarAccess.getZombieAccess().getImageBaseAssignment_10_1(), "rule__Zombie__ImageBaseAssignment_10_1");
			builder.put(grammarAccess.getZombieAccess().getImageTurnLeftAssignment_11_1(), "rule__Zombie__ImageTurnLeftAssignment_11_1");
			builder.put(grammarAccess.getZombieAccess().getImageTurnRightAssignment_12_1(), "rule__Zombie__ImageTurnRightAssignment_12_1");
			builder.put(grammarAccess.getZombieAccess().getImageTurnUpAssignment_13_1(), "rule__Zombie__ImageTurnUpAssignment_13_1");
			builder.put(grammarAccess.getZombieAccess().getImageTurnDownAssignment_14_1(), "rule__Zombie__ImageTurnDownAssignment_14_1");
			builder.put(grammarAccess.getZombieAccess().getBehaviorAssignment_15_1(), "rule__Zombie__BehaviorAssignment_15_1");
			builder.put(grammarAccess.getZombieAccess().getAttackDamageAssignment_17(), "rule__Zombie__AttackDamageAssignment_17");
			builder.put(grammarAccess.getZombieAccess().getInfectionLevelAssignment_19(), "rule__Zombie__InfectionLevelAssignment_19");
			builder.put(grammarAccess.getZombieAccess().getResurrectionTimeAssignment_21(), "rule__Zombie__ResurrectionTimeAssignment_21");
			builder.put(grammarAccess.getZombieAccess().getTouchSoundAssignment_22_1(), "rule__Zombie__TouchSoundAssignment_22_1");
			builder.put(grammarAccess.getZombieAccess().getZombieLootTableAssignment_23_1(), "rule__Zombie__ZombieLootTableAssignment_23_1");
			builder.put(grammarAccess.getGhostAccess().getIdAssignment_2_1(), "rule__Ghost__IdAssignment_2_1");
			builder.put(grammarAccess.getGhostAccess().getDisplayNameAssignment_3_1(), "rule__Ghost__DisplayNameAssignment_3_1");
			builder.put(grammarAccess.getGhostAccess().getEnabledAssignment_5(), "rule__Ghost__EnabledAssignment_5");
			builder.put(grammarAccess.getGhostAccess().getHealthAssignment_7(), "rule__Ghost__HealthAssignment_7");
			builder.put(grammarAccess.getGhostAccess().getSpeedAssignment_9(), "rule__Ghost__SpeedAssignment_9");
			builder.put(grammarAccess.getGhostAccess().getImageBaseAssignment_10_1(), "rule__Ghost__ImageBaseAssignment_10_1");
			builder.put(grammarAccess.getGhostAccess().getImageTurnLeftAssignment_11_1(), "rule__Ghost__ImageTurnLeftAssignment_11_1");
			builder.put(grammarAccess.getGhostAccess().getImageTurnRightAssignment_12_1(), "rule__Ghost__ImageTurnRightAssignment_12_1");
			builder.put(grammarAccess.getGhostAccess().getImageTurnUpAssignment_13_1(), "rule__Ghost__ImageTurnUpAssignment_13_1");
			builder.put(grammarAccess.getGhostAccess().getImageTurnDownAssignment_14_1(), "rule__Ghost__ImageTurnDownAssignment_14_1");
			builder.put(grammarAccess.getGhostAccess().getBehaviorAssignment_15_1(), "rule__Ghost__BehaviorAssignment_15_1");
			builder.put(grammarAccess.getGhostAccess().getAttackDamageAssignment_17(), "rule__Ghost__AttackDamageAssignment_17");
			builder.put(grammarAccess.getGhostAccess().getVisibilityLevelAssignment_19(), "rule__Ghost__VisibilityLevelAssignment_19");
			builder.put(grammarAccess.getGhostAccess().getNonTangibilityEnergyAssignment_21(), "rule__Ghost__NonTangibilityEnergyAssignment_21");
			builder.put(grammarAccess.getPumpkinBomberAccess().getIdAssignment_2_1(), "rule__PumpkinBomber__IdAssignment_2_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getDisplayNameAssignment_3_1(), "rule__PumpkinBomber__DisplayNameAssignment_3_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getEnabledAssignment_5(), "rule__PumpkinBomber__EnabledAssignment_5");
			builder.put(grammarAccess.getPumpkinBomberAccess().getHealthAssignment_7(), "rule__PumpkinBomber__HealthAssignment_7");
			builder.put(grammarAccess.getPumpkinBomberAccess().getSpeedAssignment_9(), "rule__PumpkinBomber__SpeedAssignment_9");
			builder.put(grammarAccess.getPumpkinBomberAccess().getImageBaseAssignment_10_1(), "rule__PumpkinBomber__ImageBaseAssignment_10_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getImageTurnLeftAssignment_11_1(), "rule__PumpkinBomber__ImageTurnLeftAssignment_11_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getImageTurnRightAssignment_12_1(), "rule__PumpkinBomber__ImageTurnRightAssignment_12_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getImageTurnUpAssignment_13_1(), "rule__PumpkinBomber__ImageTurnUpAssignment_13_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getImageTurnDownAssignment_14_1(), "rule__PumpkinBomber__ImageTurnDownAssignment_14_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getBehaviorAssignment_15_1(), "rule__PumpkinBomber__BehaviorAssignment_15_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getAttackRangeAssignment_17(), "rule__PumpkinBomber__AttackRangeAssignment_17");
			builder.put(grammarAccess.getPumpkinBomberAccess().getAttackCooldownMsAssignment_19(), "rule__PumpkinBomber__AttackCooldownMsAssignment_19");
			builder.put(grammarAccess.getPumpkinBomberAccess().getAttackDamageAssignment_21(), "rule__PumpkinBomber__AttackDamageAssignment_21");
			builder.put(grammarAccess.getPumpkinBomberAccess().getProjectileSpeedAssignment_23(), "rule__PumpkinBomber__ProjectileSpeedAssignment_23");
			builder.put(grammarAccess.getPumpkinBomberAccess().getProjectileTypeAssignment_25(), "rule__PumpkinBomber__ProjectileTypeAssignment_25");
			builder.put(grammarAccess.getPumpkinBomberAccess().getSplashRadiusAssignment_27(), "rule__PumpkinBomber__SplashRadiusAssignment_27");
			builder.put(grammarAccess.getPumpkinBomberAccess().getArcHeightAssignment_29(), "rule__PumpkinBomber__ArcHeightAssignment_29");
			builder.put(grammarAccess.getPumpkinBomberAccess().getProjectileImageAssignment_30_1(), "rule__PumpkinBomber__ProjectileImageAssignment_30_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getExplosionImageAssignment_31_1(), "rule__PumpkinBomber__ExplosionImageAssignment_31_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getExplosionSoundAssignment_32_1(), "rule__PumpkinBomber__ExplosionSoundAssignment_32_1");
			builder.put(grammarAccess.getPumpkinBomberAccess().getThrowSoundAssignment_33_1(), "rule__PumpkinBomber__ThrowSoundAssignment_33_1");
			builder.put(grammarAccess.getLootTableAccess().getWeightCapacityAssignment_4(), "rule__LootTable__WeightCapacityAssignment_4");
			builder.put(grammarAccess.getLootTableAccess().getWeightCapacityAssignment_5_1(), "rule__LootTable__WeightCapacityAssignment_5_1");
			builder.put(grammarAccess.getLootTableAccess().getItemsAssignment_7_2(), "rule__LootTable__ItemsAssignment_7_2");
			builder.put(grammarAccess.getLootTableAccess().getItemsAssignment_7_3_1(), "rule__LootTable__ItemsAssignment_7_3_1");
			builder.put(grammarAccess.getLootItemAccess().getNameAssignment_1(), "rule__LootItem__NameAssignment_1");
			builder.put(grammarAccess.getLootItemAccess().getTypeAssignment_4(), "rule__LootItem__TypeAssignment_4");
			builder.put(grammarAccess.getLootItemAccess().getValueAssignment_6(), "rule__LootItem__ValueAssignment_6");
			builder.put(grammarAccess.getLootItemAccess().getWeightAssignment_9(), "rule__LootItem__WeightAssignment_9");
			builder.put(grammarAccess.getLootItemAccess().getWeightAssignment_10_1(), "rule__LootItem__WeightAssignment_10_1");
			builder.put(grammarAccess.getLootItemAccess().getGraphicBaseAssignment_12_1(), "rule__LootItem__GraphicBaseAssignment_12_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MazeCompGrammarAccess grammarAccess;

	@Override
	protected InternalMazeCompParser createParser() {
		InternalMazeCompParser result = new InternalMazeCompParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MazeCompGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MazeCompGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
