/*
 * generated by Xtext 2.40.0
 */
package main.game.maze.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMazeCompValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(main.game.maze.mazecomp.MazecompPackage.eINSTANCE);
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://main.game.maze/opponents"));
		return result;
	}
}
