<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="opponents" nsURI="http://main.game.maze/opponents" nsPrefix="opp">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value=""/>
    <details key="settingDelegates" value=""/>
    <details key="validationDelegates" value=""/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OpponentModel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="validateMaxThreat" value="self.characterTypes->collect(ct | ct.effectiveThreat)->sum() &lt;= self.maxThreat"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validateMaxThreat"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characterTypes" lowerBound="1"
        upperBound="-1" eType="#//CharacterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxThreat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterType" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threatLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveThreat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" defaultValueLiteral="1"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombie.png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageTurnLeft" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombie-left.png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageTurnRight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombie-right.png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageTurnUp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombie-up.png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImageTurnDown" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombie-up.png"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTangible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Zombie" eSuperTypes="#//CharacterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" eType="#//BehaviorType"
        defaultValueLiteral="WANDER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="zombieLootTable" eType="#//LootTable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infectionLevel" upperBound="10"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resurrectionTime" upperBound="180"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="touchSound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="/main/game/maze/zombieScream.mp3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BehaviorType">
    <eLiterals name="PASSIVE" literal="PASSIVE"/>
    <eLiterals name="WANDER" value="1"/>
    <eLiterals name="AGGRESSIVE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LootTable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//LootItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weightCapacity" lowerBound="1"
        upperBound="100" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LootItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//LootItemType"
        defaultValueLiteral="FOOD"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        upperBound="10" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="graphicBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LootItemType">
    <eLiterals name="FOOD"/>
    <eLiterals name="BOMB" value="1"/>
    <eLiterals name="TRAP" value="2"/>
    <eLiterals name="WEAPON" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ghost" eSuperTypes="#//CharacterType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attackDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" eType="#//BehaviorType"
        defaultValueLiteral="WANDER"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibilityLevel" upperBound="100"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonTangibilityEnergy" upperBound="100"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="100"/>
  </eClassifiers>
</ecore:EPackage>
