/*
 * generated by Xtext 2.40.0
 */
package main.game.maze.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MazeCompUiModule extends AbstractMazeCompUiModule {

	public MazeCompUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
