/*
 * generated by Xtext
 */
package main.game.maze.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MazeDslStandaloneSetup extends MazeDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MazeDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
