/*
 * generated by Xtext
 */
package main.game.maze.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MazeDslRuntimeModule extends AbstractMazeDslRuntimeModule {
}
