/*
 * generated by Xtext
 */
package main.game.maze.dsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MazeDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class GameConfigurationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.GameConfiguration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cImportsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cImportsImportParserRuleCall_3_0 = (RuleCall)cImportsAssignment_3.eContents().get(0);
		private final Assignment cDifficultyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDifficultyDifficultyConfigParserRuleCall_4_0 = (RuleCall)cDifficultyAssignment_4.eContents().get(0);
		private final Assignment cOpponentsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cOpponentsOpponentConfigParserRuleCall_5_0 = (RuleCall)cOpponentsAssignment_5.eContents().get(0);
		private final Assignment cPatrolsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPatrolsPatrolConfigParserRuleCall_6_0 = (RuleCall)cPatrolsAssignment_6.eContents().get(0);
		private final Assignment cLootTablesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLootTablesLootTableConfigParserRuleCall_7_0 = (RuleCall)cLootTablesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		///*
		// * Root element - A game configuration containing all game elements
		// */
		//GameConfiguration:
		//    'game' name=ID '{'
		//        (imports+=Import)*
		//        (difficulty=DifficultyConfig)?
		//        (opponents+=OpponentConfig)*
		//        (patrols+=PatrolConfig)*
		//        (lootTables+=LootTableConfig)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'game' name=ID '{'
		//    (imports+=Import)*
		//    (difficulty=DifficultyConfig)?
		//    (opponents+=OpponentConfig)*
		//    (patrols+=PatrolConfig)*
		//    (lootTables+=LootTableConfig)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'game'
		public Keyword getGameKeyword_0() { return cGameKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//(imports+=Import)*
		public Assignment getImportsAssignment_3() { return cImportsAssignment_3; }
		
		//Import
		public RuleCall getImportsImportParserRuleCall_3_0() { return cImportsImportParserRuleCall_3_0; }
		
		//(difficulty=DifficultyConfig)?
		public Assignment getDifficultyAssignment_4() { return cDifficultyAssignment_4; }
		
		//DifficultyConfig
		public RuleCall getDifficultyDifficultyConfigParserRuleCall_4_0() { return cDifficultyDifficultyConfigParserRuleCall_4_0; }
		
		//(opponents+=OpponentConfig)*
		public Assignment getOpponentsAssignment_5() { return cOpponentsAssignment_5; }
		
		//OpponentConfig
		public RuleCall getOpponentsOpponentConfigParserRuleCall_5_0() { return cOpponentsOpponentConfigParserRuleCall_5_0; }
		
		//(patrols+=PatrolConfig)*
		public Assignment getPatrolsAssignment_6() { return cPatrolsAssignment_6; }
		
		//PatrolConfig
		public RuleCall getPatrolsPatrolConfigParserRuleCall_6_0() { return cPatrolsPatrolConfigParserRuleCall_6_0; }
		
		//(lootTables+=LootTableConfig)*
		public Assignment getLootTablesAssignment_7() { return cLootTablesAssignment_7; }
		
		//LootTableConfig
		public RuleCall getLootTablesLootTableConfigParserRuleCall_7_0() { return cLootTablesLootTableConfigParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportURIAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportURISTRINGTerminalRuleCall_1_0 = (RuleCall)cImportURIAssignment_1.eContents().get(0);
		
		///*
		// * Import statement for referencing external XMI files
		// */
		//Import:
		//    'import' importURI=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'import' importURI=STRING
		public Group getGroup() { return cGroup; }
		
		//'import'
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }
		
		//importURI=STRING
		public Assignment getImportURIAssignment_1() { return cImportURIAssignment_1; }
		
		//STRING
		public RuleCall getImportURISTRINGTerminalRuleCall_1_0() { return cImportURISTRINGTerminalRuleCall_1_0; }
	}
	public class DifficultyConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.DifficultyConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDifficultyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLevelKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLevelAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLevelDifficultyLevelEnumRuleCall_3_0 = (RuleCall)cLevelAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInstantDeathKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInstantDeathAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final Keyword cInstantDeathTrueKeyword_4_1_0 = (Keyword)cInstantDeathAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSpeedMultiplierKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSpeedMultiplierAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cSpeedMultiplierDOUBLEParserRuleCall_5_1_0 = (RuleCall)cSpeedMultiplierAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDamageMultiplierKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDamageMultiplierAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDamageMultiplierDOUBLEParserRuleCall_6_1_0 = (RuleCall)cDamageMultiplierAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cMaxThreatKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cMaxThreatAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cMaxThreatSIGNED_INTParserRuleCall_7_1_0 = (RuleCall)cMaxThreatAssignment_7_1.eContents().get(0);
		private final Assignment cEnemyLimitsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEnemyLimitsEnemyLimitParserRuleCall_8_0 = (RuleCall)cEnemyLimitsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		///*
		// * Difficulty configuration section
		// */
		//DifficultyConfig:
		//    'difficulty' '{'
		//        'level' level=DifficultyLevel
		//        ('instantDeath' instantDeath?='true')?
		//        ('speedMultiplier' speedMultiplier=DOUBLE)?
		//        ('damageMultiplier' damageMultiplier=DOUBLE)?
		//        ('maxThreat' maxThreat=SIGNED_INT)?
		//        (enemyLimits+=EnemyLimit)*
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'difficulty' '{'
		//    'level' level=DifficultyLevel
		//    ('instantDeath' instantDeath?='true')?
		//    ('speedMultiplier' speedMultiplier=DOUBLE)?
		//    ('damageMultiplier' damageMultiplier=DOUBLE)?
		//    ('maxThreat' maxThreat=SIGNED_INT)?
		//    (enemyLimits+=EnemyLimit)*
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'difficulty'
		public Keyword getDifficultyKeyword_0() { return cDifficultyKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'level'
		public Keyword getLevelKeyword_2() { return cLevelKeyword_2; }
		
		//level=DifficultyLevel
		public Assignment getLevelAssignment_3() { return cLevelAssignment_3; }
		
		//DifficultyLevel
		public RuleCall getLevelDifficultyLevelEnumRuleCall_3_0() { return cLevelDifficultyLevelEnumRuleCall_3_0; }
		
		//('instantDeath' instantDeath?='true')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'instantDeath'
		public Keyword getInstantDeathKeyword_4_0() { return cInstantDeathKeyword_4_0; }
		
		//instantDeath?='true'
		public Assignment getInstantDeathAssignment_4_1() { return cInstantDeathAssignment_4_1; }
		
		//'true'
		public Keyword getInstantDeathTrueKeyword_4_1_0() { return cInstantDeathTrueKeyword_4_1_0; }
		
		//('speedMultiplier' speedMultiplier=DOUBLE)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'speedMultiplier'
		public Keyword getSpeedMultiplierKeyword_5_0() { return cSpeedMultiplierKeyword_5_0; }
		
		//speedMultiplier=DOUBLE
		public Assignment getSpeedMultiplierAssignment_5_1() { return cSpeedMultiplierAssignment_5_1; }
		
		//DOUBLE
		public RuleCall getSpeedMultiplierDOUBLEParserRuleCall_5_1_0() { return cSpeedMultiplierDOUBLEParserRuleCall_5_1_0; }
		
		//('damageMultiplier' damageMultiplier=DOUBLE)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'damageMultiplier'
		public Keyword getDamageMultiplierKeyword_6_0() { return cDamageMultiplierKeyword_6_0; }
		
		//damageMultiplier=DOUBLE
		public Assignment getDamageMultiplierAssignment_6_1() { return cDamageMultiplierAssignment_6_1; }
		
		//DOUBLE
		public RuleCall getDamageMultiplierDOUBLEParserRuleCall_6_1_0() { return cDamageMultiplierDOUBLEParserRuleCall_6_1_0; }
		
		//('maxThreat' maxThreat=SIGNED_INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'maxThreat'
		public Keyword getMaxThreatKeyword_7_0() { return cMaxThreatKeyword_7_0; }
		
		//maxThreat=SIGNED_INT
		public Assignment getMaxThreatAssignment_7_1() { return cMaxThreatAssignment_7_1; }
		
		//SIGNED_INT
		public RuleCall getMaxThreatSIGNED_INTParserRuleCall_7_1_0() { return cMaxThreatSIGNED_INTParserRuleCall_7_1_0; }
		
		//(enemyLimits+=EnemyLimit)*
		public Assignment getEnemyLimitsAssignment_8() { return cEnemyLimitsAssignment_8; }
		
		//EnemyLimit
		public RuleCall getEnemyLimitsEnemyLimitParserRuleCall_8_0() { return cEnemyLimitsEnemyLimitParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EnemyLimitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.EnemyLimit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLimitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTypeEnemyTypeEnumRuleCall_1_0 = (RuleCall)cTypeAssignment_1.eContents().get(0);
		private final Keyword cMaxKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMaxCountAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMaxCountSIGNED_INTParserRuleCall_3_0 = (RuleCall)cMaxCountAssignment_3.eContents().get(0);
		
		///*
		// * Enemy count limits per type
		// */
		//EnemyLimit:
		//    'limit' type=EnemyType 'max' maxCount=SIGNED_INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'limit' type=EnemyType 'max' maxCount=SIGNED_INT
		public Group getGroup() { return cGroup; }
		
		//'limit'
		public Keyword getLimitKeyword_0() { return cLimitKeyword_0; }
		
		//type=EnemyType
		public Assignment getTypeAssignment_1() { return cTypeAssignment_1; }
		
		//EnemyType
		public RuleCall getTypeEnemyTypeEnumRuleCall_1_0() { return cTypeEnemyTypeEnumRuleCall_1_0; }
		
		//'max'
		public Keyword getMaxKeyword_2() { return cMaxKeyword_2; }
		
		//maxCount=SIGNED_INT
		public Assignment getMaxCountAssignment_3() { return cMaxCountAssignment_3; }
		
		//SIGNED_INT
		public RuleCall getMaxCountSIGNED_INTParserRuleCall_3_0() { return cMaxCountSIGNED_INTParserRuleCall_3_0; }
	}
	public class OpponentConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.OpponentConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOpponentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeCharacterTypeEnumEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDisplayNameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDisplayNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDisplayNameSTRINGTerminalRuleCall_5_1_0 = (RuleCall)cDisplayNameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cHealthKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cHealthAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cHealthSIGNED_INTParserRuleCall_6_1_0 = (RuleCall)cHealthAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cSpeedKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSpeedAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSpeedDOUBLEParserRuleCall_7_1_0 = (RuleCall)cSpeedAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cThreatLevelKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cThreatLevelAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cThreatLevelDOUBLEParserRuleCall_8_1_0 = (RuleCall)cThreatLevelAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cEnabledKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cEnabledAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cEnabledBOOLEANParserRuleCall_9_1_0 = (RuleCall)cEnabledAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cBehaviorKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cBehaviorAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cBehaviorBehaviorTypeEnumEnumRuleCall_10_1_0 = (RuleCall)cBehaviorAssignment_10_1.eContents().get(0);
		private final Assignment cCharacterSpecificsAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cCharacterSpecificsCharacterSpecificsParserRuleCall_11_0 = (RuleCall)cCharacterSpecificsAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cPatrolKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Assignment cPatrolRefAssignment_12_1 = (Assignment)cGroup_12.eContents().get(1);
		private final CrossReference cPatrolRefPatrolConfigCrossReference_12_1_0 = (CrossReference)cPatrolRefAssignment_12_1.eContents().get(0);
		private final RuleCall cPatrolRefPatrolConfigIDTerminalRuleCall_12_1_0_1 = (RuleCall)cPatrolRefPatrolConfigCrossReference_12_1_0.eContents().get(1);
		private final Group cGroup_13 = (Group)cGroup.eContents().get(13);
		private final Keyword cLootKeyword_13_0 = (Keyword)cGroup_13.eContents().get(0);
		private final Assignment cLootRefAssignment_13_1 = (Assignment)cGroup_13.eContents().get(1);
		private final CrossReference cLootRefLootTableConfigCrossReference_13_1_0 = (CrossReference)cLootRefAssignment_13_1.eContents().get(0);
		private final RuleCall cLootRefLootTableConfigIDTerminalRuleCall_13_1_0_1 = (RuleCall)cLootRefLootTableConfigCrossReference_13_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		///*
		// * Opponent/Enemy configuration
		// */
		//OpponentConfig:
		//    'opponent' name=ID '{'
		//        'type' type=CharacterTypeEnum
		//        ('displayName' displayName=STRING)?
		//        ('health' health=SIGNED_INT)?
		//        ('speed' speed=DOUBLE)?
		//        ('threatLevel' threatLevel=DOUBLE)?
		//        ('enabled' enabled=BOOLEAN)?
		//        ('behavior' behavior=BehaviorTypeEnum)?
		//        (characterSpecifics=CharacterSpecifics)?
		//        ('patrol' patrolRef=[PatrolConfig])?
		//        ('loot' lootRef=[LootTableConfig])?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'opponent' name=ID '{'
		//    'type' type=CharacterTypeEnum
		//    ('displayName' displayName=STRING)?
		//    ('health' health=SIGNED_INT)?
		//    ('speed' speed=DOUBLE)?
		//    ('threatLevel' threatLevel=DOUBLE)?
		//    ('enabled' enabled=BOOLEAN)?
		//    ('behavior' behavior=BehaviorTypeEnum)?
		//    (characterSpecifics=CharacterSpecifics)?
		//    ('patrol' patrolRef=[PatrolConfig])?
		//    ('loot' lootRef=[LootTableConfig])?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'opponent'
		public Keyword getOpponentKeyword_0() { return cOpponentKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=CharacterTypeEnum
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//CharacterTypeEnum
		public RuleCall getTypeCharacterTypeEnumEnumRuleCall_4_0() { return cTypeCharacterTypeEnumEnumRuleCall_4_0; }
		
		//('displayName' displayName=STRING)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'displayName'
		public Keyword getDisplayNameKeyword_5_0() { return cDisplayNameKeyword_5_0; }
		
		//displayName=STRING
		public Assignment getDisplayNameAssignment_5_1() { return cDisplayNameAssignment_5_1; }
		
		//STRING
		public RuleCall getDisplayNameSTRINGTerminalRuleCall_5_1_0() { return cDisplayNameSTRINGTerminalRuleCall_5_1_0; }
		
		//('health' health=SIGNED_INT)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'health'
		public Keyword getHealthKeyword_6_0() { return cHealthKeyword_6_0; }
		
		//health=SIGNED_INT
		public Assignment getHealthAssignment_6_1() { return cHealthAssignment_6_1; }
		
		//SIGNED_INT
		public RuleCall getHealthSIGNED_INTParserRuleCall_6_1_0() { return cHealthSIGNED_INTParserRuleCall_6_1_0; }
		
		//('speed' speed=DOUBLE)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'speed'
		public Keyword getSpeedKeyword_7_0() { return cSpeedKeyword_7_0; }
		
		//speed=DOUBLE
		public Assignment getSpeedAssignment_7_1() { return cSpeedAssignment_7_1; }
		
		//DOUBLE
		public RuleCall getSpeedDOUBLEParserRuleCall_7_1_0() { return cSpeedDOUBLEParserRuleCall_7_1_0; }
		
		//('threatLevel' threatLevel=DOUBLE)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'threatLevel'
		public Keyword getThreatLevelKeyword_8_0() { return cThreatLevelKeyword_8_0; }
		
		//threatLevel=DOUBLE
		public Assignment getThreatLevelAssignment_8_1() { return cThreatLevelAssignment_8_1; }
		
		//DOUBLE
		public RuleCall getThreatLevelDOUBLEParserRuleCall_8_1_0() { return cThreatLevelDOUBLEParserRuleCall_8_1_0; }
		
		//('enabled' enabled=BOOLEAN)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'enabled'
		public Keyword getEnabledKeyword_9_0() { return cEnabledKeyword_9_0; }
		
		//enabled=BOOLEAN
		public Assignment getEnabledAssignment_9_1() { return cEnabledAssignment_9_1; }
		
		//BOOLEAN
		public RuleCall getEnabledBOOLEANParserRuleCall_9_1_0() { return cEnabledBOOLEANParserRuleCall_9_1_0; }
		
		//('behavior' behavior=BehaviorTypeEnum)?
		public Group getGroup_10() { return cGroup_10; }
		
		//'behavior'
		public Keyword getBehaviorKeyword_10_0() { return cBehaviorKeyword_10_0; }
		
		//behavior=BehaviorTypeEnum
		public Assignment getBehaviorAssignment_10_1() { return cBehaviorAssignment_10_1; }
		
		//BehaviorTypeEnum
		public RuleCall getBehaviorBehaviorTypeEnumEnumRuleCall_10_1_0() { return cBehaviorBehaviorTypeEnumEnumRuleCall_10_1_0; }
		
		//(characterSpecifics=CharacterSpecifics)?
		public Assignment getCharacterSpecificsAssignment_11() { return cCharacterSpecificsAssignment_11; }
		
		//CharacterSpecifics
		public RuleCall getCharacterSpecificsCharacterSpecificsParserRuleCall_11_0() { return cCharacterSpecificsCharacterSpecificsParserRuleCall_11_0; }
		
		//('patrol' patrolRef=[PatrolConfig])?
		public Group getGroup_12() { return cGroup_12; }
		
		//'patrol'
		public Keyword getPatrolKeyword_12_0() { return cPatrolKeyword_12_0; }
		
		//patrolRef=[PatrolConfig]
		public Assignment getPatrolRefAssignment_12_1() { return cPatrolRefAssignment_12_1; }
		
		//[PatrolConfig]
		public CrossReference getPatrolRefPatrolConfigCrossReference_12_1_0() { return cPatrolRefPatrolConfigCrossReference_12_1_0; }
		
		//ID
		public RuleCall getPatrolRefPatrolConfigIDTerminalRuleCall_12_1_0_1() { return cPatrolRefPatrolConfigIDTerminalRuleCall_12_1_0_1; }
		
		//('loot' lootRef=[LootTableConfig])?
		public Group getGroup_13() { return cGroup_13; }
		
		//'loot'
		public Keyword getLootKeyword_13_0() { return cLootKeyword_13_0; }
		
		//lootRef=[LootTableConfig]
		public Assignment getLootRefAssignment_13_1() { return cLootRefAssignment_13_1; }
		
		//[LootTableConfig]
		public CrossReference getLootRefLootTableConfigCrossReference_13_1_0() { return cLootRefLootTableConfigCrossReference_13_1_0; }
		
		//ID
		public RuleCall getLootRefLootTableConfigIDTerminalRuleCall_13_1_0_1() { return cLootRefLootTableConfigIDTerminalRuleCall_13_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_14() { return cRightCurlyBracketKeyword_14; }
	}
	public class CharacterSpecificsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.CharacterSpecifics");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cZombieSpecificsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cGhostSpecificsParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRangedSpecificsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		///*
		// * Character-specific attributes (zombie, ghost, or ranged enemy)
		// */
		//CharacterSpecifics:
		//    ZombieSpecifics | GhostSpecifics | RangedSpecifics
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//ZombieSpecifics | GhostSpecifics | RangedSpecifics
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ZombieSpecifics
		public RuleCall getZombieSpecificsParserRuleCall_0() { return cZombieSpecificsParserRuleCall_0; }
		
		//GhostSpecifics
		public RuleCall getGhostSpecificsParserRuleCall_1() { return cGhostSpecificsParserRuleCall_1; }
		
		//RangedSpecifics
		public RuleCall getRangedSpecificsParserRuleCall_2() { return cRangedSpecificsParserRuleCall_2; }
	}
	public class ZombieSpecificsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.ZombieSpecifics");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cZombieSpecificsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cZombieStatsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAttackDamageKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAttackDamageAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAttackDamageINTTerminalRuleCall_3_1_0 = (RuleCall)cAttackDamageAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cInfectionLevelKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cInfectionLevelAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cInfectionLevelINTTerminalRuleCall_4_1_0 = (RuleCall)cInfectionLevelAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cResurrectionTimeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cResurrectionTimeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cResurrectionTimeINTTerminalRuleCall_5_1_0 = (RuleCall)cResurrectionTimeAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//ZombieSpecifics:
		//    {ZombieSpecifics}
		//    'zombie-stats' '{'
		//        ('attackDamage' attackDamage=INT)?
		//        ('infectionLevel' infectionLevel=INT)?
		//        ('resurrectionTime' resurrectionTime=INT)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{ZombieSpecifics}
		//'zombie-stats' '{'
		//    ('attackDamage' attackDamage=INT)?
		//    ('infectionLevel' infectionLevel=INT)?
		//    ('resurrectionTime' resurrectionTime=INT)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{ZombieSpecifics}
		public Action getZombieSpecificsAction_0() { return cZombieSpecificsAction_0; }
		
		//'zombie-stats'
		public Keyword getZombieStatsKeyword_1() { return cZombieStatsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('attackDamage' attackDamage=INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'attackDamage'
		public Keyword getAttackDamageKeyword_3_0() { return cAttackDamageKeyword_3_0; }
		
		//attackDamage=INT
		public Assignment getAttackDamageAssignment_3_1() { return cAttackDamageAssignment_3_1; }
		
		//INT
		public RuleCall getAttackDamageINTTerminalRuleCall_3_1_0() { return cAttackDamageINTTerminalRuleCall_3_1_0; }
		
		//('infectionLevel' infectionLevel=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'infectionLevel'
		public Keyword getInfectionLevelKeyword_4_0() { return cInfectionLevelKeyword_4_0; }
		
		//infectionLevel=INT
		public Assignment getInfectionLevelAssignment_4_1() { return cInfectionLevelAssignment_4_1; }
		
		//INT
		public RuleCall getInfectionLevelINTTerminalRuleCall_4_1_0() { return cInfectionLevelINTTerminalRuleCall_4_1_0; }
		
		//('resurrectionTime' resurrectionTime=INT)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'resurrectionTime'
		public Keyword getResurrectionTimeKeyword_5_0() { return cResurrectionTimeKeyword_5_0; }
		
		//resurrectionTime=INT
		public Assignment getResurrectionTimeAssignment_5_1() { return cResurrectionTimeAssignment_5_1; }
		
		//INT
		public RuleCall getResurrectionTimeINTTerminalRuleCall_5_1_0() { return cResurrectionTimeINTTerminalRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class GhostSpecificsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.GhostSpecifics");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cGhostSpecificsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cGhostStatsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAttackDamageKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAttackDamageAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAttackDamageINTTerminalRuleCall_3_1_0 = (RuleCall)cAttackDamageAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVisibilityLevelKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVisibilityLevelAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVisibilityLevelINTTerminalRuleCall_4_1_0 = (RuleCall)cVisibilityLevelAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cNonTangibilityEnergyKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cNonTangibilityEnergyAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNonTangibilityEnergyDOUBLEParserRuleCall_5_1_0 = (RuleCall)cNonTangibilityEnergyAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//GhostSpecifics:
		//    {GhostSpecifics}
		//    'ghost-stats' '{'
		//        ('attackDamage' attackDamage=INT)?
		//        ('visibilityLevel' visibilityLevel=INT)?
		//        ('nonTangibilityEnergy' nonTangibilityEnergy=DOUBLE)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{GhostSpecifics}
		//'ghost-stats' '{'
		//    ('attackDamage' attackDamage=INT)?
		//    ('visibilityLevel' visibilityLevel=INT)?
		//    ('nonTangibilityEnergy' nonTangibilityEnergy=DOUBLE)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{GhostSpecifics}
		public Action getGhostSpecificsAction_0() { return cGhostSpecificsAction_0; }
		
		//'ghost-stats'
		public Keyword getGhostStatsKeyword_1() { return cGhostStatsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('attackDamage' attackDamage=INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'attackDamage'
		public Keyword getAttackDamageKeyword_3_0() { return cAttackDamageKeyword_3_0; }
		
		//attackDamage=INT
		public Assignment getAttackDamageAssignment_3_1() { return cAttackDamageAssignment_3_1; }
		
		//INT
		public RuleCall getAttackDamageINTTerminalRuleCall_3_1_0() { return cAttackDamageINTTerminalRuleCall_3_1_0; }
		
		//('visibilityLevel' visibilityLevel=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'visibilityLevel'
		public Keyword getVisibilityLevelKeyword_4_0() { return cVisibilityLevelKeyword_4_0; }
		
		//visibilityLevel=INT
		public Assignment getVisibilityLevelAssignment_4_1() { return cVisibilityLevelAssignment_4_1; }
		
		//INT
		public RuleCall getVisibilityLevelINTTerminalRuleCall_4_1_0() { return cVisibilityLevelINTTerminalRuleCall_4_1_0; }
		
		//('nonTangibilityEnergy' nonTangibilityEnergy=DOUBLE)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'nonTangibilityEnergy'
		public Keyword getNonTangibilityEnergyKeyword_5_0() { return cNonTangibilityEnergyKeyword_5_0; }
		
		//nonTangibilityEnergy=DOUBLE
		public Assignment getNonTangibilityEnergyAssignment_5_1() { return cNonTangibilityEnergyAssignment_5_1; }
		
		//DOUBLE
		public RuleCall getNonTangibilityEnergyDOUBLEParserRuleCall_5_1_0() { return cNonTangibilityEnergyDOUBLEParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class RangedSpecificsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.RangedSpecifics");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRangedSpecificsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRangedStatsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAttackRangeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAttackRangeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAttackRangeDOUBLEParserRuleCall_3_1_0 = (RuleCall)cAttackRangeAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAttackCooldownKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cAttackCooldownAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cAttackCooldownINTTerminalRuleCall_4_1_0 = (RuleCall)cAttackCooldownAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAttackDamageKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cAttackDamageAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cAttackDamageINTTerminalRuleCall_5_1_0 = (RuleCall)cAttackDamageAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cProjectileSpeedKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cProjectileSpeedAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cProjectileSpeedDOUBLEParserRuleCall_6_1_0 = (RuleCall)cProjectileSpeedAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cProjectileTypeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cProjectileTypeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cProjectileTypeProjectileTypeEnumEnumRuleCall_7_1_0 = (RuleCall)cProjectileTypeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cSplashRadiusKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cSplashRadiusAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cSplashRadiusDOUBLEParserRuleCall_8_1_0 = (RuleCall)cSplashRadiusAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//RangedSpecifics:
		//    {RangedSpecifics}
		//    'ranged-stats' '{'
		//        ('attackRange' attackRange=DOUBLE)?
		//        ('attackCooldown' attackCooldown=INT)?
		//        ('attackDamage' attackDamage=INT)?
		//        ('projectileSpeed' projectileSpeed=DOUBLE)?
		//        ('projectileType' projectileType=ProjectileTypeEnum)?
		//        ('splashRadius' splashRadius=DOUBLE)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//{RangedSpecifics}
		//'ranged-stats' '{'
		//    ('attackRange' attackRange=DOUBLE)?
		//    ('attackCooldown' attackCooldown=INT)?
		//    ('attackDamage' attackDamage=INT)?
		//    ('projectileSpeed' projectileSpeed=DOUBLE)?
		//    ('projectileType' projectileType=ProjectileTypeEnum)?
		//    ('splashRadius' splashRadius=DOUBLE)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RangedSpecifics}
		public Action getRangedSpecificsAction_0() { return cRangedSpecificsAction_0; }
		
		//'ranged-stats'
		public Keyword getRangedStatsKeyword_1() { return cRangedStatsKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('attackRange' attackRange=DOUBLE)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'attackRange'
		public Keyword getAttackRangeKeyword_3_0() { return cAttackRangeKeyword_3_0; }
		
		//attackRange=DOUBLE
		public Assignment getAttackRangeAssignment_3_1() { return cAttackRangeAssignment_3_1; }
		
		//DOUBLE
		public RuleCall getAttackRangeDOUBLEParserRuleCall_3_1_0() { return cAttackRangeDOUBLEParserRuleCall_3_1_0; }
		
		//('attackCooldown' attackCooldown=INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'attackCooldown'
		public Keyword getAttackCooldownKeyword_4_0() { return cAttackCooldownKeyword_4_0; }
		
		//attackCooldown=INT
		public Assignment getAttackCooldownAssignment_4_1() { return cAttackCooldownAssignment_4_1; }
		
		//INT
		public RuleCall getAttackCooldownINTTerminalRuleCall_4_1_0() { return cAttackCooldownINTTerminalRuleCall_4_1_0; }
		
		//('attackDamage' attackDamage=INT)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'attackDamage'
		public Keyword getAttackDamageKeyword_5_0() { return cAttackDamageKeyword_5_0; }
		
		//attackDamage=INT
		public Assignment getAttackDamageAssignment_5_1() { return cAttackDamageAssignment_5_1; }
		
		//INT
		public RuleCall getAttackDamageINTTerminalRuleCall_5_1_0() { return cAttackDamageINTTerminalRuleCall_5_1_0; }
		
		//('projectileSpeed' projectileSpeed=DOUBLE)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'projectileSpeed'
		public Keyword getProjectileSpeedKeyword_6_0() { return cProjectileSpeedKeyword_6_0; }
		
		//projectileSpeed=DOUBLE
		public Assignment getProjectileSpeedAssignment_6_1() { return cProjectileSpeedAssignment_6_1; }
		
		//DOUBLE
		public RuleCall getProjectileSpeedDOUBLEParserRuleCall_6_1_0() { return cProjectileSpeedDOUBLEParserRuleCall_6_1_0; }
		
		//('projectileType' projectileType=ProjectileTypeEnum)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'projectileType'
		public Keyword getProjectileTypeKeyword_7_0() { return cProjectileTypeKeyword_7_0; }
		
		//projectileType=ProjectileTypeEnum
		public Assignment getProjectileTypeAssignment_7_1() { return cProjectileTypeAssignment_7_1; }
		
		//ProjectileTypeEnum
		public RuleCall getProjectileTypeProjectileTypeEnumEnumRuleCall_7_1_0() { return cProjectileTypeProjectileTypeEnumEnumRuleCall_7_1_0; }
		
		//('splashRadius' splashRadius=DOUBLE)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'splashRadius'
		public Keyword getSplashRadiusKeyword_8_0() { return cSplashRadiusKeyword_8_0; }
		
		//splashRadius=DOUBLE
		public Assignment getSplashRadiusAssignment_8_1() { return cSplashRadiusAssignment_8_1; }
		
		//DOUBLE
		public RuleCall getSplashRadiusDOUBLEParserRuleCall_8_1_0() { return cSplashRadiusDOUBLEParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class PatrolConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.PatrolConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPatrolKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cVisionRangeKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cVisionRangeAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cVisionRangeDOUBLEParserRuleCall_3_1_0 = (RuleCall)cVisionRangeAssignment_3_1.eContents().get(0);
		private final Assignment cZoneAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cZonePatrolZoneConfigParserRuleCall_4_0 = (RuleCall)cZoneAssignment_4.eContents().get(0);
		private final Keyword cPathKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftSquareBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cWaypointsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cWaypointsWaypointParserRuleCall_7_0 = (RuleCall)cWaypointsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cWaypointsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cWaypointsWaypointParserRuleCall_8_1_0 = (RuleCall)cWaypointsAssignment_8_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		///*
		// * Patrol path configuration
		// */
		//PatrolConfig:
		//    'patrol' name=ID '{'
		//        ('visionRange' visionRange=DOUBLE)?
		//        (zone=PatrolZoneConfig)?
		//        'path' '['
		//            waypoints+=Waypoint (',' waypoints+=Waypoint)*
		//        ']'
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'patrol' name=ID '{'
		//    ('visionRange' visionRange=DOUBLE)?
		//    (zone=PatrolZoneConfig)?
		//    'path' '['
		//        waypoints+=Waypoint (',' waypoints+=Waypoint)*
		//    ']'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'patrol'
		public Keyword getPatrolKeyword_0() { return cPatrolKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('visionRange' visionRange=DOUBLE)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'visionRange'
		public Keyword getVisionRangeKeyword_3_0() { return cVisionRangeKeyword_3_0; }
		
		//visionRange=DOUBLE
		public Assignment getVisionRangeAssignment_3_1() { return cVisionRangeAssignment_3_1; }
		
		//DOUBLE
		public RuleCall getVisionRangeDOUBLEParserRuleCall_3_1_0() { return cVisionRangeDOUBLEParserRuleCall_3_1_0; }
		
		//(zone=PatrolZoneConfig)?
		public Assignment getZoneAssignment_4() { return cZoneAssignment_4; }
		
		//PatrolZoneConfig
		public RuleCall getZonePatrolZoneConfigParserRuleCall_4_0() { return cZonePatrolZoneConfigParserRuleCall_4_0; }
		
		//'path'
		public Keyword getPathKeyword_5() { return cPathKeyword_5; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6() { return cLeftSquareBracketKeyword_6; }
		
		//waypoints+=Waypoint
		public Assignment getWaypointsAssignment_7() { return cWaypointsAssignment_7; }
		
		//Waypoint
		public RuleCall getWaypointsWaypointParserRuleCall_7_0() { return cWaypointsWaypointParserRuleCall_7_0; }
		
		//(',' waypoints+=Waypoint)*
		public Group getGroup_8() { return cGroup_8; }
		
		//','
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//waypoints+=Waypoint
		public Assignment getWaypointsAssignment_8_1() { return cWaypointsAssignment_8_1; }
		
		//Waypoint
		public RuleCall getWaypointsWaypointParserRuleCall_8_1_0() { return cWaypointsWaypointParserRuleCall_8_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9() { return cRightSquareBracketKeyword_9; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class PatrolZoneConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.PatrolZoneConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cZoneKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cTopLeftKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTopLeftXAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTopLeftXDOUBLEParserRuleCall_4_0 = (RuleCall)cTopLeftXAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTopLeftYAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTopLeftYDOUBLEParserRuleCall_6_0 = (RuleCall)cTopLeftYAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cWidthKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cWidthAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cWidthDOUBLEParserRuleCall_9_0 = (RuleCall)cWidthAssignment_9.eContents().get(0);
		private final Keyword cHeightKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cHeightAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cHeightDOUBLEParserRuleCall_11_0 = (RuleCall)cHeightAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//PatrolZoneConfig:
		//    'zone' '{'
		//        'topLeft' '(' topLeftX=DOUBLE ',' topLeftY=DOUBLE ')'
		//        'width' width=DOUBLE
		//        'height' height=DOUBLE
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'zone' '{'
		//    'topLeft' '(' topLeftX=DOUBLE ',' topLeftY=DOUBLE ')'
		//    'width' width=DOUBLE
		//    'height' height=DOUBLE
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'zone'
		public Keyword getZoneKeyword_0() { return cZoneKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'topLeft'
		public Keyword getTopLeftKeyword_2() { return cTopLeftKeyword_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_3() { return cLeftParenthesisKeyword_3; }
		
		//topLeftX=DOUBLE
		public Assignment getTopLeftXAssignment_4() { return cTopLeftXAssignment_4; }
		
		//DOUBLE
		public RuleCall getTopLeftXDOUBLEParserRuleCall_4_0() { return cTopLeftXDOUBLEParserRuleCall_4_0; }
		
		//','
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//topLeftY=DOUBLE
		public Assignment getTopLeftYAssignment_6() { return cTopLeftYAssignment_6; }
		
		//DOUBLE
		public RuleCall getTopLeftYDOUBLEParserRuleCall_6_0() { return cTopLeftYDOUBLEParserRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'width'
		public Keyword getWidthKeyword_8() { return cWidthKeyword_8; }
		
		//width=DOUBLE
		public Assignment getWidthAssignment_9() { return cWidthAssignment_9; }
		
		//DOUBLE
		public RuleCall getWidthDOUBLEParserRuleCall_9_0() { return cWidthDOUBLEParserRuleCall_9_0; }
		
		//'height'
		public Keyword getHeightKeyword_10() { return cHeightKeyword_10; }
		
		//height=DOUBLE
		public Assignment getHeightAssignment_11() { return cHeightAssignment_11; }
		
		//DOUBLE
		public RuleCall getHeightDOUBLEParserRuleCall_11_0() { return cHeightDOUBLEParserRuleCall_11_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}
	public class WaypointElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.Waypoint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cXAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cXDOUBLEParserRuleCall_1_0 = (RuleCall)cXAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cYAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cYDOUBLEParserRuleCall_3_0 = (RuleCall)cYAssignment_3.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cWaitTimeAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cWaitTimeINTTerminalRuleCall_5_1_0 = (RuleCall)cWaitTimeAssignment_5_1.eContents().get(0);
		private final Keyword cMsKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		
		//Waypoint:
		//    '(' x=DOUBLE ',' y=DOUBLE ')'
		//    (':' waitTime=INT 'ms')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'(' x=DOUBLE ',' y=DOUBLE ')'
		//(':' waitTime=INT 'ms')?
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//x=DOUBLE
		public Assignment getXAssignment_1() { return cXAssignment_1; }
		
		//DOUBLE
		public RuleCall getXDOUBLEParserRuleCall_1_0() { return cXDOUBLEParserRuleCall_1_0; }
		
		//','
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//y=DOUBLE
		public Assignment getYAssignment_3() { return cYAssignment_3; }
		
		//DOUBLE
		public RuleCall getYDOUBLEParserRuleCall_3_0() { return cYDOUBLEParserRuleCall_3_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//(':' waitTime=INT 'ms')?
		public Group getGroup_5() { return cGroup_5; }
		
		//':'
		public Keyword getColonKeyword_5_0() { return cColonKeyword_5_0; }
		
		//waitTime=INT
		public Assignment getWaitTimeAssignment_5_1() { return cWaitTimeAssignment_5_1; }
		
		//INT
		public RuleCall getWaitTimeINTTerminalRuleCall_5_1_0() { return cWaitTimeINTTerminalRuleCall_5_1_0; }
		
		//'ms'
		public Keyword getMsKeyword_5_2() { return cMsKeyword_5_2; }
	}
	public class LootTableConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.LootTableConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLootTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCapacityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cCapacityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cCapacityINTTerminalRuleCall_3_1_0 = (RuleCall)cCapacityAssignment_3_1.eContents().get(0);
		private final Assignment cItemsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cItemsLootItemConfigParserRuleCall_4_0 = (RuleCall)cItemsAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		///*
		// * Loot table configuration
		// */
		//LootTableConfig:
		//    'loot-table' name=ID '{'
		//        ('capacity' capacity=INT)?
		//        items+=LootItemConfig+
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'loot-table' name=ID '{'
		//    ('capacity' capacity=INT)?
		//    items+=LootItemConfig+
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'loot-table'
		public Keyword getLootTableKeyword_0() { return cLootTableKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('capacity' capacity=INT)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'capacity'
		public Keyword getCapacityKeyword_3_0() { return cCapacityKeyword_3_0; }
		
		//capacity=INT
		public Assignment getCapacityAssignment_3_1() { return cCapacityAssignment_3_1; }
		
		//INT
		public RuleCall getCapacityINTTerminalRuleCall_3_1_0() { return cCapacityINTTerminalRuleCall_3_1_0; }
		
		//items+=LootItemConfig+
		public Assignment getItemsAssignment_4() { return cItemsAssignment_4; }
		
		//LootItemConfig
		public RuleCall getItemsLootItemConfigParserRuleCall_4_0() { return cItemsLootItemConfigParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class LootItemConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.LootItemConfig");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cItemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTypeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cTypeLootItemTypeEnumEnumRuleCall_4_0 = (RuleCall)cTypeAssignment_4.eContents().get(0);
		private final Keyword cValueKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cValueAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cValueINTTerminalRuleCall_6_0 = (RuleCall)cValueAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWeightKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cWeightAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cWeightINTTerminalRuleCall_7_1_0 = (RuleCall)cWeightAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//LootItemConfig:
		//    'item' name=ID '{'
		//        'type' type=LootItemTypeEnum
		//        'value' value=INT
		//        ('weight' weight=INT)?
		//    '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'item' name=ID '{'
		//    'type' type=LootItemTypeEnum
		//    'value' value=INT
		//    ('weight' weight=INT)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'item'
		public Keyword getItemKeyword_0() { return cItemKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'type'
		public Keyword getTypeKeyword_3() { return cTypeKeyword_3; }
		
		//type=LootItemTypeEnum
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }
		
		//LootItemTypeEnum
		public RuleCall getTypeLootItemTypeEnumEnumRuleCall_4_0() { return cTypeLootItemTypeEnumEnumRuleCall_4_0; }
		
		//'value'
		public Keyword getValueKeyword_5() { return cValueKeyword_5; }
		
		//value=INT
		public Assignment getValueAssignment_6() { return cValueAssignment_6; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_6_0() { return cValueINTTerminalRuleCall_6_0; }
		
		//('weight' weight=INT)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'weight'
		public Keyword getWeightKeyword_7_0() { return cWeightKeyword_7_0; }
		
		//weight=INT
		public Assignment getWeightAssignment_7_1() { return cWeightAssignment_7_1; }
		
		//INT
		public RuleCall getWeightINTTerminalRuleCall_7_1_0() { return cWeightINTTerminalRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class DOUBLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.DOUBLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cFullStopKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		
		///*
		// * Datatype rule for double values (accepts both integers and decimals)
		// */
		//DOUBLE returns ecore::EDouble:
		//    ('-')? INT ('.' INT)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('-')? INT ('.' INT)?
		public Group getGroup() { return cGroup; }
		
		//('-')?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//('.' INT)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'.'
		public Keyword getFullStopKeyword_2_0() { return cFullStopKeyword_2_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2_1() { return cINTTerminalRuleCall_2_1; }
	}
	public class SIGNED_INTElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.SIGNED_INT");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//SIGNED_INT returns ecore::EInt:
		//    ('-')? INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('-')? INT
		public Group getGroup() { return cGroup; }
		
		//('-')?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class BOOLEANElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.BOOLEAN");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		///*
		// * Datatype rule for boolean values
		// */
		//BOOLEAN returns ecore::EBoolean:
		//    'true' | 'false'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	public class DifficultyLevelElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.DifficultyLevel");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cEASYEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cEASYEasyKeyword_0_0 = (Keyword)cEASYEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNORMALEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNORMALNormalKeyword_1_0 = (Keyword)cNORMALEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cHARDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cHARDHardKeyword_2_0 = (Keyword)cHARDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum DifficultyLevel:
		//    EASY='easy' | NORMAL='normal' | HARD='hard'
		//;
		public EnumRule getRule() { return rule; }
		
		//EASY='easy' | NORMAL='normal' | HARD='hard'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//EASY='easy'
		public EnumLiteralDeclaration getEASYEnumLiteralDeclaration_0() { return cEASYEnumLiteralDeclaration_0; }
		
		//'easy'
		public Keyword getEASYEasyKeyword_0_0() { return cEASYEasyKeyword_0_0; }
		
		//NORMAL='normal'
		public EnumLiteralDeclaration getNORMALEnumLiteralDeclaration_1() { return cNORMALEnumLiteralDeclaration_1; }
		
		//'normal'
		public Keyword getNORMALNormalKeyword_1_0() { return cNORMALNormalKeyword_1_0; }
		
		//HARD='hard'
		public EnumLiteralDeclaration getHARDEnumLiteralDeclaration_2() { return cHARDEnumLiteralDeclaration_2; }
		
		//'hard'
		public Keyword getHARDHardKeyword_2_0() { return cHARDHardKeyword_2_0; }
	}
	public class EnemyTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.EnemyType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cZOMBIEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cZOMBIEZombieKeyword_0_0 = (Keyword)cZOMBIEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGHOSTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGHOSTGhostKeyword_1_0 = (Keyword)cGHOSTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPUMPKINBOMBEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPUMPKINBOMBERPumpkinbomberKeyword_2_0 = (Keyword)cPUMPKINBOMBEREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum EnemyType:
		//    ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
		//;
		public EnumRule getRule() { return rule; }
		
		//ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ZOMBIE='zombie'
		public EnumLiteralDeclaration getZOMBIEEnumLiteralDeclaration_0() { return cZOMBIEEnumLiteralDeclaration_0; }
		
		//'zombie'
		public Keyword getZOMBIEZombieKeyword_0_0() { return cZOMBIEZombieKeyword_0_0; }
		
		//GHOST='ghost'
		public EnumLiteralDeclaration getGHOSTEnumLiteralDeclaration_1() { return cGHOSTEnumLiteralDeclaration_1; }
		
		//'ghost'
		public Keyword getGHOSTGhostKeyword_1_0() { return cGHOSTGhostKeyword_1_0; }
		
		//PUMPKINBOMBER='pumpkinbomber'
		public EnumLiteralDeclaration getPUMPKINBOMBEREnumLiteralDeclaration_2() { return cPUMPKINBOMBEREnumLiteralDeclaration_2; }
		
		//'pumpkinbomber'
		public Keyword getPUMPKINBOMBERPumpkinbomberKeyword_2_0() { return cPUMPKINBOMBERPumpkinbomberKeyword_2_0; }
	}
	public class CharacterTypeEnumElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.CharacterTypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cZOMBIEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cZOMBIEZombieKeyword_0_0 = (Keyword)cZOMBIEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cGHOSTEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cGHOSTGhostKeyword_1_0 = (Keyword)cGHOSTEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cPUMPKINBOMBEREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cPUMPKINBOMBERPumpkinbomberKeyword_2_0 = (Keyword)cPUMPKINBOMBEREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum CharacterTypeEnum:
		//    ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
		//;
		public EnumRule getRule() { return rule; }
		
		//ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ZOMBIE='zombie'
		public EnumLiteralDeclaration getZOMBIEEnumLiteralDeclaration_0() { return cZOMBIEEnumLiteralDeclaration_0; }
		
		//'zombie'
		public Keyword getZOMBIEZombieKeyword_0_0() { return cZOMBIEZombieKeyword_0_0; }
		
		//GHOST='ghost'
		public EnumLiteralDeclaration getGHOSTEnumLiteralDeclaration_1() { return cGHOSTEnumLiteralDeclaration_1; }
		
		//'ghost'
		public Keyword getGHOSTGhostKeyword_1_0() { return cGHOSTGhostKeyword_1_0; }
		
		//PUMPKINBOMBER='pumpkinbomber'
		public EnumLiteralDeclaration getPUMPKINBOMBEREnumLiteralDeclaration_2() { return cPUMPKINBOMBEREnumLiteralDeclaration_2; }
		
		//'pumpkinbomber'
		public Keyword getPUMPKINBOMBERPumpkinbomberKeyword_2_0() { return cPUMPKINBOMBERPumpkinbomberKeyword_2_0; }
	}
	public class BehaviorTypeEnumElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.BehaviorTypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPASSIVEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPASSIVEPassiveKeyword_0_0 = (Keyword)cPASSIVEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cWANDEREnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cWANDERWanderKeyword_1_0 = (Keyword)cWANDEREnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAGGRESSIVEEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAGGRESSIVEAggressiveKeyword_2_0 = (Keyword)cAGGRESSIVEEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cPATROLEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cPATROLPatrolKeyword_3_0 = (Keyword)cPATROLEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum BehaviorTypeEnum:
		//    PASSIVE='passive' | WANDER='wander' | AGGRESSIVE='aggressive' | PATROL='patrol'
		//;
		public EnumRule getRule() { return rule; }
		
		//PASSIVE='passive' | WANDER='wander' | AGGRESSIVE='aggressive' | PATROL='patrol'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PASSIVE='passive'
		public EnumLiteralDeclaration getPASSIVEEnumLiteralDeclaration_0() { return cPASSIVEEnumLiteralDeclaration_0; }
		
		//'passive'
		public Keyword getPASSIVEPassiveKeyword_0_0() { return cPASSIVEPassiveKeyword_0_0; }
		
		//WANDER='wander'
		public EnumLiteralDeclaration getWANDEREnumLiteralDeclaration_1() { return cWANDEREnumLiteralDeclaration_1; }
		
		//'wander'
		public Keyword getWANDERWanderKeyword_1_0() { return cWANDERWanderKeyword_1_0; }
		
		//AGGRESSIVE='aggressive'
		public EnumLiteralDeclaration getAGGRESSIVEEnumLiteralDeclaration_2() { return cAGGRESSIVEEnumLiteralDeclaration_2; }
		
		//'aggressive'
		public Keyword getAGGRESSIVEAggressiveKeyword_2_0() { return cAGGRESSIVEAggressiveKeyword_2_0; }
		
		//PATROL='patrol'
		public EnumLiteralDeclaration getPATROLEnumLiteralDeclaration_3() { return cPATROLEnumLiteralDeclaration_3; }
		
		//'patrol'
		public Keyword getPATROLPatrolKeyword_3_0() { return cPATROLPatrolKeyword_3_0; }
	}
	public class ProjectileTypeEnumElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.ProjectileTypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSTRAIGHTEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSTRAIGHTStraightKeyword_0_0 = (Keyword)cSTRAIGHTEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLOBEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLOBLobKeyword_1_0 = (Keyword)cLOBEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBEAMEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBEAMBeamKeyword_2_0 = (Keyword)cBEAMEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ProjectileTypeEnum:
		//    STRAIGHT='straight' | LOB='lob' | BEAM='beam'
		//;
		public EnumRule getRule() { return rule; }
		
		//STRAIGHT='straight' | LOB='lob' | BEAM='beam'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRAIGHT='straight'
		public EnumLiteralDeclaration getSTRAIGHTEnumLiteralDeclaration_0() { return cSTRAIGHTEnumLiteralDeclaration_0; }
		
		//'straight'
		public Keyword getSTRAIGHTStraightKeyword_0_0() { return cSTRAIGHTStraightKeyword_0_0; }
		
		//LOB='lob'
		public EnumLiteralDeclaration getLOBEnumLiteralDeclaration_1() { return cLOBEnumLiteralDeclaration_1; }
		
		//'lob'
		public Keyword getLOBLobKeyword_1_0() { return cLOBLobKeyword_1_0; }
		
		//BEAM='beam'
		public EnumLiteralDeclaration getBEAMEnumLiteralDeclaration_2() { return cBEAMEnumLiteralDeclaration_2; }
		
		//'beam'
		public Keyword getBEAMBeamKeyword_2_0() { return cBEAMBeamKeyword_2_0; }
	}
	public class LootItemTypeEnumElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "main.game.maze.dsl.MazeDsl.LootItemTypeEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cFOODEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cFOODFoodKeyword_0_0 = (Keyword)cFOODEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBOMBEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBOMBBombKeyword_1_0 = (Keyword)cBOMBEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cTRAPEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cTRAPTrapKeyword_2_0 = (Keyword)cTRAPEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cWEAPONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cWEAPONWeaponKeyword_3_0 = (Keyword)cWEAPONEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum LootItemTypeEnum:
		//    FOOD='food' | BOMB='bomb' | TRAP='trap' | WEAPON='weapon'
		//;
		public EnumRule getRule() { return rule; }
		
		//FOOD='food' | BOMB='bomb' | TRAP='trap' | WEAPON='weapon'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//FOOD='food'
		public EnumLiteralDeclaration getFOODEnumLiteralDeclaration_0() { return cFOODEnumLiteralDeclaration_0; }
		
		//'food'
		public Keyword getFOODFoodKeyword_0_0() { return cFOODFoodKeyword_0_0; }
		
		//BOMB='bomb'
		public EnumLiteralDeclaration getBOMBEnumLiteralDeclaration_1() { return cBOMBEnumLiteralDeclaration_1; }
		
		//'bomb'
		public Keyword getBOMBBombKeyword_1_0() { return cBOMBBombKeyword_1_0; }
		
		//TRAP='trap'
		public EnumLiteralDeclaration getTRAPEnumLiteralDeclaration_2() { return cTRAPEnumLiteralDeclaration_2; }
		
		//'trap'
		public Keyword getTRAPTrapKeyword_2_0() { return cTRAPTrapKeyword_2_0; }
		
		//WEAPON='weapon'
		public EnumLiteralDeclaration getWEAPONEnumLiteralDeclaration_3() { return cWEAPONEnumLiteralDeclaration_3; }
		
		//'weapon'
		public Keyword getWEAPONWeaponKeyword_3_0() { return cWEAPONWeaponKeyword_3_0; }
	}
	
	private final GameConfigurationElements pGameConfiguration;
	private final ImportElements pImport;
	private final DifficultyConfigElements pDifficultyConfig;
	private final DifficultyLevelElements eDifficultyLevel;
	private final EnemyLimitElements pEnemyLimit;
	private final EnemyTypeElements eEnemyType;
	private final OpponentConfigElements pOpponentConfig;
	private final CharacterTypeEnumElements eCharacterTypeEnum;
	private final BehaviorTypeEnumElements eBehaviorTypeEnum;
	private final CharacterSpecificsElements pCharacterSpecifics;
	private final ZombieSpecificsElements pZombieSpecifics;
	private final GhostSpecificsElements pGhostSpecifics;
	private final RangedSpecificsElements pRangedSpecifics;
	private final ProjectileTypeEnumElements eProjectileTypeEnum;
	private final PatrolConfigElements pPatrolConfig;
	private final PatrolZoneConfigElements pPatrolZoneConfig;
	private final WaypointElements pWaypoint;
	private final LootTableConfigElements pLootTableConfig;
	private final LootItemConfigElements pLootItemConfig;
	private final LootItemTypeEnumElements eLootItemTypeEnum;
	private final DOUBLEElements pDOUBLE;
	private final SIGNED_INTElements pSIGNED_INT;
	private final BOOLEANElements pBOOLEAN;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MazeDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pGameConfiguration = new GameConfigurationElements();
		this.pImport = new ImportElements();
		this.pDifficultyConfig = new DifficultyConfigElements();
		this.eDifficultyLevel = new DifficultyLevelElements();
		this.pEnemyLimit = new EnemyLimitElements();
		this.eEnemyType = new EnemyTypeElements();
		this.pOpponentConfig = new OpponentConfigElements();
		this.eCharacterTypeEnum = new CharacterTypeEnumElements();
		this.eBehaviorTypeEnum = new BehaviorTypeEnumElements();
		this.pCharacterSpecifics = new CharacterSpecificsElements();
		this.pZombieSpecifics = new ZombieSpecificsElements();
		this.pGhostSpecifics = new GhostSpecificsElements();
		this.pRangedSpecifics = new RangedSpecificsElements();
		this.eProjectileTypeEnum = new ProjectileTypeEnumElements();
		this.pPatrolConfig = new PatrolConfigElements();
		this.pPatrolZoneConfig = new PatrolZoneConfigElements();
		this.pWaypoint = new WaypointElements();
		this.pLootTableConfig = new LootTableConfigElements();
		this.pLootItemConfig = new LootItemConfigElements();
		this.eLootItemTypeEnum = new LootItemTypeEnumElements();
		this.pDOUBLE = new DOUBLEElements();
		this.pSIGNED_INT = new SIGNED_INTElements();
		this.pBOOLEAN = new BOOLEANElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("main.game.maze.dsl.MazeDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	///*
	// * Root element - A game configuration containing all game elements
	// */
	//GameConfiguration:
	//    'game' name=ID '{'
	//        (imports+=Import)*
	//        (difficulty=DifficultyConfig)?
	//        (opponents+=OpponentConfig)*
	//        (patrols+=PatrolConfig)*
	//        (lootTables+=LootTableConfig)*
	//    '}'
	//;
	public GameConfigurationElements getGameConfigurationAccess() {
		return pGameConfiguration;
	}
	
	public ParserRule getGameConfigurationRule() {
		return getGameConfigurationAccess().getRule();
	}
	
	///*
	// * Import statement for referencing external XMI files
	// */
	//Import:
	//    'import' importURI=STRING
	//;
	public ImportElements getImportAccess() {
		return pImport;
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}
	
	///*
	// * Difficulty configuration section
	// */
	//DifficultyConfig:
	//    'difficulty' '{'
	//        'level' level=DifficultyLevel
	//        ('instantDeath' instantDeath?='true')?
	//        ('speedMultiplier' speedMultiplier=DOUBLE)?
	//        ('damageMultiplier' damageMultiplier=DOUBLE)?
	//        ('maxThreat' maxThreat=SIGNED_INT)?
	//        (enemyLimits+=EnemyLimit)*
	//    '}'
	//;
	public DifficultyConfigElements getDifficultyConfigAccess() {
		return pDifficultyConfig;
	}
	
	public ParserRule getDifficultyConfigRule() {
		return getDifficultyConfigAccess().getRule();
	}
	
	//enum DifficultyLevel:
	//    EASY='easy' | NORMAL='normal' | HARD='hard'
	//;
	public DifficultyLevelElements getDifficultyLevelAccess() {
		return eDifficultyLevel;
	}
	
	public EnumRule getDifficultyLevelRule() {
		return getDifficultyLevelAccess().getRule();
	}
	
	///*
	// * Enemy count limits per type
	// */
	//EnemyLimit:
	//    'limit' type=EnemyType 'max' maxCount=SIGNED_INT
	//;
	public EnemyLimitElements getEnemyLimitAccess() {
		return pEnemyLimit;
	}
	
	public ParserRule getEnemyLimitRule() {
		return getEnemyLimitAccess().getRule();
	}
	
	//enum EnemyType:
	//    ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
	//;
	public EnemyTypeElements getEnemyTypeAccess() {
		return eEnemyType;
	}
	
	public EnumRule getEnemyTypeRule() {
		return getEnemyTypeAccess().getRule();
	}
	
	///*
	// * Opponent/Enemy configuration
	// */
	//OpponentConfig:
	//    'opponent' name=ID '{'
	//        'type' type=CharacterTypeEnum
	//        ('displayName' displayName=STRING)?
	//        ('health' health=SIGNED_INT)?
	//        ('speed' speed=DOUBLE)?
	//        ('threatLevel' threatLevel=DOUBLE)?
	//        ('enabled' enabled=BOOLEAN)?
	//        ('behavior' behavior=BehaviorTypeEnum)?
	//        (characterSpecifics=CharacterSpecifics)?
	//        ('patrol' patrolRef=[PatrolConfig])?
	//        ('loot' lootRef=[LootTableConfig])?
	//    '}'
	//;
	public OpponentConfigElements getOpponentConfigAccess() {
		return pOpponentConfig;
	}
	
	public ParserRule getOpponentConfigRule() {
		return getOpponentConfigAccess().getRule();
	}
	
	//enum CharacterTypeEnum:
	//    ZOMBIE='zombie' | GHOST='ghost' | PUMPKINBOMBER='pumpkinbomber'
	//;
	public CharacterTypeEnumElements getCharacterTypeEnumAccess() {
		return eCharacterTypeEnum;
	}
	
	public EnumRule getCharacterTypeEnumRule() {
		return getCharacterTypeEnumAccess().getRule();
	}
	
	//enum BehaviorTypeEnum:
	//    PASSIVE='passive' | WANDER='wander' | AGGRESSIVE='aggressive' | PATROL='patrol'
	//;
	public BehaviorTypeEnumElements getBehaviorTypeEnumAccess() {
		return eBehaviorTypeEnum;
	}
	
	public EnumRule getBehaviorTypeEnumRule() {
		return getBehaviorTypeEnumAccess().getRule();
	}
	
	///*
	// * Character-specific attributes (zombie, ghost, or ranged enemy)
	// */
	//CharacterSpecifics:
	//    ZombieSpecifics | GhostSpecifics | RangedSpecifics
	//;
	public CharacterSpecificsElements getCharacterSpecificsAccess() {
		return pCharacterSpecifics;
	}
	
	public ParserRule getCharacterSpecificsRule() {
		return getCharacterSpecificsAccess().getRule();
	}
	
	//ZombieSpecifics:
	//    {ZombieSpecifics}
	//    'zombie-stats' '{'
	//        ('attackDamage' attackDamage=INT)?
	//        ('infectionLevel' infectionLevel=INT)?
	//        ('resurrectionTime' resurrectionTime=INT)?
	//    '}'
	//;
	public ZombieSpecificsElements getZombieSpecificsAccess() {
		return pZombieSpecifics;
	}
	
	public ParserRule getZombieSpecificsRule() {
		return getZombieSpecificsAccess().getRule();
	}
	
	//GhostSpecifics:
	//    {GhostSpecifics}
	//    'ghost-stats' '{'
	//        ('attackDamage' attackDamage=INT)?
	//        ('visibilityLevel' visibilityLevel=INT)?
	//        ('nonTangibilityEnergy' nonTangibilityEnergy=DOUBLE)?
	//    '}'
	//;
	public GhostSpecificsElements getGhostSpecificsAccess() {
		return pGhostSpecifics;
	}
	
	public ParserRule getGhostSpecificsRule() {
		return getGhostSpecificsAccess().getRule();
	}
	
	//RangedSpecifics:
	//    {RangedSpecifics}
	//    'ranged-stats' '{'
	//        ('attackRange' attackRange=DOUBLE)?
	//        ('attackCooldown' attackCooldown=INT)?
	//        ('attackDamage' attackDamage=INT)?
	//        ('projectileSpeed' projectileSpeed=DOUBLE)?
	//        ('projectileType' projectileType=ProjectileTypeEnum)?
	//        ('splashRadius' splashRadius=DOUBLE)?
	//    '}'
	//;
	public RangedSpecificsElements getRangedSpecificsAccess() {
		return pRangedSpecifics;
	}
	
	public ParserRule getRangedSpecificsRule() {
		return getRangedSpecificsAccess().getRule();
	}
	
	//enum ProjectileTypeEnum:
	//    STRAIGHT='straight' | LOB='lob' | BEAM='beam'
	//;
	public ProjectileTypeEnumElements getProjectileTypeEnumAccess() {
		return eProjectileTypeEnum;
	}
	
	public EnumRule getProjectileTypeEnumRule() {
		return getProjectileTypeEnumAccess().getRule();
	}
	
	///*
	// * Patrol path configuration
	// */
	//PatrolConfig:
	//    'patrol' name=ID '{'
	//        ('visionRange' visionRange=DOUBLE)?
	//        (zone=PatrolZoneConfig)?
	//        'path' '['
	//            waypoints+=Waypoint (',' waypoints+=Waypoint)*
	//        ']'
	//    '}'
	//;
	public PatrolConfigElements getPatrolConfigAccess() {
		return pPatrolConfig;
	}
	
	public ParserRule getPatrolConfigRule() {
		return getPatrolConfigAccess().getRule();
	}
	
	//PatrolZoneConfig:
	//    'zone' '{'
	//        'topLeft' '(' topLeftX=DOUBLE ',' topLeftY=DOUBLE ')'
	//        'width' width=DOUBLE
	//        'height' height=DOUBLE
	//    '}'
	//;
	public PatrolZoneConfigElements getPatrolZoneConfigAccess() {
		return pPatrolZoneConfig;
	}
	
	public ParserRule getPatrolZoneConfigRule() {
		return getPatrolZoneConfigAccess().getRule();
	}
	
	//Waypoint:
	//    '(' x=DOUBLE ',' y=DOUBLE ')'
	//    (':' waitTime=INT 'ms')?
	//;
	public WaypointElements getWaypointAccess() {
		return pWaypoint;
	}
	
	public ParserRule getWaypointRule() {
		return getWaypointAccess().getRule();
	}
	
	///*
	// * Loot table configuration
	// */
	//LootTableConfig:
	//    'loot-table' name=ID '{'
	//        ('capacity' capacity=INT)?
	//        items+=LootItemConfig+
	//    '}'
	//;
	public LootTableConfigElements getLootTableConfigAccess() {
		return pLootTableConfig;
	}
	
	public ParserRule getLootTableConfigRule() {
		return getLootTableConfigAccess().getRule();
	}
	
	//LootItemConfig:
	//    'item' name=ID '{'
	//        'type' type=LootItemTypeEnum
	//        'value' value=INT
	//        ('weight' weight=INT)?
	//    '}'
	//;
	public LootItemConfigElements getLootItemConfigAccess() {
		return pLootItemConfig;
	}
	
	public ParserRule getLootItemConfigRule() {
		return getLootItemConfigAccess().getRule();
	}
	
	//enum LootItemTypeEnum:
	//    FOOD='food' | BOMB='bomb' | TRAP='trap' | WEAPON='weapon'
	//;
	public LootItemTypeEnumElements getLootItemTypeEnumAccess() {
		return eLootItemTypeEnum;
	}
	
	public EnumRule getLootItemTypeEnumRule() {
		return getLootItemTypeEnumAccess().getRule();
	}
	
	///*
	// * Datatype rule for double values (accepts both integers and decimals)
	// */
	//DOUBLE returns ecore::EDouble:
	//    ('-')? INT ('.' INT)?
	//;
	public DOUBLEElements getDOUBLEAccess() {
		return pDOUBLE;
	}
	
	public ParserRule getDOUBLERule() {
		return getDOUBLEAccess().getRule();
	}
	
	//SIGNED_INT returns ecore::EInt:
	//    ('-')? INT
	//;
	public SIGNED_INTElements getSIGNED_INTAccess() {
		return pSIGNED_INT;
	}
	
	public ParserRule getSIGNED_INTRule() {
		return getSIGNED_INTAccess().getRule();
	}
	
	///*
	// * Datatype rule for boolean values
	// */
	//BOOLEAN returns ecore::EBoolean:
	//    'true' | 'false'
	//;
	public BOOLEANElements getBOOLEANAccess() {
		return pBOOLEAN;
	}
	
	public ParserRule getBOOLEANRule() {
		return getBOOLEANAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}


