/*
 * generated by Xtext
 */
package main.game.maze.dsl.parser.antlr;

import com.google.inject.Inject;
import main.game.maze.dsl.parser.antlr.internal.InternalMazeDslParser;
import main.game.maze.dsl.services.MazeDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MazeDslParser extends AbstractAntlrParser {

	@Inject
	private MazeDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMazeDslParser createParser(XtextTokenStream stream) {
		return new InternalMazeDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GameConfiguration";
	}

	public MazeDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MazeDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
