# Build properties for maze-generator.freemarker
source.. = src/main/java/
output.. = bin/
bin.includes = META-INF/,\
               plugin.xml,\
               src/main/java/,\
               src/main/resources/,\
               lib/,\
               .