<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mazeidea" nsURI="http://main.game.maze/maze-idea" nsPrefix="maze-idea">
  <eSubpackages name="difficulty" nsURI="http://main.game.maze/maze-idea/difficulty"
      nsPrefix="idea.difficulty">
    <eClassifiers xsi:type="ecore:EClass" name="GameDatas">
      <eOperations name="getInstance" eType="#//difficulty/GameDatas"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EasyDifficulty" eSuperTypes="#//difficulty/Difficulty"/>
    <eClassifiers xsi:type="ecore:EClass" name="Difficulty" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instantDeath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enemymaxcount" ordered="false"
          upperBound="-1" eType="#//difficulty/EnemyMaxCount"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="movementSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="monstersDamage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NormalDifficulty" eSuperTypes="#//difficulty/Difficulty"/>
    <eClassifiers xsi:type="ecore:EClass" name="HardDifficulty" eSuperTypes="#//difficulty/Difficulty"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnemyMaxCount">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../../../../opponents-module/src/main/resources/opponents/opponents.ecore#//EnemyTypes"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="movements" nsURI="http://main.game.maze/maze-idea/character/movements"
      nsPrefix="idea.character.movements">
    <eClassifiers xsi:type="ecore:EClass" name="MovementBehavior" abstract="true"
        interface="true">
      <eOperations name="move" lowerBound="1">
        <eParameters name="enemy" eType="#//characters/EnemyCharacter"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomBehavior" eSuperTypes="#//movements/MovementBehavior">
      <eOperations name="setRandomDirection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChaseBehavior" eSuperTypes="#//movements/MovementBehavior">
      <eOperations name="setDirectionToPlayer">
        <eParameters name="player" eType="#//characters/PlayerCharacter"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatrolBehavior" eSuperTypes="#//movements/MovementBehavior">
      <eOperations name="getNextStep" eType="#//movements/PatrolPoint"/>
      <eOperations name="setNextDirection"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="steps" lowerBound="2"
          upperBound="-1" eType="#//movements/PatrolPoint" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PatrolPoint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="characters" nsURI="http://main.game.maze/maze-idea/characters"
      nsPrefix="idea.characters">
    <eClassifiers xsi:type="ecore:EClass" name="Character" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="PlayerCharacter" eSuperTypes="#//characters/Character"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnemyCharacter" abstract="true" eSuperTypes="#//characters/Character">
      <eOperations name="move" lowerBound="1"/>
      <eOperations name="setMovementBehavior" lowerBound="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="movementBehavior" eType="#//movements/MovementBehavior"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
