<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>main.game.maze</groupId>
    <artifactId>MazeGame</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <packaging>eclipse-plugin</packaging>
  <artifactId>main.game.maze.dsl</artifactId>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>
    <xtext.version>2.33.0</xtext.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.xtext</groupId>
      <artifactId>org.eclipse.xtext</artifactId>
      <version>${xtext.version}</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.xtext</groupId>
      <artifactId>org.eclipse.xtext.xbase</artifactId>
      <version>${xtext.version}</version>
    </dependency>
    <dependency>
      <groupId>main.game.maze</groupId>
      <artifactId>main.game.maze.behaviour</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>main.game.maze</groupId>
      <artifactId>main.game.maze.difficulties</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>main.game.maze</groupId>
      <artifactId>main.game.maze.opponents</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.eclipse.xtext</groupId>
        <artifactId>xtext-maven-plugin</artifactId>
        <version>${xtext.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <languages>
            <language>
              <setup>main.game.maze.dsl.MazeDslStandaloneSetup</setup>
              <outputConfigurations>
                <outputConfiguration>
                  <outputDirectory>${project.basedir}/src-gen</outputDirectory>
                </outputConfiguration>
              </outputConfigurations>
            </language>
          </languages>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
