/*
 * generated by Xtext 2.40.0
 */
package main.game.maze.parser.antlr;

import com.google.inject.Inject;
import main.game.maze.parser.antlr.internal.InternalMazeCompParser;
import main.game.maze.services.MazeCompGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MazeCompParser extends AbstractAntlrParser {

	@Inject
	private MazeCompGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMazeCompParser createParser(XtextTokenStream stream) {
		return new InternalMazeCompParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MazeFile";
	}

	public MazeCompGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MazeCompGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
