/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.mazecomp.impl;

import main.game.maze.difficulties.DifficultiesPackage;

import main.game.maze.mazecomp.MazeFile;
import main.game.maze.mazecomp.MazecompFactory;
import main.game.maze.mazecomp.MazecompPackage;

import main.game.maze.opponents.OpponentsPackage;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MazecompPackageImpl extends EPackageImpl implements MazecompPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mazeFileEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see main.game.maze.mazecomp.MazecompPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MazecompPackageImpl()
  {
    super(eNS_URI, MazecompFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MazecompPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MazecompPackage init()
  {
    if (isInited) return (MazecompPackage)EPackage.Registry.INSTANCE.getEPackage(MazecompPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMazecompPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MazecompPackageImpl theMazecompPackage = registeredMazecompPackage instanceof MazecompPackageImpl ? (MazecompPackageImpl)registeredMazecompPackage : new MazecompPackageImpl();

    isInited = true;

    // Initialize simple dependencies
    OpponentsPackage.eINSTANCE.eClass();
    DifficultiesPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theMazecompPackage.createPackageContents();

    // Initialize created meta-data
    theMazecompPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMazecompPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MazecompPackage.eNS_URI, theMazecompPackage);
    return theMazecompPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMazeFile()
  {
    return mazeFileEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMazeFile_Zombies()
  {
    return (EReference)mazeFileEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMazeFile_Ghosts()
  {
    return (EReference)mazeFileEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMazeFile_PumpkinBombers()
  {
    return (EReference)mazeFileEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMazeFile_LootTables()
  {
    return (EReference)mazeFileEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMazeFile_LootItems()
  {
    return (EReference)mazeFileEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MazecompFactory getMazecompFactory()
  {
    return (MazecompFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    mazeFileEClass = createEClass(MAZE_FILE);
    createEReference(mazeFileEClass, MAZE_FILE__ZOMBIES);
    createEReference(mazeFileEClass, MAZE_FILE__GHOSTS);
    createEReference(mazeFileEClass, MAZE_FILE__PUMPKIN_BOMBERS);
    createEReference(mazeFileEClass, MAZE_FILE__LOOT_TABLES);
    createEReference(mazeFileEClass, MAZE_FILE__LOOT_ITEMS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    OpponentsPackage theOpponentsPackage = (OpponentsPackage)EPackage.Registry.INSTANCE.getEPackage(OpponentsPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes

    // Initialize classes and features; add operations and parameters
    initEClass(mazeFileEClass, MazeFile.class, "MazeFile", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMazeFile_Zombies(), theOpponentsPackage.getZombie(), null, "zombies", null, 0, -1, MazeFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMazeFile_Ghosts(), theOpponentsPackage.getGhost(), null, "ghosts", null, 0, -1, MazeFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMazeFile_PumpkinBombers(), theOpponentsPackage.getPumpkinBomber(), null, "pumpkinBombers", null, 0, -1, MazeFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMazeFile_LootTables(), theOpponentsPackage.getLootTable(), null, "lootTables", null, 0, -1, MazeFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMazeFile_LootItems(), theOpponentsPackage.getLootItem(), null, "lootItems", null, 0, -1, MazeFile.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MazecompPackageImpl
