/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.mazecomp.impl;

import java.util.Collection;

import main.game.maze.mazecomp.MazeFile;
import main.game.maze.mazecomp.MazecompPackage;

import main.game.maze.opponents.Ghost;
import main.game.maze.opponents.LootItem;
import main.game.maze.opponents.LootTable;
import main.game.maze.opponents.PumpkinBomber;
import main.game.maze.opponents.Zombie;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Maze File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.mazecomp.impl.MazeFileImpl#getZombies <em>Zombies</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.impl.MazeFileImpl#getGhosts <em>Ghosts</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.impl.MazeFileImpl#getPumpkinBombers <em>Pumpkin Bombers</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.impl.MazeFileImpl#getLootTables <em>Loot Tables</em>}</li>
 *   <li>{@link main.game.maze.mazecomp.impl.MazeFileImpl#getLootItems <em>Loot Items</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MazeFileImpl extends MinimalEObjectImpl.Container implements MazeFile
{
  /**
   * The cached value of the '{@link #getZombies() <em>Zombies</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getZombies()
   * @generated
   * @ordered
   */
  protected EList<Zombie> zombies;

  /**
   * The cached value of the '{@link #getGhosts() <em>Ghosts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGhosts()
   * @generated
   * @ordered
   */
  protected EList<Ghost> ghosts;

  /**
   * The cached value of the '{@link #getPumpkinBombers() <em>Pumpkin Bombers</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPumpkinBombers()
   * @generated
   * @ordered
   */
  protected EList<PumpkinBomber> pumpkinBombers;

  /**
   * The cached value of the '{@link #getLootTables() <em>Loot Tables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLootTables()
   * @generated
   * @ordered
   */
  protected EList<LootTable> lootTables;

  /**
   * The cached value of the '{@link #getLootItems() <em>Loot Items</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLootItems()
   * @generated
   * @ordered
   */
  protected EList<LootItem> lootItems;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MazeFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazecompPackage.Literals.MAZE_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Zombie> getZombies()
  {
    if (zombies == null)
    {
      zombies = new EObjectContainmentEList<Zombie>(Zombie.class, this, MazecompPackage.MAZE_FILE__ZOMBIES);
    }
    return zombies;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Ghost> getGhosts()
  {
    if (ghosts == null)
    {
      ghosts = new EObjectContainmentEList<Ghost>(Ghost.class, this, MazecompPackage.MAZE_FILE__GHOSTS);
    }
    return ghosts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PumpkinBomber> getPumpkinBombers()
  {
    if (pumpkinBombers == null)
    {
      pumpkinBombers = new EObjectContainmentEList<PumpkinBomber>(PumpkinBomber.class, this, MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS);
    }
    return pumpkinBombers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LootTable> getLootTables()
  {
    if (lootTables == null)
    {
      lootTables = new EObjectContainmentEList<LootTable>(LootTable.class, this, MazecompPackage.MAZE_FILE__LOOT_TABLES);
    }
    return lootTables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LootItem> getLootItems()
  {
    if (lootItems == null)
    {
      lootItems = new EObjectContainmentEList<LootItem>(LootItem.class, this, MazecompPackage.MAZE_FILE__LOOT_ITEMS);
    }
    return lootItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MazecompPackage.MAZE_FILE__ZOMBIES:
        return ((InternalEList<?>)getZombies()).basicRemove(otherEnd, msgs);
      case MazecompPackage.MAZE_FILE__GHOSTS:
        return ((InternalEList<?>)getGhosts()).basicRemove(otherEnd, msgs);
      case MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS:
        return ((InternalEList<?>)getPumpkinBombers()).basicRemove(otherEnd, msgs);
      case MazecompPackage.MAZE_FILE__LOOT_TABLES:
        return ((InternalEList<?>)getLootTables()).basicRemove(otherEnd, msgs);
      case MazecompPackage.MAZE_FILE__LOOT_ITEMS:
        return ((InternalEList<?>)getLootItems()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazecompPackage.MAZE_FILE__ZOMBIES:
        return getZombies();
      case MazecompPackage.MAZE_FILE__GHOSTS:
        return getGhosts();
      case MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS:
        return getPumpkinBombers();
      case MazecompPackage.MAZE_FILE__LOOT_TABLES:
        return getLootTables();
      case MazecompPackage.MAZE_FILE__LOOT_ITEMS:
        return getLootItems();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazecompPackage.MAZE_FILE__ZOMBIES:
        getZombies().clear();
        getZombies().addAll((Collection<? extends Zombie>)newValue);
        return;
      case MazecompPackage.MAZE_FILE__GHOSTS:
        getGhosts().clear();
        getGhosts().addAll((Collection<? extends Ghost>)newValue);
        return;
      case MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS:
        getPumpkinBombers().clear();
        getPumpkinBombers().addAll((Collection<? extends PumpkinBomber>)newValue);
        return;
      case MazecompPackage.MAZE_FILE__LOOT_TABLES:
        getLootTables().clear();
        getLootTables().addAll((Collection<? extends LootTable>)newValue);
        return;
      case MazecompPackage.MAZE_FILE__LOOT_ITEMS:
        getLootItems().clear();
        getLootItems().addAll((Collection<? extends LootItem>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazecompPackage.MAZE_FILE__ZOMBIES:
        getZombies().clear();
        return;
      case MazecompPackage.MAZE_FILE__GHOSTS:
        getGhosts().clear();
        return;
      case MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS:
        getPumpkinBombers().clear();
        return;
      case MazecompPackage.MAZE_FILE__LOOT_TABLES:
        getLootTables().clear();
        return;
      case MazecompPackage.MAZE_FILE__LOOT_ITEMS:
        getLootItems().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazecompPackage.MAZE_FILE__ZOMBIES:
        return zombies != null && !zombies.isEmpty();
      case MazecompPackage.MAZE_FILE__GHOSTS:
        return ghosts != null && !ghosts.isEmpty();
      case MazecompPackage.MAZE_FILE__PUMPKIN_BOMBERS:
        return pumpkinBombers != null && !pumpkinBombers.isEmpty();
      case MazecompPackage.MAZE_FILE__LOOT_TABLES:
        return lootTables != null && !lootTables.isEmpty();
      case MazecompPackage.MAZE_FILE__LOOT_ITEMS:
        return lootItems != null && !lootItems.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //MazeFileImpl
