/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import main.game.maze.dsl.mazeDsl.CharacterSpecifics;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Character Specifics</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.CharacterSpecificsImpl#getAttackDamage <em>Attack Damage</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CharacterSpecificsImpl extends MinimalEObjectImpl.Container implements CharacterSpecifics
{
  /**
   * The default value of the '{@link #getAttackDamage() <em>Attack Damage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackDamage()
   * @generated
   * @ordered
   */
  protected static final int ATTACK_DAMAGE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAttackDamage() <em>Attack Damage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackDamage()
   * @generated
   * @ordered
   */
  protected int attackDamage = ATTACK_DAMAGE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CharacterSpecificsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.CHARACTER_SPECIFICS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getAttackDamage()
  {
    return attackDamage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttackDamage(int newAttackDamage)
  {
    int oldAttackDamage = attackDamage;
    attackDamage = newAttackDamage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.CHARACTER_SPECIFICS__ATTACK_DAMAGE, oldAttackDamage, attackDamage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.CHARACTER_SPECIFICS__ATTACK_DAMAGE:
        return getAttackDamage();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.CHARACTER_SPECIFICS__ATTACK_DAMAGE:
        setAttackDamage((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.CHARACTER_SPECIFICS__ATTACK_DAMAGE:
        setAttackDamage(ATTACK_DAMAGE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.CHARACTER_SPECIFICS__ATTACK_DAMAGE:
        return attackDamage != ATTACK_DAMAGE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (attackDamage: ");
    result.append(attackDamage);
    result.append(')');
    return result.toString();
  }

} //CharacterSpecificsImpl
