/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import java.util.Collection;

import main.game.maze.dsl.mazeDsl.DifficultyConfig;
import main.game.maze.dsl.mazeDsl.DifficultyLevel;
import main.game.maze.dsl.mazeDsl.EnemyLimit;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Difficulty Config</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#getLevel <em>Level</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#isInstantDeath <em>Instant Death</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#getSpeedMultiplier <em>Speed Multiplier</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#getDamageMultiplier <em>Damage Multiplier</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#getMaxThreat <em>Max Threat</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.DifficultyConfigImpl#getEnemyLimits <em>Enemy Limits</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DifficultyConfigImpl extends MinimalEObjectImpl.Container implements DifficultyConfig
{
  /**
   * The default value of the '{@link #getLevel() <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevel()
   * @generated
   * @ordered
   */
  protected static final DifficultyLevel LEVEL_EDEFAULT = DifficultyLevel.EASY;

  /**
   * The cached value of the '{@link #getLevel() <em>Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLevel()
   * @generated
   * @ordered
   */
  protected DifficultyLevel level = LEVEL_EDEFAULT;

  /**
   * The default value of the '{@link #isInstantDeath() <em>Instant Death</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isInstantDeath()
   * @generated
   * @ordered
   */
  protected static final boolean INSTANT_DEATH_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isInstantDeath() <em>Instant Death</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isInstantDeath()
   * @generated
   * @ordered
   */
  protected boolean instantDeath = INSTANT_DEATH_EDEFAULT;

  /**
   * The default value of the '{@link #getSpeedMultiplier() <em>Speed Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeedMultiplier()
   * @generated
   * @ordered
   */
  protected static final double SPEED_MULTIPLIER_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getSpeedMultiplier() <em>Speed Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeedMultiplier()
   * @generated
   * @ordered
   */
  protected double speedMultiplier = SPEED_MULTIPLIER_EDEFAULT;

  /**
   * The default value of the '{@link #getDamageMultiplier() <em>Damage Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDamageMultiplier()
   * @generated
   * @ordered
   */
  protected static final double DAMAGE_MULTIPLIER_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getDamageMultiplier() <em>Damage Multiplier</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDamageMultiplier()
   * @generated
   * @ordered
   */
  protected double damageMultiplier = DAMAGE_MULTIPLIER_EDEFAULT;

  /**
   * The default value of the '{@link #getMaxThreat() <em>Max Threat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxThreat()
   * @generated
   * @ordered
   */
  protected static final int MAX_THREAT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getMaxThreat() <em>Max Threat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMaxThreat()
   * @generated
   * @ordered
   */
  protected int maxThreat = MAX_THREAT_EDEFAULT;

  /**
   * The cached value of the '{@link #getEnemyLimits() <em>Enemy Limits</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnemyLimits()
   * @generated
   * @ordered
   */
  protected EList<EnemyLimit> enemyLimits;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DifficultyConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.DIFFICULTY_CONFIG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DifficultyLevel getLevel()
  {
    return level;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLevel(DifficultyLevel newLevel)
  {
    DifficultyLevel oldLevel = level;
    level = newLevel == null ? LEVEL_EDEFAULT : newLevel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.DIFFICULTY_CONFIG__LEVEL, oldLevel, level));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isInstantDeath()
  {
    return instantDeath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInstantDeath(boolean newInstantDeath)
  {
    boolean oldInstantDeath = instantDeath;
    instantDeath = newInstantDeath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.DIFFICULTY_CONFIG__INSTANT_DEATH, oldInstantDeath, instantDeath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getSpeedMultiplier()
  {
    return speedMultiplier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpeedMultiplier(double newSpeedMultiplier)
  {
    double oldSpeedMultiplier = speedMultiplier;
    speedMultiplier = newSpeedMultiplier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.DIFFICULTY_CONFIG__SPEED_MULTIPLIER, oldSpeedMultiplier, speedMultiplier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getDamageMultiplier()
  {
    return damageMultiplier;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDamageMultiplier(double newDamageMultiplier)
  {
    double oldDamageMultiplier = damageMultiplier;
    damageMultiplier = newDamageMultiplier;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER, oldDamageMultiplier, damageMultiplier));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getMaxThreat()
  {
    return maxThreat;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMaxThreat(int newMaxThreat)
  {
    int oldMaxThreat = maxThreat;
    maxThreat = newMaxThreat;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.DIFFICULTY_CONFIG__MAX_THREAT, oldMaxThreat, maxThreat));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EnemyLimit> getEnemyLimits()
  {
    if (enemyLimits == null)
    {
      enemyLimits = new EObjectContainmentEList<EnemyLimit>(EnemyLimit.class, this, MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS);
    }
    return enemyLimits;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS:
        return ((InternalEList<?>)getEnemyLimits()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.DIFFICULTY_CONFIG__LEVEL:
        return getLevel();
      case MazeDslPackage.DIFFICULTY_CONFIG__INSTANT_DEATH:
        return isInstantDeath();
      case MazeDslPackage.DIFFICULTY_CONFIG__SPEED_MULTIPLIER:
        return getSpeedMultiplier();
      case MazeDslPackage.DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER:
        return getDamageMultiplier();
      case MazeDslPackage.DIFFICULTY_CONFIG__MAX_THREAT:
        return getMaxThreat();
      case MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS:
        return getEnemyLimits();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.DIFFICULTY_CONFIG__LEVEL:
        setLevel((DifficultyLevel)newValue);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__INSTANT_DEATH:
        setInstantDeath((Boolean)newValue);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__SPEED_MULTIPLIER:
        setSpeedMultiplier((Double)newValue);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER:
        setDamageMultiplier((Double)newValue);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__MAX_THREAT:
        setMaxThreat((Integer)newValue);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS:
        getEnemyLimits().clear();
        getEnemyLimits().addAll((Collection<? extends EnemyLimit>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.DIFFICULTY_CONFIG__LEVEL:
        setLevel(LEVEL_EDEFAULT);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__INSTANT_DEATH:
        setInstantDeath(INSTANT_DEATH_EDEFAULT);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__SPEED_MULTIPLIER:
        setSpeedMultiplier(SPEED_MULTIPLIER_EDEFAULT);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER:
        setDamageMultiplier(DAMAGE_MULTIPLIER_EDEFAULT);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__MAX_THREAT:
        setMaxThreat(MAX_THREAT_EDEFAULT);
        return;
      case MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS:
        getEnemyLimits().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.DIFFICULTY_CONFIG__LEVEL:
        return level != LEVEL_EDEFAULT;
      case MazeDslPackage.DIFFICULTY_CONFIG__INSTANT_DEATH:
        return instantDeath != INSTANT_DEATH_EDEFAULT;
      case MazeDslPackage.DIFFICULTY_CONFIG__SPEED_MULTIPLIER:
        return speedMultiplier != SPEED_MULTIPLIER_EDEFAULT;
      case MazeDslPackage.DIFFICULTY_CONFIG__DAMAGE_MULTIPLIER:
        return damageMultiplier != DAMAGE_MULTIPLIER_EDEFAULT;
      case MazeDslPackage.DIFFICULTY_CONFIG__MAX_THREAT:
        return maxThreat != MAX_THREAT_EDEFAULT;
      case MazeDslPackage.DIFFICULTY_CONFIG__ENEMY_LIMITS:
        return enemyLimits != null && !enemyLimits.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (level: ");
    result.append(level);
    result.append(", instantDeath: ");
    result.append(instantDeath);
    result.append(", speedMultiplier: ");
    result.append(speedMultiplier);
    result.append(", damageMultiplier: ");
    result.append(damageMultiplier);
    result.append(", maxThreat: ");
    result.append(maxThreat);
    result.append(')');
    return result.toString();
  }

} //DifficultyConfigImpl
