/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import java.util.Collection;

import main.game.maze.dsl.mazeDsl.DifficultyConfig;
import main.game.maze.dsl.mazeDsl.GameConfiguration;
import main.game.maze.dsl.mazeDsl.Import;
import main.game.maze.dsl.mazeDsl.LootTableConfig;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;
import main.game.maze.dsl.mazeDsl.OpponentConfig;
import main.game.maze.dsl.mazeDsl.PatrolConfig;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Game Configuration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getDifficulty <em>Difficulty</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getOpponents <em>Opponents</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getPatrols <em>Patrols</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.GameConfigurationImpl#getLootTables <em>Loot Tables</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GameConfigurationImpl extends MinimalEObjectImpl.Container implements GameConfiguration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<Import> imports;

  /**
   * The cached value of the '{@link #getDifficulty() <em>Difficulty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDifficulty()
   * @generated
   * @ordered
   */
  protected DifficultyConfig difficulty;

  /**
   * The cached value of the '{@link #getOpponents() <em>Opponents</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpponents()
   * @generated
   * @ordered
   */
  protected EList<OpponentConfig> opponents;

  /**
   * The cached value of the '{@link #getPatrols() <em>Patrols</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatrols()
   * @generated
   * @ordered
   */
  protected EList<PatrolConfig> patrols;

  /**
   * The cached value of the '{@link #getLootTables() <em>Loot Tables</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLootTables()
   * @generated
   * @ordered
   */
  protected EList<LootTableConfig> lootTables;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GameConfigurationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.GAME_CONFIGURATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.GAME_CONFIGURATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Import> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<Import>(Import.class, this, MazeDslPackage.GAME_CONFIGURATION__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public DifficultyConfig getDifficulty()
  {
    return difficulty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDifficulty(DifficultyConfig newDifficulty, NotificationChain msgs)
  {
    DifficultyConfig oldDifficulty = difficulty;
    difficulty = newDifficulty;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY, oldDifficulty, newDifficulty);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDifficulty(DifficultyConfig newDifficulty)
  {
    if (newDifficulty != difficulty)
    {
      NotificationChain msgs = null;
      if (difficulty != null)
        msgs = ((InternalEObject)difficulty).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY, null, msgs);
      if (newDifficulty != null)
        msgs = ((InternalEObject)newDifficulty).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY, null, msgs);
      msgs = basicSetDifficulty(newDifficulty, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY, newDifficulty, newDifficulty));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<OpponentConfig> getOpponents()
  {
    if (opponents == null)
    {
      opponents = new EObjectContainmentEList<OpponentConfig>(OpponentConfig.class, this, MazeDslPackage.GAME_CONFIGURATION__OPPONENTS);
    }
    return opponents;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<PatrolConfig> getPatrols()
  {
    if (patrols == null)
    {
      patrols = new EObjectContainmentEList<PatrolConfig>(PatrolConfig.class, this, MazeDslPackage.GAME_CONFIGURATION__PATROLS);
    }
    return patrols;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LootTableConfig> getLootTables()
  {
    if (lootTables == null)
    {
      lootTables = new EObjectContainmentEList<LootTableConfig>(LootTableConfig.class, this, MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES);
    }
    return lootTables;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MazeDslPackage.GAME_CONFIGURATION__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY:
        return basicSetDifficulty(null, msgs);
      case MazeDslPackage.GAME_CONFIGURATION__OPPONENTS:
        return ((InternalEList<?>)getOpponents()).basicRemove(otherEnd, msgs);
      case MazeDslPackage.GAME_CONFIGURATION__PATROLS:
        return ((InternalEList<?>)getPatrols()).basicRemove(otherEnd, msgs);
      case MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES:
        return ((InternalEList<?>)getLootTables()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.GAME_CONFIGURATION__NAME:
        return getName();
      case MazeDslPackage.GAME_CONFIGURATION__IMPORTS:
        return getImports();
      case MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY:
        return getDifficulty();
      case MazeDslPackage.GAME_CONFIGURATION__OPPONENTS:
        return getOpponents();
      case MazeDslPackage.GAME_CONFIGURATION__PATROLS:
        return getPatrols();
      case MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES:
        return getLootTables();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.GAME_CONFIGURATION__NAME:
        setName((String)newValue);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends Import>)newValue);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY:
        setDifficulty((DifficultyConfig)newValue);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__OPPONENTS:
        getOpponents().clear();
        getOpponents().addAll((Collection<? extends OpponentConfig>)newValue);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__PATROLS:
        getPatrols().clear();
        getPatrols().addAll((Collection<? extends PatrolConfig>)newValue);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES:
        getLootTables().clear();
        getLootTables().addAll((Collection<? extends LootTableConfig>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.GAME_CONFIGURATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__IMPORTS:
        getImports().clear();
        return;
      case MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY:
        setDifficulty((DifficultyConfig)null);
        return;
      case MazeDslPackage.GAME_CONFIGURATION__OPPONENTS:
        getOpponents().clear();
        return;
      case MazeDslPackage.GAME_CONFIGURATION__PATROLS:
        getPatrols().clear();
        return;
      case MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES:
        getLootTables().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.GAME_CONFIGURATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MazeDslPackage.GAME_CONFIGURATION__IMPORTS:
        return imports != null && !imports.isEmpty();
      case MazeDslPackage.GAME_CONFIGURATION__DIFFICULTY:
        return difficulty != null;
      case MazeDslPackage.GAME_CONFIGURATION__OPPONENTS:
        return opponents != null && !opponents.isEmpty();
      case MazeDslPackage.GAME_CONFIGURATION__PATROLS:
        return patrols != null && !patrols.isEmpty();
      case MazeDslPackage.GAME_CONFIGURATION__LOOT_TABLES:
        return lootTables != null && !lootTables.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //GameConfigurationImpl


