/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import main.game.maze.dsl.mazeDsl.LootItemConfig;
import main.game.maze.dsl.mazeDsl.LootItemTypeEnum;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Loot Item Config</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl#getType <em>Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl#getValue <em>Value</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.LootItemConfigImpl#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LootItemConfigImpl extends MinimalEObjectImpl.Container implements LootItemConfig
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final LootItemTypeEnum TYPE_EDEFAULT = LootItemTypeEnum.FOOD;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected LootItemTypeEnum type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected static final int VALUE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected int value = VALUE_EDEFAULT;

  /**
   * The default value of the '{@link #getWeight() <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeight()
   * @generated
   * @ordered
   */
  protected static final int WEIGHT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWeight() <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWeight()
   * @generated
   * @ordered
   */
  protected int weight = WEIGHT_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LootItemConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.LOOT_ITEM_CONFIG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.LOOT_ITEM_CONFIG__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LootItemTypeEnum getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(LootItemTypeEnum newType)
  {
    LootItemTypeEnum oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.LOOT_ITEM_CONFIG__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(int newValue)
  {
    int oldValue = value;
    value = newValue;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.LOOT_ITEM_CONFIG__VALUE, oldValue, value));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getWeight()
  {
    return weight;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWeight(int newWeight)
  {
    int oldWeight = weight;
    weight = newWeight;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.LOOT_ITEM_CONFIG__WEIGHT, oldWeight, weight));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.LOOT_ITEM_CONFIG__NAME:
        return getName();
      case MazeDslPackage.LOOT_ITEM_CONFIG__TYPE:
        return getType();
      case MazeDslPackage.LOOT_ITEM_CONFIG__VALUE:
        return getValue();
      case MazeDslPackage.LOOT_ITEM_CONFIG__WEIGHT:
        return getWeight();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.LOOT_ITEM_CONFIG__NAME:
        setName((String)newValue);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__TYPE:
        setType((LootItemTypeEnum)newValue);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__VALUE:
        setValue((Integer)newValue);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__WEIGHT:
        setWeight((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.LOOT_ITEM_CONFIG__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__VALUE:
        setValue(VALUE_EDEFAULT);
        return;
      case MazeDslPackage.LOOT_ITEM_CONFIG__WEIGHT:
        setWeight(WEIGHT_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.LOOT_ITEM_CONFIG__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MazeDslPackage.LOOT_ITEM_CONFIG__TYPE:
        return type != TYPE_EDEFAULT;
      case MazeDslPackage.LOOT_ITEM_CONFIG__VALUE:
        return value != VALUE_EDEFAULT;
      case MazeDslPackage.LOOT_ITEM_CONFIG__WEIGHT:
        return weight != WEIGHT_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", type: ");
    result.append(type);
    result.append(", value: ");
    result.append(value);
    result.append(", weight: ");
    result.append(weight);
    result.append(')');
    return result.toString();
  }

} //LootItemConfigImpl


