/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import main.game.maze.dsl.mazeDsl.BehaviorTypeEnum;
import main.game.maze.dsl.mazeDsl.CharacterSpecifics;
import main.game.maze.dsl.mazeDsl.CharacterTypeEnum;
import main.game.maze.dsl.mazeDsl.LootTableConfig;
import main.game.maze.dsl.mazeDsl.MazeDslPackage;
import main.game.maze.dsl.mazeDsl.OpponentConfig;
import main.game.maze.dsl.mazeDsl.PatrolConfig;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Opponent Config</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getName <em>Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getType <em>Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getDisplayName <em>Display Name</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getHealth <em>Health</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getSpeed <em>Speed</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getThreatLevel <em>Threat Level</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#isEnabled <em>Enabled</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getBehavior <em>Behavior</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getCharacterSpecifics <em>Character Specifics</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getPatrolRef <em>Patrol Ref</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.OpponentConfigImpl#getLootRef <em>Loot Ref</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OpponentConfigImpl extends MinimalEObjectImpl.Container implements OpponentConfig
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final CharacterTypeEnum TYPE_EDEFAULT = CharacterTypeEnum.ZOMBIE;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected CharacterTypeEnum type = TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getDisplayName() <em>Display Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayName()
   * @generated
   * @ordered
   */
  protected static final String DISPLAY_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDisplayName() <em>Display Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDisplayName()
   * @generated
   * @ordered
   */
  protected String displayName = DISPLAY_NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getHealth() <em>Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHealth()
   * @generated
   * @ordered
   */
  protected static final int HEALTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getHealth() <em>Health</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHealth()
   * @generated
   * @ordered
   */
  protected int health = HEALTH_EDEFAULT;

  /**
   * The default value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected static final double SPEED_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected double speed = SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getThreatLevel() <em>Threat Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThreatLevel()
   * @generated
   * @ordered
   */
  protected static final double THREAT_LEVEL_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getThreatLevel() <em>Threat Level</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getThreatLevel()
   * @generated
   * @ordered
   */
  protected double threatLevel = THREAT_LEVEL_EDEFAULT;

  /**
   * The default value of the '{@link #isEnabled() <em>Enabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnabled()
   * @generated
   * @ordered
   */
  protected static final boolean ENABLED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEnabled() <em>Enabled</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnabled()
   * @generated
   * @ordered
   */
  protected boolean enabled = ENABLED_EDEFAULT;

  /**
   * The default value of the '{@link #getBehavior() <em>Behavior</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBehavior()
   * @generated
   * @ordered
   */
  protected static final BehaviorTypeEnum BEHAVIOR_EDEFAULT = BehaviorTypeEnum.PASSIVE;

  /**
   * The cached value of the '{@link #getBehavior() <em>Behavior</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBehavior()
   * @generated
   * @ordered
   */
  protected BehaviorTypeEnum behavior = BEHAVIOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getCharacterSpecifics() <em>Character Specifics</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCharacterSpecifics()
   * @generated
   * @ordered
   */
  protected CharacterSpecifics characterSpecifics;

  /**
   * The cached value of the '{@link #getPatrolRef() <em>Patrol Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatrolRef()
   * @generated
   * @ordered
   */
  protected PatrolConfig patrolRef;

  /**
   * The cached value of the '{@link #getLootRef() <em>Loot Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLootRef()
   * @generated
   * @ordered
   */
  protected LootTableConfig lootRef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OpponentConfigImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.OPPONENT_CONFIG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CharacterTypeEnum getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(CharacterTypeEnum newType)
  {
    CharacterTypeEnum oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDisplayName()
  {
    return displayName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDisplayName(String newDisplayName)
  {
    String oldDisplayName = displayName;
    displayName = newDisplayName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__DISPLAY_NAME, oldDisplayName, displayName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getHealth()
  {
    return health;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHealth(int newHealth)
  {
    int oldHealth = health;
    health = newHealth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__HEALTH, oldHealth, health));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getSpeed()
  {
    return speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpeed(double newSpeed)
  {
    double oldSpeed = speed;
    speed = newSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__SPEED, oldSpeed, speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getThreatLevel()
  {
    return threatLevel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setThreatLevel(double newThreatLevel)
  {
    double oldThreatLevel = threatLevel;
    threatLevel = newThreatLevel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__THREAT_LEVEL, oldThreatLevel, threatLevel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEnabled()
  {
    return enabled;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnabled(boolean newEnabled)
  {
    boolean oldEnabled = enabled;
    enabled = newEnabled;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__ENABLED, oldEnabled, enabled));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BehaviorTypeEnum getBehavior()
  {
    return behavior;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBehavior(BehaviorTypeEnum newBehavior)
  {
    BehaviorTypeEnum oldBehavior = behavior;
    behavior = newBehavior == null ? BEHAVIOR_EDEFAULT : newBehavior;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__BEHAVIOR, oldBehavior, behavior));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CharacterSpecifics getCharacterSpecifics()
  {
    return characterSpecifics;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCharacterSpecifics(CharacterSpecifics newCharacterSpecifics, NotificationChain msgs)
  {
    CharacterSpecifics oldCharacterSpecifics = characterSpecifics;
    characterSpecifics = newCharacterSpecifics;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS, oldCharacterSpecifics, newCharacterSpecifics);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCharacterSpecifics(CharacterSpecifics newCharacterSpecifics)
  {
    if (newCharacterSpecifics != characterSpecifics)
    {
      NotificationChain msgs = null;
      if (characterSpecifics != null)
        msgs = ((InternalEObject)characterSpecifics).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS, null, msgs);
      if (newCharacterSpecifics != null)
        msgs = ((InternalEObject)newCharacterSpecifics).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS, null, msgs);
      msgs = basicSetCharacterSpecifics(newCharacterSpecifics, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS, newCharacterSpecifics, newCharacterSpecifics));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PatrolConfig getPatrolRef()
  {
    if (patrolRef != null && patrolRef.eIsProxy())
    {
      InternalEObject oldPatrolRef = (InternalEObject)patrolRef;
      patrolRef = (PatrolConfig)eResolveProxy(oldPatrolRef);
      if (patrolRef != oldPatrolRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MazeDslPackage.OPPONENT_CONFIG__PATROL_REF, oldPatrolRef, patrolRef));
      }
    }
    return patrolRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PatrolConfig basicGetPatrolRef()
  {
    return patrolRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatrolRef(PatrolConfig newPatrolRef)
  {
    PatrolConfig oldPatrolRef = patrolRef;
    patrolRef = newPatrolRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__PATROL_REF, oldPatrolRef, patrolRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LootTableConfig getLootRef()
  {
    if (lootRef != null && lootRef.eIsProxy())
    {
      InternalEObject oldLootRef = (InternalEObject)lootRef;
      lootRef = (LootTableConfig)eResolveProxy(oldLootRef);
      if (lootRef != oldLootRef)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MazeDslPackage.OPPONENT_CONFIG__LOOT_REF, oldLootRef, lootRef));
      }
    }
    return lootRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LootTableConfig basicGetLootRef()
  {
    return lootRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLootRef(LootTableConfig newLootRef)
  {
    LootTableConfig oldLootRef = lootRef;
    lootRef = newLootRef;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.OPPONENT_CONFIG__LOOT_REF, oldLootRef, lootRef));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS:
        return basicSetCharacterSpecifics(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.OPPONENT_CONFIG__NAME:
        return getName();
      case MazeDslPackage.OPPONENT_CONFIG__TYPE:
        return getType();
      case MazeDslPackage.OPPONENT_CONFIG__DISPLAY_NAME:
        return getDisplayName();
      case MazeDslPackage.OPPONENT_CONFIG__HEALTH:
        return getHealth();
      case MazeDslPackage.OPPONENT_CONFIG__SPEED:
        return getSpeed();
      case MazeDslPackage.OPPONENT_CONFIG__THREAT_LEVEL:
        return getThreatLevel();
      case MazeDslPackage.OPPONENT_CONFIG__ENABLED:
        return isEnabled();
      case MazeDslPackage.OPPONENT_CONFIG__BEHAVIOR:
        return getBehavior();
      case MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS:
        return getCharacterSpecifics();
      case MazeDslPackage.OPPONENT_CONFIG__PATROL_REF:
        if (resolve) return getPatrolRef();
        return basicGetPatrolRef();
      case MazeDslPackage.OPPONENT_CONFIG__LOOT_REF:
        if (resolve) return getLootRef();
        return basicGetLootRef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.OPPONENT_CONFIG__NAME:
        setName((String)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__TYPE:
        setType((CharacterTypeEnum)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__DISPLAY_NAME:
        setDisplayName((String)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__HEALTH:
        setHealth((Integer)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__SPEED:
        setSpeed((Double)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__THREAT_LEVEL:
        setThreatLevel((Double)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__ENABLED:
        setEnabled((Boolean)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__BEHAVIOR:
        setBehavior((BehaviorTypeEnum)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS:
        setCharacterSpecifics((CharacterSpecifics)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__PATROL_REF:
        setPatrolRef((PatrolConfig)newValue);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__LOOT_REF:
        setLootRef((LootTableConfig)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.OPPONENT_CONFIG__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__TYPE:
        setType(TYPE_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__DISPLAY_NAME:
        setDisplayName(DISPLAY_NAME_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__HEALTH:
        setHealth(HEALTH_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__SPEED:
        setSpeed(SPEED_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__THREAT_LEVEL:
        setThreatLevel(THREAT_LEVEL_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__ENABLED:
        setEnabled(ENABLED_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__BEHAVIOR:
        setBehavior(BEHAVIOR_EDEFAULT);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS:
        setCharacterSpecifics((CharacterSpecifics)null);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__PATROL_REF:
        setPatrolRef((PatrolConfig)null);
        return;
      case MazeDslPackage.OPPONENT_CONFIG__LOOT_REF:
        setLootRef((LootTableConfig)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.OPPONENT_CONFIG__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MazeDslPackage.OPPONENT_CONFIG__TYPE:
        return type != TYPE_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__DISPLAY_NAME:
        return DISPLAY_NAME_EDEFAULT == null ? displayName != null : !DISPLAY_NAME_EDEFAULT.equals(displayName);
      case MazeDslPackage.OPPONENT_CONFIG__HEALTH:
        return health != HEALTH_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__SPEED:
        return speed != SPEED_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__THREAT_LEVEL:
        return threatLevel != THREAT_LEVEL_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__ENABLED:
        return enabled != ENABLED_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__BEHAVIOR:
        return behavior != BEHAVIOR_EDEFAULT;
      case MazeDslPackage.OPPONENT_CONFIG__CHARACTER_SPECIFICS:
        return characterSpecifics != null;
      case MazeDslPackage.OPPONENT_CONFIG__PATROL_REF:
        return patrolRef != null;
      case MazeDslPackage.OPPONENT_CONFIG__LOOT_REF:
        return lootRef != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", type: ");
    result.append(type);
    result.append(", displayName: ");
    result.append(displayName);
    result.append(", health: ");
    result.append(health);
    result.append(", speed: ");
    result.append(speed);
    result.append(", threatLevel: ");
    result.append(threatLevel);
    result.append(", enabled: ");
    result.append(enabled);
    result.append(", behavior: ");
    result.append(behavior);
    result.append(')');
    return result.toString();
  }

} //OpponentConfigImpl


