/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import main.game.maze.dsl.mazeDsl.MazeDslPackage;
import main.game.maze.dsl.mazeDsl.ProjectileTypeEnum;
import main.game.maze.dsl.mazeDsl.RangedSpecifics;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ranged Specifics</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl#getAttackRange <em>Attack Range</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl#getAttackCooldown <em>Attack Cooldown</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl#getProjectileSpeed <em>Projectile Speed</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl#getProjectileType <em>Projectile Type</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.RangedSpecificsImpl#getSplashRadius <em>Splash Radius</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RangedSpecificsImpl extends CharacterSpecificsImpl implements RangedSpecifics
{
  /**
   * The default value of the '{@link #getAttackRange() <em>Attack Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackRange()
   * @generated
   * @ordered
   */
  protected static final double ATTACK_RANGE_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getAttackRange() <em>Attack Range</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackRange()
   * @generated
   * @ordered
   */
  protected double attackRange = ATTACK_RANGE_EDEFAULT;

  /**
   * The default value of the '{@link #getAttackCooldown() <em>Attack Cooldown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackCooldown()
   * @generated
   * @ordered
   */
  protected static final int ATTACK_COOLDOWN_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getAttackCooldown() <em>Attack Cooldown</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttackCooldown()
   * @generated
   * @ordered
   */
  protected int attackCooldown = ATTACK_COOLDOWN_EDEFAULT;

  /**
   * The default value of the '{@link #getProjectileSpeed() <em>Projectile Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectileSpeed()
   * @generated
   * @ordered
   */
  protected static final double PROJECTILE_SPEED_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getProjectileSpeed() <em>Projectile Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectileSpeed()
   * @generated
   * @ordered
   */
  protected double projectileSpeed = PROJECTILE_SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getProjectileType() <em>Projectile Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectileType()
   * @generated
   * @ordered
   */
  protected static final ProjectileTypeEnum PROJECTILE_TYPE_EDEFAULT = ProjectileTypeEnum.STRAIGHT;

  /**
   * The cached value of the '{@link #getProjectileType() <em>Projectile Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProjectileType()
   * @generated
   * @ordered
   */
  protected ProjectileTypeEnum projectileType = PROJECTILE_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getSplashRadius() <em>Splash Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSplashRadius()
   * @generated
   * @ordered
   */
  protected static final double SPLASH_RADIUS_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getSplashRadius() <em>Splash Radius</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSplashRadius()
   * @generated
   * @ordered
   */
  protected double splashRadius = SPLASH_RADIUS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RangedSpecificsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.RANGED_SPECIFICS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getAttackRange()
  {
    return attackRange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttackRange(double newAttackRange)
  {
    double oldAttackRange = attackRange;
    attackRange = newAttackRange;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.RANGED_SPECIFICS__ATTACK_RANGE, oldAttackRange, attackRange));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getAttackCooldown()
  {
    return attackCooldown;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttackCooldown(int newAttackCooldown)
  {
    int oldAttackCooldown = attackCooldown;
    attackCooldown = newAttackCooldown;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.RANGED_SPECIFICS__ATTACK_COOLDOWN, oldAttackCooldown, attackCooldown));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getProjectileSpeed()
  {
    return projectileSpeed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProjectileSpeed(double newProjectileSpeed)
  {
    double oldProjectileSpeed = projectileSpeed;
    projectileSpeed = newProjectileSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_SPEED, oldProjectileSpeed, projectileSpeed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ProjectileTypeEnum getProjectileType()
  {
    return projectileType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setProjectileType(ProjectileTypeEnum newProjectileType)
  {
    ProjectileTypeEnum oldProjectileType = projectileType;
    projectileType = newProjectileType == null ? PROJECTILE_TYPE_EDEFAULT : newProjectileType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_TYPE, oldProjectileType, projectileType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getSplashRadius()
  {
    return splashRadius;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSplashRadius(double newSplashRadius)
  {
    double oldSplashRadius = splashRadius;
    splashRadius = newSplashRadius;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.RANGED_SPECIFICS__SPLASH_RADIUS, oldSplashRadius, splashRadius));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_RANGE:
        return getAttackRange();
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_COOLDOWN:
        return getAttackCooldown();
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_SPEED:
        return getProjectileSpeed();
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_TYPE:
        return getProjectileType();
      case MazeDslPackage.RANGED_SPECIFICS__SPLASH_RADIUS:
        return getSplashRadius();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_RANGE:
        setAttackRange((Double)newValue);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_COOLDOWN:
        setAttackCooldown((Integer)newValue);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_SPEED:
        setProjectileSpeed((Double)newValue);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_TYPE:
        setProjectileType((ProjectileTypeEnum)newValue);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__SPLASH_RADIUS:
        setSplashRadius((Double)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_RANGE:
        setAttackRange(ATTACK_RANGE_EDEFAULT);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_COOLDOWN:
        setAttackCooldown(ATTACK_COOLDOWN_EDEFAULT);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_SPEED:
        setProjectileSpeed(PROJECTILE_SPEED_EDEFAULT);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_TYPE:
        setProjectileType(PROJECTILE_TYPE_EDEFAULT);
        return;
      case MazeDslPackage.RANGED_SPECIFICS__SPLASH_RADIUS:
        setSplashRadius(SPLASH_RADIUS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_RANGE:
        return attackRange != ATTACK_RANGE_EDEFAULT;
      case MazeDslPackage.RANGED_SPECIFICS__ATTACK_COOLDOWN:
        return attackCooldown != ATTACK_COOLDOWN_EDEFAULT;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_SPEED:
        return projectileSpeed != PROJECTILE_SPEED_EDEFAULT;
      case MazeDslPackage.RANGED_SPECIFICS__PROJECTILE_TYPE:
        return projectileType != PROJECTILE_TYPE_EDEFAULT;
      case MazeDslPackage.RANGED_SPECIFICS__SPLASH_RADIUS:
        return splashRadius != SPLASH_RADIUS_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (attackRange: ");
    result.append(attackRange);
    result.append(", attackCooldown: ");
    result.append(attackCooldown);
    result.append(", projectileSpeed: ");
    result.append(projectileSpeed);
    result.append(", projectileType: ");
    result.append(projectileType);
    result.append(", splashRadius: ");
    result.append(splashRadius);
    result.append(')');
    return result.toString();
  }

} //RangedSpecificsImpl


