/**
 * generated by Xtext
 */
package main.game.maze.dsl.mazeDsl.impl;

import main.game.maze.dsl.mazeDsl.MazeDslPackage;
import main.game.maze.dsl.mazeDsl.Waypoint;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Waypoint</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.WaypointImpl#getX <em>X</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.WaypointImpl#getY <em>Y</em>}</li>
 *   <li>{@link main.game.maze.dsl.mazeDsl.impl.WaypointImpl#getWaitTime <em>Wait Time</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WaypointImpl extends MinimalEObjectImpl.Container implements Waypoint
{
  /**
   * The default value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected static final double X_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getX() <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getX()
   * @generated
   * @ordered
   */
  protected double x = X_EDEFAULT;

  /**
   * The default value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected static final double Y_EDEFAULT = 0.0;

  /**
   * The cached value of the '{@link #getY() <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getY()
   * @generated
   * @ordered
   */
  protected double y = Y_EDEFAULT;

  /**
   * The default value of the '{@link #getWaitTime() <em>Wait Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWaitTime()
   * @generated
   * @ordered
   */
  protected static final int WAIT_TIME_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getWaitTime() <em>Wait Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWaitTime()
   * @generated
   * @ordered
   */
  protected int waitTime = WAIT_TIME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WaypointImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MazeDslPackage.Literals.WAYPOINT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getX()
  {
    return x;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setX(double newX)
  {
    double oldX = x;
    x = newX;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.WAYPOINT__X, oldX, x));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public double getY()
  {
    return y;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setY(double newY)
  {
    double oldY = y;
    y = newY;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.WAYPOINT__Y, oldY, y));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getWaitTime()
  {
    return waitTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWaitTime(int newWaitTime)
  {
    int oldWaitTime = waitTime;
    waitTime = newWaitTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MazeDslPackage.WAYPOINT__WAIT_TIME, oldWaitTime, waitTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MazeDslPackage.WAYPOINT__X:
        return getX();
      case MazeDslPackage.WAYPOINT__Y:
        return getY();
      case MazeDslPackage.WAYPOINT__WAIT_TIME:
        return getWaitTime();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MazeDslPackage.WAYPOINT__X:
        setX((Double)newValue);
        return;
      case MazeDslPackage.WAYPOINT__Y:
        setY((Double)newValue);
        return;
      case MazeDslPackage.WAYPOINT__WAIT_TIME:
        setWaitTime((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.WAYPOINT__X:
        setX(X_EDEFAULT);
        return;
      case MazeDslPackage.WAYPOINT__Y:
        setY(Y_EDEFAULT);
        return;
      case MazeDslPackage.WAYPOINT__WAIT_TIME:
        setWaitTime(WAIT_TIME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MazeDslPackage.WAYPOINT__X:
        return x != X_EDEFAULT;
      case MazeDslPackage.WAYPOINT__Y:
        return y != Y_EDEFAULT;
      case MazeDslPackage.WAYPOINT__WAIT_TIME:
        return waitTime != WAIT_TIME_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (x: ");
    result.append(x);
    result.append(", y: ");
    result.append(y);
    result.append(", waitTime: ");
    result.append(waitTime);
    result.append(')');
    return result.toString();
  }

} //WaypointImpl
