/**
 * generated by Xtext 2.40.0
 */
package main.game.maze.formatting2;

import com.google.inject.Inject;
import main.game.maze.opponents.LootTable;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;

public class MazeCompFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private /* MazeCompGrammarAccess */Object _mazeCompGrammarAccess;

  protected void _format(final /* MazeFile */Object mazeFile, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nzombies cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nghosts cannot be resolved"
      + "\nformat cannot be resolved"
      + "\npumpkinBombers cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nlootTables cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nlootItems cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final LootTable lootTable, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\nformat cannot be resolved");
  }

  @XbaseGenerated
  public void format(final MazeFile lootTable, final IFormattableDocument document) {
    if (lootTable != null) {
      _format(lootTable, document);
      return;
    } else if (lootTable != null) {
      _format(lootTable, document);
      return;
    } else if (lootTable != null) {
      _format(lootTable, document);
      return;
    } else if (lootTable != null) {
      _format(lootTable, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(lootTable, document).toString());
    }
  }
}
